version: 2

models:
  - name: my_first_dbt_model
    description: "dbtモデルサンプル01"
    columns:
      - name: id
        description: "The primary key for this table"

  - name: my_second_dbt_model
    description: "dbtモデルサンプル02"
    columns:
      - name: id
        description: "The primary key for this table"
