version: 2

sources:
  - name: fivetran_db
    database: fivetran_database
    schema: oraclerds_lzdata01_dagster_dxpfy2d
    tables:
      - name: dagster_poc
      - name: my_fourth_dbt_model

  - name: edp_db
    database: edp_infra_sandbox_db
    schema: public
    tables:
      - name: asset03_01
      - name: asset06_03
