id: job_build_hokyunoki_mieruka
namespace: kestra_dbt_project.proj-job-hokyunoki_mieruka

labels:
  error: default_failed
  dbt: build

retry:
  behavior: CREATE_NEW_EXECUTION # or RETRY_FAILED_TASK
  type: exponential
  interval: PT5S
  maxAttempts: 7
  maxInterval: PT720S
  delayFactor: 30

# 手動実行時に指定できるdbtオプション
inputs:
  - id: dbt_options
    type: SELECT
    displayName: Choose dbt options
    values:
      - --full-refresh
    required: false
    allowCustomValue: true

variables:
  dbt_command:
    --select +stg_cvn06dodrshiji +stg_cvn18nosiodrjyoho_initial +stg_cvn18nosiodrjyoho_latest +stg_cvn18nosiodrjyoho_previous +stg_cvn35dsyukabin +stg_dvnp054a +stg_dvnp0700_odrno +stg_dvnp0710 +stg_dvnp4330 +stg_dvnp4520 +stg_dvnp5770 +stg_dvnp6490 +stg_dvsf509a +stg_shkjissekiruikei +stg_tbbofll +stg_tbchznl +stg_tbdaihl +stg_tbdaikl +stg_tbdaiml +stg_tbnokjs +stg_tbnoukifl +stg_tbnoukifl_initial +stg_tbnoukifl_latest +stg_tbnoukifl_previous +stg_tbnsyus +stg_tbsmksk +stg_tbuserm +scd_tbsmksk_noki +stg_dm_pno +stg_h_hanbaikt_frmkbn +stg_h_sinsyaodno +stg_lk_hanbaikt_frmkbn +stg_lk_sinsyaodno +stg_o_cvs11jyuchuu +stg_st_hanbaikt_frmkbn +stg_st_jpsalecar +stg_st_jpsalecar_frmkbn +stg_st_sinsyaodno +stg_yohinhinban
    --vars '{"DBT_JOB_NAME":"_hokyunoki_mieruka"}'

tasks:
  - id: clone_dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    commands:
      - dbt build {{ vars.dbt_command }}
        {{ inputs.dbt_options ?? "" }}

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "20 06 * * *"
    timezone: Asia/Tokyo

# エラーログを出力
errors:
  - id: error_log
    type: io.kestra.plugin.core.debug.Return
    format: "{{ errorLogs()[0]['message'] }}"

outputs: 
  - id: output_error_log
    type: STRING
    value: "{{ outputs.error_log.value ?? 'No message found.' }}"
  - id: output_state
    type: STRING
    value: "{{ tasks.clone_dbt_build.state ?? 'No state' }}"

# ログ出力
finally:
  - id: finally_log 
    type: io.kestra.plugin.core.log.Log
    message: 
      - "Git branch -> {{ namespace.GIT.BRANCH }}"
      - "dbt options -> {{ inputs.dbt_options ?? '' }}"
      - "dbt commands -> {{ vars.dbt_command }}"
      
disabled: false