variables:
  DAGSTER_CLOUD_ORGANIZATION: toyotadataplatform
  DAGSTER_PROJECT_DIR: .
  DAGSTER_CLOUD_YAML_PATH: dagster_cloud.yaml
  IMAGE_REGISTRY: 085931761001.dkr.ecr.ap-northeast-1.amazonaws.com/sajp1-dxpf-edp-ecr-dagster
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  DAGSTER_BUILD_STATEDIR: build-state

stages:
  - setup
  - build
  - deploy

workflow:
  rules:
    #- if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    #- if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'web'

initialize:
  stage: setup
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: ghcr.io/dagster-io/dagster-cloud-action:0.1.31
  script:
    - export
    - dagster-cloud ci check --project-dir=$DAGSTER_PROJECT_DIR --dagster-cloud-yaml-path=$DAGSTER_CLOUD_YAML_PATH
    - >
      dagster-cloud ci init --deployment=stg --statedir=$DAGSTER_BUILD_STATEDIR
      --project-dir=$DAGSTER_PROJECT_DIR --dagster-cloud-yaml-path=$DAGSTER_CLOUD_YAML_PATH
      --git-url=$CI_COMMIT_SHA
      --commit-hash=$CI_COMMIT_SHA
      --status-url=$CI_PIPELINE_URL
    - dagster-cloud ci status
  artifacts:
    paths:
      - $DAGSTER_BUILD_STATEDIR
    expire_in: 1 week

build-image:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - initialize
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - whoami
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $IMAGE_REGISTRY
  script:
    - docker build . -t $IMAGE_REGISTRY:$IMAGE_TAG
    - docker push $IMAGE_REGISTRY:$IMAGE_TAG
    - docker system prune -a -f --filter "until=24h"

deploy-docker:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-image
    - initialize
  image: ghcr.io/dagster-io/dagster-cloud-action:0.1.31
  script:
    - export
    - dagster-cloud ci set-build-output --image-tag=$IMAGE_TAG
    - dagster-cloud ci deploy

#deploy-docker-buranch:
#  stage: deploy
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#  dependencies:
#    - build-image
#    - initialize
#  image: ghcr.io/dagster-io/dagster-cloud-action:0.1.31
#  script:
#    - dagster-cloud ci set-build-output --image-tag=$IMAGE_TAG
#    - dagster-cloud ci deploy
#  environment:
#    name: branch/$CI_COMMIT_REF_NAME
#    on_stop: close-branch

#close-branch:
#  stage: deploy
#  image: ghcr.io/dagster-io/dagster-cloud-action:0.1.31
#  when: manual
#  only:
#    - merge_request
#  script:
#    - dagster-cloud ci branch-deployment $DAGSTER_PROJECT_DIR --mark-closed
#  environment:
#    name: branch/$CI_COMMIT_REF_NAME
#    action: stop
