{{ config(snowflake_warehouse='DBT_WH') }}

with substr_dvnp0680 as (
    select
        substr(raw_data, 1, 11)::VARCHAR(11) as ORDRKEY,
        substr(raw_data, 12, 1)::VARCHAR(1) as KOKAGKBN,
        substr(raw_data, 13, 4)::VARCHAR(4) as DATAKBN4,
        substr(raw_data, 17, 7)::VARCHAR(7) as DLRCD,
        substr(raw_data, 24, 1)::VARCHAR(1) as YUSOKBN,
        substr(raw_data, 25, 8)::VARCHAR(8) as ODRNO,
        substr(raw_data, 33, 8)::VARCHAR(8) as JUCHUYMD,
        substr(raw_data, 41, 4)::VARCHAR(4) as ITEMNO,
        substr(raw_data, 45, 20)::VARCHAR(20) as JHINBAN,
        substr(raw_data, 65, 2)::VARCHAR(2) as SYUBETSU,
        substr(raw_data, 67, 1)::VARCHAR(1) as ORDRTYPE,
        substr(raw_data, 68, 1)::VARCHAR(1) as ORDTSYRI,
        substr(raw_data, 69, 1)::VARCHAR(1) as KNKYUDO1,
        substr(raw_data, 70, 1)::VARCHAR(1) as ODRZOK,
        substr(raw_data, 71, 1)::VARCHAR(1) as YUMUKBN,
        substr(raw_data, 72, 1)::VARCHAR(1) as HYOFTNBS,
        substr(raw_data, 73, 1)::VARCHAR(1) as KYOSEICD,
        substr(raw_data, 74, 1)::VARCHAR(1) as HANBAICD,
        substr(raw_data, 75, 1)::VARCHAR(1) as BOCD,
        substr(raw_data, 76, 1)::VARCHAR(1) as YUSOUTCD,
        substr(raw_data, 77, 4)::VARCHAR(4) as SPDISCOUNT,
        substr(raw_data, 81, 1)::VARCHAR(1) as TUIKAKBN,
        substr(raw_data, 82, 1)::VARCHAR(1) as KKKSRKBN,
        substr(raw_data, 83, 8)::VARCHAR(8) as SAGYOKGNYMD,
        substr(raw_data, 91, 1)::VARCHAR(1) as ZUIZIKBN,
        substr(raw_data, 92, 3)::VARCHAR(3) as ZUIZIRTU,
        substr(raw_data, 95, 4)::VARCHAR(4) as BETMKCD,
        substr(raw_data, 99, 8)::VARCHAR(8) as JYUSYYMD,
        substr(raw_data, 107, 6)::VARCHAR(6) as JUCHUSU,
        substr(raw_data, 113, 6)::VARCHAR(6) as PROJUSUU6,
        substr(raw_data, 119, 3)::VARCHAR(3) as TARIFCD,
        substr(raw_data, 122, 9)::VARCHAR(9) as TOKTANKA9,
        substr(raw_data, 131, 8)::VARCHAR(8) as TANSJYMD,
        substr(raw_data, 139, 10)::VARCHAR(10) as RIMAK1,
        substr(raw_data, 149, 1)::VARCHAR(1) as RIMAK2,
        substr(raw_data, 150, 1)::VARCHAR(1) as BNRKYSCD,
        substr(raw_data, 151, 1)::VARCHAR(1) as BEKONCD,
        substr(raw_data, 152, 20)::VARCHAR(20) as SIMKMEIK,
        substr(raw_data, 172, 3)::VARCHAR(3) as SIMKMEIJP,
        substr(raw_data, 175, 8)::VARCHAR(8) as YUSTGTCD,
        substr(raw_data, 183, 1)::VARCHAR(1) as ORDRCYCL,
        substr(raw_data, 184, 7)::VARCHAR(7) as SDLRCD,
        substr(raw_data, 191, 1)::VARCHAR(1) as PSHUKAKBN,
        substr(raw_data, 192, 1)::VARCHAR(1) as DOUKNHUKAKBN,
        substr(raw_data, 193, 1)::VARCHAR(1) as SYTYUBANFLG,
        substr(raw_data, 194, 1)::VARCHAR(1) as TANDKBAN,
        substr(raw_data, 195, 1)::VARCHAR(1) as KNPKTCD,
        substr(raw_data, 196, 3)::VARCHAR(3) as HANSTSAKCD,
        substr(raw_data, 199, 3)::VARCHAR(3) as ETCTES,
        substr(raw_data, 202, 2)::VARCHAR(2) as KESSAI,
        substr(raw_data, 204, 1)::VARCHAR(1) as TATNKBN,
        substr(raw_data, 205, 1)::VARCHAR(1) as TNDKINV,
        substr(raw_data, 206, 1)::VARCHAR(1) as TARIFDKN,
        substr(raw_data, 207, 2)::VARCHAR(2) as PFCD,
        substr(raw_data, 209, 16)::VARCHAR(16) as MTUSERID,
        substr(raw_data, 225, 26)::VARCHAR(26) as MTTIME,
        substr(raw_data, 251, 45)::VARCHAR(45) as FILLER,
        LDTS
    from {{ source('snowpipe_db_valuechain', 'raw_dvnp0680') }}
)
select * from substr_dvnp0680
        