with substr_ktrla01vzz0kvr00qe as (
    select
        substr(raw_data, 1, 1)::varchar(1) as syoritype,
        substr(raw_data, 2, 8)::varchar(8) as uketukeymd,
        substr(raw_data, 10, 17)::varchar(17) as uketuketime,
        substr(raw_data, 27, 4)::varchar(4) as dataid,
        substr(raw_data, 31, 4)::varchar(4) as tyohyono,
        substr(raw_data, 35, 2)::varchar(2) as ukeirecd,
        substr(raw_data, 37, 1)::varchar(1) as nnkyotnkbn,
        substr(raw_data, 38, 1)::varchar(1) as kaknokyotnkbn,
        substr(raw_data, 39, 20)::varchar(20) as tyotathb,
        substr(raw_data, 59, 4)::varchar(4) as srsirskcd,
        substr(raw_data, 63, 4)::varchar(4) as brsirskcd,
        substr(raw_data, 67, 1)::varchar(1) as kanbnkbn,
        substr(raw_data, 68, 6)::varchar(6) as nsinnsu,
        substr(raw_data, 74, 5)::varchar(5) as teiseisu,
        substr(raw_data, 79, 2)::varchar(2) as nnyoteibi,
        substr(raw_data, 81, 8)::varchar(8) as nnymd,
        substr(raw_data, 89, 4)::varchar(4) as motikomisk,
        substr(raw_data, 93, 8)::varchar(8) as tcksyrbi,
        substr(raw_data, 101, 4)::varchar(4) as tckyomitritime,
        substr(raw_data, 105, 2)::varchar(2) as inputbasyocd,
        substr(raw_data, 107, 5)::varchar(5) as nnbangou,
        substr(raw_data, 112, 2)::varchar(2) as kiban,
        substr(raw_data, 114, 5)::varchar(5) as syrrenbn,
        substr(raw_data, 119, 1)::varchar(1) as r1kbn,
        substr(raw_data, 120, 1)::varchar(1) as cardno,
        substr(raw_data, 121, 2)::varchar(2) as nnbin,
        substr(raw_data, 123, 1)::varchar(1) as srsirskkojocd,
        substr(raw_data, 124, 3)::varchar(3) as srsirsksykajocd,
        substr(raw_data, 127, 1)::varchar(1) as brsirskkojocd,
        substr(raw_data, 128, 3)::varchar(3) as brsirsksykajocd,
        substr(raw_data, 131, 6)::varchar(6) as tcknnbi,
        substr(raw_data, 137, 2)::varchar(2) as tcknnbin,
        substr(raw_data, 139, 1)::varchar(1) as uketukeflg,
        substr(raw_data, 140, 1)::varchar(1) as syrkekaflg,
        substr(raw_data, 141, 1)::varchar(1) as zikhneiumu,
        substr(raw_data, 142, 1)::varchar(1) as jissekkejyumu,
        substr(raw_data, 143, 2)::varchar(2) as ukterrflg,
        substr(raw_data, 145, 7)::varchar(7) as kknkigusyosu,
        substr(raw_data, 152, 10)::varchar(10) as sgyloke,
        substr(raw_data, 162, 5)::varchar(5) as nonyutni,
        substr(raw_data, 167, 1)::varchar(1) as hosobasyokbn,
        substr(raw_data, 168, 2)::varchar(2) as hososyubicd,
        substr(raw_data, 170, 2)::varchar(2) as orosibacd,
        substr(raw_data, 172, 19)::varchar(19) as errmsg,
        substr(raw_data, 191, 26)::varchar(26) as mttime,
        substr(raw_data, 217, 63)::varchar(63) as filler,
        ldts,
        line_number
    from {{source('snowpipe_db_valuechain', 'raw_ktrla01vzz0kvr00qe')}}
)
select * from substr_ktrla01vzz0kvr00qe