with substr_ktrla01vzz0kvq00m8 as (
    select
        substr(raw_data, 1, 1)::varchar(1) as mntkbn,
        substr(raw_data, 2, 4)::varchar(4) as thyono,
        substr(raw_data, 6, 6)::varchar(6) as jissekiym,
        substr(raw_data, 12, 20)::varchar(20) as hinban,
        substr(raw_data, 32, 7)::varchar(7) as distfd,
        substr(raw_data, 39, 4)::varchar(4) as renban,
        substr(raw_data, 43, 5)::varchar(5) as daihyoudist,
        substr(raw_data, 48, 3)::varchar(3) as pricls,
        substr(raw_data, 51, 4)::varchar(4) as hinmkcd,
        substr(raw_data, 55, 1)::varchar(1) as tukacd,
        substr(raw_data, 56, 1)::varchar(1) as syokokukbn,
        substr(raw_data, 57, 1)::varchar(1) as tokuteikokukbn,
        substr(raw_data, 58, 1)::varchar(1) as kodankokukbn,
        substr(raw_data, 59, 3)::varchar(3) as hnknhrtitiritu,
        substr(raw_data, 62, 3)::varchar(3) as hankanrhinhan,
        substr(raw_data, 65, 5)::varchar(5) as jisseiwsratehx,
        substr(raw_data, 70, 5)::varchar(5) as zenteiwsratehx,
        substr(raw_data, 75, 5)::varchar(5) as skutisenhannka,
        substr(raw_data, 80, 15)::varchar(15) as jssiurgknh15,
        substr(raw_data, 95, 15)::varchar(15) as zeurikinhanka,
        substr(raw_data, 110, 11)::varchar(11) as uriagekosuhanka,
        substr(raw_data, 121, 9)::varchar(9) as kijungenka9hanx,
        substr(raw_data, 130, 9)::varchar(9) as tankahanka,
        substr(raw_data, 139, 15)::varchar(15) as sogenka1itirihn,
        substr(raw_data, 154, 15)::varchar(15) as sogenka2hinmohn,
        substr(raw_data, 169, 15)::varchar(15) as jisseisnek1hn,
        substr(raw_data, 184, 15)::varchar(15) as jisseisnek2hn,
        substr(raw_data, 199, 15)::varchar(15) as zentsonekig1han,
        substr(raw_data, 214, 15)::varchar(15) as zentsonekig2han,
        substr(raw_data, 229, 12)::varchar(12) as dairitenmei,
        substr(raw_data, 241, 3)::varchar(3) as tiikicd3,
        substr(raw_data, 244, 3)::varchar(3) as rgncd3,
        substr(raw_data, 247, 7)::varchar(7) as setteidistfd,
        substr(raw_data, 254, 15)::varchar(15) as ararigaku1han,
        substr(raw_data, 269, 15)::varchar(15) as ararigaku2han,
        substr(raw_data, 284, 15)::varchar(15) as hankanhihanx,
        substr(raw_data, 299, 15)::varchar(15) as genkagakuhanka,
        substr(raw_data, 314, 2)::varchar(2) as kyokuflg,
        substr(raw_data, 316, 43)::varchar(43) as filler,
        substr(raw_data, 359, 16)::varchar(16) as mtuserid,
        substr(raw_data, 375, 26)::varchar(26) as mttime,
        ldts,
        line_number
    from {{source('snowpipe_db_valuechain', 'raw_ktrla01vzz0kvq00m8')}}
)
select * from substr_ktrla01vzz0kvq00m8