{{ config(snowflake_warehouse='DBT_WH') }}

with substr_dvnp0710 as (
    select
        substr(raw_data, 1, 1)::VARCHAR(1) as MNTKBN,
        substr(raw_data, 2, 11)::VARCHAR(11) as ORDRKEY,
        substr(raw_data, 13, 8)::VARCHAR(8) as JURRSYMD,
        substr(raw_data, 21, 11)::VARCHAR(11) as TANSKKEY,
        substr(raw_data, 32, 20)::VARCHAR(20) as SHINBAN,
        substr(raw_data, 52, 7)::VARCHAR(7) as DLRCD,
        substr(raw_data, 59, 8)::VARCHAR(8) as ODRNO,
        substr(raw_data, 67, 4)::VARCHAR(4) as ITEMNO,
        substr(raw_data, 71, 1)::VARCHAR(1) as KOKAGKBN,
        substr(raw_data, 72, 1)::VARCHAR(1) as YUSOKBN,
        substr(raw_data, 73, 2)::VARCHAR(2) as SYUBETSU,
        substr(raw_data, 75, 1)::VARCHAR(1) as ORDRTYPE,
        substr(raw_data, 76, 1)::VARCHAR(1) as ORDTSYRI,
        substr(raw_data, 77, 1)::VARCHAR(1) as KNKYUDO1,
        substr(raw_data, 78, 1)::VARCHAR(1) as ODRZOK,
        substr(raw_data, 79, 6)::VARCHAR(6) as BOSU,
        substr(raw_data, 85, 8)::VARCHAR(8) as JUCHUYMD,
        substr(raw_data, 93, 6)::VARCHAR(6) as JUCHUSU,
        substr(raw_data, 99, 3)::VARCHAR(3) as SYYHENCT,
        substr(raw_data, 102, 3)::VARCHAR(3) as ETDHENCT,
        substr(raw_data, 105, 1)::VARCHAR(1) as MKAITOCD,
        substr(raw_data, 106, 1)::VARCHAR(1) as HNKKBN,
        substr(raw_data, 107, 12)::VARCHAR(12) as HNNOYTIME,
        substr(raw_data, 119, 12)::VARCHAR(12) as HNTAYTIME,
        substr(raw_data, 131, 12)::VARCHAR(12) as HNSYYTIME,
        substr(raw_data, 143, 12)::VARCHAR(12) as HNTOYTIME,
        substr(raw_data, 155, 8)::VARCHAR(8) as HNKTOYMD,
        substr(raw_data, 163, 1)::VARCHAR(1) as ENKKBN,
        substr(raw_data, 164, 8)::VARCHAR(8) as ENFYTYMD,
        substr(raw_data, 172, 8)::VARCHAR(8) as ENKTOYMD,
        substr(raw_data, 180, 1)::VARCHAR(1) as HOKKBN,
        substr(raw_data, 181, 12)::VARCHAR(12) as HONOYTIME,
        substr(raw_data, 193, 12)::VARCHAR(12) as HOTAYTIME,
        substr(raw_data, 205, 12)::VARCHAR(12) as HOSYYTIME,
        substr(raw_data, 217, 12)::VARCHAR(12) as HOTOYTIME,
        substr(raw_data, 229, 8)::VARCHAR(8) as HOKTOYMD,
        substr(raw_data, 237, 1)::VARCHAR(1) as EOKKBN,
        substr(raw_data, 238, 8)::VARCHAR(8) as EOFYTYMD,
        substr(raw_data, 246, 8)::VARCHAR(8) as EOKTOYMD,
        substr(raw_data, 254, 1)::VARCHAR(1) as HSKKBN,
        substr(raw_data, 255, 12)::VARCHAR(12) as HSNOYTIME,
        substr(raw_data, 267, 12)::VARCHAR(12) as HSTAYTIME,
        substr(raw_data, 279, 12)::VARCHAR(12) as HSSYYTIME,
        substr(raw_data, 291, 12)::VARCHAR(12) as HSTOYTIME,
        substr(raw_data, 303, 8)::VARCHAR(8) as HSKTOYMD,
        substr(raw_data, 311, 1)::VARCHAR(1) as ESKKBN,
        substr(raw_data, 312, 8)::VARCHAR(8) as ESFYTYMD,
        substr(raw_data, 320, 8)::VARCHAR(8) as ESKTOYMD,
        substr(raw_data, 328, 1)::VARCHAR(1) as PTOPFLG,
        substr(raw_data, 329, 1)::VARCHAR(1) as MARTFLG,
        substr(raw_data, 330, 6)::VARCHAR(6) as SKJUNI,
        substr(raw_data, 336, 1)::VARCHAR(1) as KAKNOUKBN,
        substr(raw_data, 337, 12)::VARCHAR(12) as IPSYYTMIE,
        substr(raw_data, 349, 8)::VARCHAR(8) as IPFYTYMD,
        substr(raw_data, 357, 16)::VARCHAR(16) as MTUSERID,
        substr(raw_data, 373, 26)::VARCHAR(26) as MTTIME,
        substr(raw_data, 399, 12)::VARCHAR(12) as FILLER,
        LDTS
    from {{ source('snowpipe_db_valuechain', 'raw_dvnp0710') }}
)
select * from substr_dvnp0710
        