with stg_siyoumst_katashiki as (
    select
        mtkbn::varchar(1) as mtkbn, --C,U,Dのメンテ区分
        segmei::varchar(8) as segmei,
        renkey_hkata::varchar(20) as renkey_hkata,
        renkey_sedai::varchar(1) as renkey_sedai,
        hkata::varchar(20) as hkata,
        sedai::varchar(1) as sedai,
        jkkyy::varchar(4) as jkkyy,
        jkkmm::varchar(2) as jkkmm,
        jkkdd::varchar(2) as jkkdd,
        jkmyy::varchar(4) as jkmyy,
        jkmmm::varchar(2) as jkmmm,
        jkmdd::varchar(2) as jkmdd,
        dkkyy::varchar(4) as dkkyy,
        dkkmm::varchar(2) as dkkmm,
        dkkdd::varchar(2) as dkkdd,
        dkmyy::varchar(4) as dkmyy,
        dkmmm::varchar(2) as dkmmm,
        dkmdd::varchar(2) as dkmdd,
        syamei::varchar(2) as syamei,
        sno::varchar(2) as sno,
        odt::varchar(1) as odt,
        katacd::varchar(5) as katacd,
        bkata::varchar(20) as bkata,
        ckata::varchar(16) as ckata,
        fix::varchar(1) as fix,
        seikbn1::varchar(1) as seikbn1,
        seijbn1::varchar(1) as seijbn1,
        seiyk1::varchar(5) as seiyk1,
        seibkbn1::varchar(1) as seibkbn1,
        seikbn2::varchar(1) as seikbn2,
        seijbn2::varchar(1) as seijbn2,
        seiyk2::varchar(5) as seiyk2,
        seibkbn2::varchar(1) as seibkbn2,
        seikbn3::varchar(1) as seikbn3,
        seijbn3::varchar(1) as seijbn3,
        seiyk3::varchar(5) as seiyk3,
        seibkbn3::varchar(1) as seibkbn3,
        seikbn4::varchar(1) as seikbn4,
        seijbn4::varchar(1) as seijbn4,
        seiyk4::varchar(5) as seiyk4,
        seibkbn4::varchar(1) as seibkbn4,
        seikbn5::varchar(1) as seikbn5,
        seijbn5::varchar(1) as seijbn5,
        seiyk5::varchar(5) as seiyk5,
        seibkbn5::varchar(1) as seibkbn5,
        seikbn6::varchar(1) as seikbn6,
        seijbn6::varchar(1) as seijbn6,
        seiyk6::varchar(5) as seiyk6,
        seibkbn6::varchar(1) as seibkbn6,
        seikbn7::varchar(1) as seikbn7,
        seijbn7::varchar(1) as seijbn7,
        seiyk7::varchar(5) as seiyk7,
        seibkbn7::varchar(1) as seibkbn7,
        seikbn8::varchar(1) as seikbn8,
        seijbn8::varchar(1) as seijbn8,
        seiyk8::varchar(5) as seiyk8,
        seibkbn8::varchar(1) as seibkbn8,
        seikbn9::varchar(1) as seikbn9,
        seijbn9::varchar(1) as seijbn9,
        seiyk9::varchar(5) as seiyk9,
        seibkbn9::varchar(1) as seibkbn9,
        seikbn10::varchar(1) as seikbn10,
        seijbn10::varchar(1) as seijbn10,
        seiyk10::varchar(5) as seiyk10,
        seibkbn10::varchar(1) as seibkbn10,
        tecs::varchar(1) as tecs,
        kmaker::varchar(5) as kmaker,
        hassou::varchar(1) as hassou,
        sofu::varchar(1) as sofu,
        lflg::varchar(1) as lflg,
        ldts,
        row_number() over (
            partition by 
                segmei, renkey_hkata, renkey_sedai, ldts
            order by ldts desc, line_number desc
        ) aggkey
        from {{ ref('substr_tsjfa38t1') }}
        where rtrim(segmei,' 　') = 'EA31022'
)
select * exclude(aggkey,mtkbn)
from stg_siyoumst_katashiki
where aggkey = 1 and mtkbn in ('C','U')