with stg_jukyustatus_syaryosys as (
    select
        dlrcd::varchar(5) as dlrcd, 
        chumon::varchar(10) as chumon, 
        jyuhasei::varchar(8) as jyuhasei, 
        fkbn::varchar(1) as fkbn, 
        jyucyubi::varchar(8) as jyucyubi, 
        furiate::varchar(8) as furiate, 
        zaihen::varchar(5) as zaihen, 
        tatennyu::varchar(5) as tatennyu, 
        tenfuri::varchar(5) as tenfuri, 
        genyu::varchar(5) as genyu, 
        jyojyubi::varchar(8) as jyojyubi, 
        torokibo::varchar(8) as torokibo, 
        toroyote::varchar(8) as toroyote, 
        torkbi::varchar(8) as torkbi, 
        hanbaibi::varchar(8) as hanbaibi, 
        nouskibo::varchar(8) as nouskibo, 
        knobisya::varchar(8) as knobisya, 
        simuke::varchar(5) as simuke, 
        odno::varchar(12) as odno, 
        ojyy::varchar(4) as ojyy, 
        zaiko::varchar(5) as zaiko, 
        yusou::varchar(8) as yusou, 
        odrjuri::varchar(8) as odrjuri, 
        knouki::varchar(8) as knouki, 
        kyotei::varchar(8) as kyotei, 
        hyotei::varchar(8) as hyotei, 
        saihai::varchar(8) as saihai, 
        tyotei::varchar(8) as tyotei, 
        saitou::varchar(8) as saitou, 
        bkbn::varchar(1) as bkbn, 
        frmkbn::varchar(3) as frmkbn, 
        frmno::varchar(7) as frmno, 
        syukka::varchar(8) as syukka, 
        idline::varchar(2) as idline, 
        ident::varchar(10) as ident, 
        bdno::varchar(5) as bdno, 
        lokeikak::varchar(8) as lokeikak, 
        chakuko::varchar(8) as chakuko, 
        turiage::varchar(8) as turiage, 
        lineoff::varchar(8) as lineoff, 
        syuken::varchar(8) as syuken, 
        haisya::varchar(8) as haisya, 
        plant::varchar(1) as plant, 
        gyokbn::varchar(1) as gyokbn, 
        syokbn::varchar(1) as syokbn, 
        hancd::varchar(7) as hancd, 
        jymd::varchar(8) as jymd, 
        endflg::varchar(1) as endflg, 
        funatumi::varchar(7) as funatumi, 
        funaage::varchar(7) as funaage, 
        sno::varchar(2) as sno, 
        shamei::varchar(2) as shamei, 
        dfsc::varchar(5) as dfsc, 
        wax::varchar(1) as wax, 
        tecs::varchar(1) as tecs, 
        kmaker::varchar(5) as kmaker, 
        hkata::varchar(20) as hkata, 
        gaicd::varchar(4) as gaicd, 
        ucd::varchar(4) as ucd, 
        tire::varchar(3) as tire, 
        joption::varchar(80) as joption, 
        hoption::varchar(80) as hoption, 
        skibdate::varchar(8) as skibdate, 
        lexustenpo::varchar(5) as lexustenpo, 
        ldts
    from {{ ref('substr_tsjfa36q') }}
)
select * from stg_jukyustatus_syaryosys
where ldts = (select max(ldts) from stg_jukyustatus_syaryosys)