with stg_noryokuwaku_date_syaryosys as (
    select
        dum::varchar(1) as dum, 
        segmei::varchar(8) as segmei, 
        renkey_shamei::varchar(2) as renkey_shamei, 
        renkey_sno::varchar(2) as renkey_sno, 
        renkey_nen::varchar(4) as renkey_nen, 
        renkey_tuki::varchar(2) as renkey_tuki, 
        renkey_kncode::varchar(7) as renkey_kncode, 
        renkey_knkubn::varchar(1) as renkey_knkubn, 
        renkey_dum2::varchar(102) as renkey_dum2, 
        freekbn::varchar(1) as freekbn, 
        knkubn::varchar(1) as knkubn, 
        dsyubetum::varchar(9) as dsyubetum, 
        daisu01::varchar(5) as daisu01, 
        daisu02::varchar(5) as daisu02, 
        daisu03::varchar(5) as daisu03, 
        daisu04::varchar(5) as daisu04, 
        daisu05::varchar(5) as daisu05, 
        daisu06::varchar(5) as daisu06, 
        daisu07::varchar(5) as daisu07, 
        daisu08::varchar(5) as daisu08, 
        daisu09::varchar(5) as daisu09, 
        daisu10::varchar(5) as daisu10, 
        daisu11::varchar(5) as daisu11, 
        daisu12::varchar(5) as daisu12, 
        daisu13::varchar(5) as daisu13, 
        daisu14::varchar(5) as daisu14, 
        daisu15::varchar(5) as daisu15, 
        daisu16::varchar(5) as daisu16, 
        daisu17::varchar(5) as daisu17, 
        daisu18::varchar(5) as daisu18, 
        daisu19::varchar(5) as daisu19, 
        daisu20::varchar(5) as daisu20, 
        daisu21::varchar(5) as daisu21, 
        daisu22::varchar(5) as daisu22, 
        daisu23::varchar(5) as daisu23, 
        daisu24::varchar(5) as daisu24, 
        daisu25::varchar(5) as daisu25, 
        daisu26::varchar(5) as daisu26, 
        daisu27::varchar(5) as daisu27, 
        daisu28::varchar(5) as daisu28, 
        daisu29::varchar(5) as daisu29, 
        daisu30::varchar(5) as daisu30, 
        daisu31::varchar(5) as daisu31, 
        dummy::varchar(5) as dummy, 
        ldts
    from {{ ref('substr_da34b17') }}
)
select * from stg_noryokuwaku_date_syaryosys
where ldts = (select max(ldts) from stg_noryokuwaku_date_syaryosys)