with stg_kinobetsu_noryoku_daisusyukei_syaryosys as (
    select
        shamei::varchar(2) as shamei,
        sno::varchar(2) as sno,
        kncode::varchar(7) as kncode,
        sym::varchar(6) as sym,
        odt::varchar(1) as odt,
        ln::varchar(2) as ln,
        knsyukeikbn::varchar(1) as knsyukeikbn,
        to_decimal(iff(rtrim(stdai, ' 　') = '', 0, rtrim(stdai, ' 　')))::decimal(5,0) as stdai,
        to_decimal(iff(rtrim(sdai_01bi, ' 　') = '', 0, rtrim(sdai_01bi, ' 　')))::decimal(5,0) as sdai_01bi,
        to_decimal(iff(rtrim(sdai_02bi, ' 　') = '', 0, rtrim(sdai_02bi, ' 　')))::decimal(5,0) as sdai_02bi,
        to_decimal(iff(rtrim(sdai_03bi, ' 　') = '', 0, rtrim(sdai_03bi, ' 　')))::decimal(5,0) as sdai_03bi,
        to_decimal(iff(rtrim(sdai_04bi, ' 　') = '', 0, rtrim(sdai_04bi, ' 　')))::decimal(5,0) as sdai_04bi,
        to_decimal(iff(rtrim(sdai_05bi, ' 　') = '', 0, rtrim(sdai_05bi, ' 　')))::decimal(5,0) as sdai_05bi,
        to_decimal(iff(rtrim(sdai_06bi, ' 　') = '', 0, rtrim(sdai_06bi, ' 　')))::decimal(5,0) as sdai_06bi,
        to_decimal(iff(rtrim(sdai_07bi, ' 　') = '', 0, rtrim(sdai_07bi, ' 　')))::decimal(5,0) as sdai_07bi,
        to_decimal(iff(rtrim(sdai_08bi, ' 　') = '', 0, rtrim(sdai_08bi, ' 　')))::decimal(5,0) as sdai_08bi,
        to_decimal(iff(rtrim(sdai_09bi, ' 　') = '', 0, rtrim(sdai_09bi, ' 　')))::decimal(5,0) as sdai_09bi,
        to_decimal(iff(rtrim(sdai_10bi, ' 　') = '', 0, rtrim(sdai_10bi, ' 　')))::decimal(5,0) as sdai_10bi,
        to_decimal(iff(rtrim(sdai_11bi, ' 　') = '', 0, rtrim(sdai_11bi, ' 　')))::decimal(5,0) as sdai_11bi,
        to_decimal(iff(rtrim(sdai_12bi, ' 　') = '', 0, rtrim(sdai_12bi, ' 　')))::decimal(5,0) as sdai_12bi,
        to_decimal(iff(rtrim(sdai_13bi, ' 　') = '', 0, rtrim(sdai_13bi, ' 　')))::decimal(5,0) as sdai_13bi,
        to_decimal(iff(rtrim(sdai_14bi, ' 　') = '', 0, rtrim(sdai_14bi, ' 　')))::decimal(5,0) as sdai_14bi,
        to_decimal(iff(rtrim(sdai_15bi, ' 　') = '', 0, rtrim(sdai_15bi, ' 　')))::decimal(5,0) as sdai_15bi,
        to_decimal(iff(rtrim(sdai_16bi, ' 　') = '', 0, rtrim(sdai_16bi, ' 　')))::decimal(5,0) as sdai_16bi,
        to_decimal(iff(rtrim(sdai_17bi, ' 　') = '', 0, rtrim(sdai_17bi, ' 　')))::decimal(5,0) as sdai_17bi,
        to_decimal(iff(rtrim(sdai_18bi, ' 　') = '', 0, rtrim(sdai_18bi, ' 　')))::decimal(5,0) as sdai_18bi,
        to_decimal(iff(rtrim(sdai_19bi, ' 　') = '', 0, rtrim(sdai_19bi, ' 　')))::decimal(5,0) as sdai_19bi,
        to_decimal(iff(rtrim(sdai_20bi, ' 　') = '', 0, rtrim(sdai_20bi, ' 　')))::decimal(5,0) as sdai_20bi,
        to_decimal(iff(rtrim(sdai_21bi, ' 　') = '', 0, rtrim(sdai_21bi, ' 　')))::decimal(5,0) as sdai_21bi,
        to_decimal(iff(rtrim(sdai_22bi, ' 　') = '', 0, rtrim(sdai_22bi, ' 　')))::decimal(5,0) as sdai_22bi,
        to_decimal(iff(rtrim(sdai_23bi, ' 　') = '', 0, rtrim(sdai_23bi, ' 　')))::decimal(5,0) as sdai_23bi,
        to_decimal(iff(rtrim(sdai_24bi, ' 　') = '', 0, rtrim(sdai_24bi, ' 　')))::decimal(5,0) as sdai_24bi,
        to_decimal(iff(rtrim(sdai_25bi, ' 　') = '', 0, rtrim(sdai_25bi, ' 　')))::decimal(5,0) as sdai_25bi,
        to_decimal(iff(rtrim(sdai_26bi, ' 　') = '', 0, rtrim(sdai_26bi, ' 　')))::decimal(5,0) as sdai_26bi,
        to_decimal(iff(rtrim(sdai_27bi, ' 　') = '', 0, rtrim(sdai_27bi, ' 　')))::decimal(5,0) as sdai_27bi,
        to_decimal(iff(rtrim(sdai_28bi, ' 　') = '', 0, rtrim(sdai_28bi, ' 　')))::decimal(5,0) as sdai_28bi,
        to_decimal(iff(rtrim(sdai_29bi, ' 　') = '', 0, rtrim(sdai_29bi, ' 　')))::decimal(5,0) as sdai_29bi,
        to_decimal(iff(rtrim(sdai_30bi, ' 　') = '', 0, rtrim(sdai_30bi, ' 　')))::decimal(5,0) as sdai_30bi,
        to_decimal(iff(rtrim(sdai_31bi, ' 　') = '', 0, rtrim(sdai_31bi, ' 　')))::decimal(5,0) as sdai_31bi,
        to_decimal(iff(rtrim(ktdai, ' 　') = '', 0, rtrim(ktdai, ' 　')))::decimal(5,0) as ktdai,
        to_decimal(iff(rtrim(kdai_01bi, ' 　') = '', 0, rtrim(kdai_01bi, ' 　')))::decimal(5,0) as kdai_01bi,
        to_decimal(iff(rtrim(kdai_02bi, ' 　') = '', 0, rtrim(kdai_02bi, ' 　')))::decimal(5,0) as kdai_02bi,
        to_decimal(iff(rtrim(kdai_03bi, ' 　') = '', 0, rtrim(kdai_03bi, ' 　')))::decimal(5,0) as kdai_03bi,
        to_decimal(iff(rtrim(kdai_04bi, ' 　') = '', 0, rtrim(kdai_04bi, ' 　')))::decimal(5,0) as kdai_04bi,
        to_decimal(iff(rtrim(kdai_05bi, ' 　') = '', 0, rtrim(kdai_05bi, ' 　')))::decimal(5,0) as kdai_05bi,
        to_decimal(iff(rtrim(kdai_06bi, ' 　') = '', 0, rtrim(kdai_06bi, ' 　')))::decimal(5,0) as kdai_06bi,
        to_decimal(iff(rtrim(kdai_07bi, ' 　') = '', 0, rtrim(kdai_07bi, ' 　')))::decimal(5,0) as kdai_07bi,
        to_decimal(iff(rtrim(kdai_08bi, ' 　') = '', 0, rtrim(kdai_08bi, ' 　')))::decimal(5,0) as kdai_08bi,
        to_decimal(iff(rtrim(kdai_09bi, ' 　') = '', 0, rtrim(kdai_09bi, ' 　')))::decimal(5,0) as kdai_09bi,
        to_decimal(iff(rtrim(kdai_10bi, ' 　') = '', 0, rtrim(kdai_10bi, ' 　')))::decimal(5,0) as kdai_10bi,
        to_decimal(iff(rtrim(kdai_11bi, ' 　') = '', 0, rtrim(kdai_11bi, ' 　')))::decimal(5,0) as kdai_11bi,
        to_decimal(iff(rtrim(kdai_12bi, ' 　') = '', 0, rtrim(kdai_12bi, ' 　')))::decimal(5,0) as kdai_12bi,
        to_decimal(iff(rtrim(kdai_13bi, ' 　') = '', 0, rtrim(kdai_13bi, ' 　')))::decimal(5,0) as kdai_13bi,
        to_decimal(iff(rtrim(kdai_14bi, ' 　') = '', 0, rtrim(kdai_14bi, ' 　')))::decimal(5,0) as kdai_14bi,
        to_decimal(iff(rtrim(kdai_15bi, ' 　') = '', 0, rtrim(kdai_15bi, ' 　')))::decimal(5,0) as kdai_15bi,
        to_decimal(iff(rtrim(kdai_16bi, ' 　') = '', 0, rtrim(kdai_16bi, ' 　')))::decimal(5,0) as kdai_16bi,
        to_decimal(iff(rtrim(kdai_17bi, ' 　') = '', 0, rtrim(kdai_17bi, ' 　')))::decimal(5,0) as kdai_17bi,
        to_decimal(iff(rtrim(kdai_18bi, ' 　') = '', 0, rtrim(kdai_18bi, ' 　')))::decimal(5,0) as kdai_18bi,
        to_decimal(iff(rtrim(kdai_19bi, ' 　') = '', 0, rtrim(kdai_19bi, ' 　')))::decimal(5,0) as kdai_19bi,
        to_decimal(iff(rtrim(kdai_20bi, ' 　') = '', 0, rtrim(kdai_20bi, ' 　')))::decimal(5,0) as kdai_20bi,
        to_decimal(iff(rtrim(kdai_21bi, ' 　') = '', 0, rtrim(kdai_21bi, ' 　')))::decimal(5,0) as kdai_21bi,
        to_decimal(iff(rtrim(kdai_22bi, ' 　') = '', 0, rtrim(kdai_22bi, ' 　')))::decimal(5,0) as kdai_22bi,
        to_decimal(iff(rtrim(kdai_23bi, ' 　') = '', 0, rtrim(kdai_23bi, ' 　')))::decimal(5,0) as kdai_23bi,
        to_decimal(iff(rtrim(kdai_24bi, ' 　') = '', 0, rtrim(kdai_24bi, ' 　')))::decimal(5,0) as kdai_24bi,
        to_decimal(iff(rtrim(kdai_25bi, ' 　') = '', 0, rtrim(kdai_25bi, ' 　')))::decimal(5,0) as kdai_25bi,
        to_decimal(iff(rtrim(kdai_26bi, ' 　') = '', 0, rtrim(kdai_26bi, ' 　')))::decimal(5,0) as kdai_26bi,
        to_decimal(iff(rtrim(kdai_27bi, ' 　') = '', 0, rtrim(kdai_27bi, ' 　')))::decimal(5,0) as kdai_27bi,
        to_decimal(iff(rtrim(kdai_28bi, ' 　') = '', 0, rtrim(kdai_28bi, ' 　')))::decimal(5,0) as kdai_28bi,
        to_decimal(iff(rtrim(kdai_29bi, ' 　') = '', 0, rtrim(kdai_29bi, ' 　')))::decimal(5,0) as kdai_29bi,
        to_decimal(iff(rtrim(kdai_30bi, ' 　') = '', 0, rtrim(kdai_30bi, ' 　')))::decimal(5,0) as kdai_30bi,
        to_decimal(iff(rtrim(kdai_31bi, ' 　') = '', 0, rtrim(kdai_31bi, ' 　')))::decimal(5,0) as kdai_31bi,
        to_decimal(iff(rtrim(ntstiflg, ' 　') = '', 0, rtrim(ntstiflg, ' 　')))::decimal(1,0) as ntstiflg,
        mtuser::varchar(18) as mtuser,
        mttime::varchar(26) as mttime,
        ldts::timestamp_ntz(9) as ldts,
        row_number() over (
            partition by shamei, sno, kncode, sym, odt, ln
            order by ldts desc, line_number desc
        ) aggkey
    from {{ref('substr_ktrla01dzz0kalc017')}}
    where ldts = (select max(ldts) from {{ref('substr_ktrla01dzz0kalc017')}})
)
select * exclude(aggkey)
from stg_kinobetsu_noryoku_daisusyukei_syaryosys
where aggkey = 1