with stg_subarugetsudoseikei_syaryosys as (
    select
        maker_kbn::varchar(1) as maker_kbn,
        ktsk::varchar(7) as ktsk,
        sp::varchar(2) as sp,
        op::varchar(2) as op,
        onkn_kbn::varchar(1) as onkn_kbn,
        gsclr::varchar(2) as gsclr,
        nsclr::varchar(2) as nsclr,
        siyo_no::varchar(2) as siyo_no,
        ksh_ktsk::varchar(16) as ksh_ktsk,
        cntl_ktsk::varchar(16) as cntl_ktsk,
        ghnclr_cd::varchar(4) as ghnclr_cd,
        uchibr_cd::varchar(4) as uchibr_cd,
        ssn_sp::varchar(200) as ssn_sp,
        dfsc::varchar(5) as dfsc,
        tsho_ym::varchar(6) as tsho_ym,
        ssn_ym_tougt::varchar(6) as ssn_ym_tougt,
        try_to_number(dsu_tougt)::number(5, 0) as dsu_tougt,
        try_to_number(db_dsu_d01)::number(5, 0) as db_dsu_d01,
        try_to_number(db_dsu_d02)::number(5, 0) as db_dsu_d02,
        try_to_number(db_dsu_d03)::number(5, 0) as db_dsu_d03,
        try_to_number(db_dsu_d04)::number(5, 0) as db_dsu_d04,
        try_to_number(db_dsu_d05)::number(5, 0) as db_dsu_d05,
        try_to_number(db_dsu_d06)::number(5, 0) as db_dsu_d06,
        try_to_number(db_dsu_d07)::number(5, 0) as db_dsu_d07,
        try_to_number(db_dsu_d08)::number(5, 0) as db_dsu_d08,
        try_to_number(db_dsu_d09)::number(5, 0) as db_dsu_d09,
        try_to_number(db_dsu_d10)::number(5, 0) as db_dsu_d10,
        try_to_number(db_dsu_d11)::number(5, 0) as db_dsu_d11,
        try_to_number(db_dsu_d12)::number(5, 0) as db_dsu_d12,
        try_to_number(db_dsu_d13)::number(5, 0) as db_dsu_d13,
        try_to_number(db_dsu_d14)::number(5, 0) as db_dsu_d14,
        try_to_number(db_dsu_d15)::number(5, 0) as db_dsu_d15,
        try_to_number(db_dsu_d16)::number(5, 0) as db_dsu_d16,
        try_to_number(db_dsu_d17)::number(5, 0) as db_dsu_d17,
        try_to_number(db_dsu_d18)::number(5, 0) as db_dsu_d18,
        try_to_number(db_dsu_d19)::number(5, 0) as db_dsu_d19,
        try_to_number(db_dsu_d20)::number(5, 0) as db_dsu_d20,
        try_to_number(db_dsu_d21)::number(5, 0) as db_dsu_d21,
        try_to_number(db_dsu_d22)::number(5, 0) as db_dsu_d22,
        try_to_number(db_dsu_d23)::number(5, 0) as db_dsu_d23,
        try_to_number(db_dsu_d24)::number(5, 0) as db_dsu_d24,
        try_to_number(db_dsu_d25)::number(5, 0) as db_dsu_d25,
        try_to_number(db_dsu_d26)::number(5, 0) as db_dsu_d26,
        try_to_number(db_dsu_d27)::number(5, 0) as db_dsu_d27,
        try_to_number(db_dsu_d28)::number(5, 0) as db_dsu_d28,
        try_to_number(db_dsu_d29)::number(5, 0) as db_dsu_d29,
        try_to_number(db_dsu_d30)::number(5, 0) as db_dsu_d30,
        try_to_number(db_dsu_d31)::number(5, 0) as db_dsu_d31,
        ssn_ym_zg1gt::varchar(6) as ssn_ym_zg1gt,
        try_to_number(dsu_zg1gt)::number(5, 0) as dsu_zg1gt,
        ssn_ym_zg2gt::varchar(6) as ssn_ym_zg2gt,
        try_to_number(dsu_zg2gt)::number(5, 0) as dsu_zg2gt,
        knfugo::varchar(11) as knfugo,
        idline::varchar(2) as idline,
        syamei::varchar(2) as syamei,
        simuke::varchar(1) as simuke,
        dummy::varchar(26) as dummy,
        ldts  -- B層のldts
    from {{ ref('substr_tsjfae2b') }}
    where ldts = (select max(ldts) from {{ ref('substr_tsjfae2b') }})
)
select * from stg_subarugetsudoseikei_syaryosys