{{ config(snowflake_warehouse='DBT_WH') }}

with substr_dvnp0700 as (
    select
        substr(raw_data, 1, 11)::VARCHAR(11) as ORDRKEY,
        substr(raw_data, 12, 11)::VARCHAR(11) as TANSKKEY,
        substr(raw_data, 23, 20)::VARCHAR(20) as SHINBAN,
        substr(raw_data, 43, 20)::VARCHAR(20) as SZHINBAN,
        substr(raw_data, 63, 1)::VARCHAR(1) as KAKNOUKBN,
        substr(raw_data, 64, 1)::VARCHAR(1) as BOYUSNFLG,
        substr(raw_data, 65, 12)::VARCHAR(12) as BOYUSNFTRKTIME,
        substr(raw_data, 77, 1)::VARCHAR(1) as KNKYUDO1,
        substr(raw_data, 78, 12)::VARCHAR(12) as BOSKSTIMEJUN,
        substr(raw_data, 90, 2)::VARCHAR(2) as KNKYUDO2,
        substr(raw_data, 92, 6)::VARCHAR(6) as YUSNRNBN,
        substr(raw_data, 98, 1)::VARCHAR(1) as MARTFLG,
        substr(raw_data, 99, 1)::VARCHAR(1) as PTOPFLG,
        substr(raw_data, 100, 1)::VARCHAR(1) as YUSNPTRN,
        substr(raw_data, 101, 1)::VARCHAR(1) as BOSELFLG,
        substr(raw_data, 102, 6)::VARCHAR(6) as SKSIJSU,
        substr(raw_data, 108, 12)::VARCHAR(12) as SKSIJITIME,
        substr(raw_data, 120, 6)::VARCHAR(6) as TNSKSJSU,
        substr(raw_data, 126, 6)::VARCHAR(6) as HZIKSJSU,
        substr(raw_data, 132, 6)::VARCHAR(6) as NONYUYTISU,
        substr(raw_data, 138, 6)::VARCHAR(6) as BOSU,
        substr(raw_data, 144, 6)::VARCHAR(6) as BORUISUU,
        substr(raw_data, 150, 12)::VARCHAR(12) as BOSKSTIME,
        substr(raw_data, 162, 12)::VARCHAR(12) as BOKTIME,
        substr(raw_data, 174, 1)::VARCHAR(1) as GNBKPFLG,
        substr(raw_data, 175, 2)::VARCHAR(2) as PENDID,
        substr(raw_data, 177, 6)::VARCHAR(6) as PENSU,
        substr(raw_data, 183, 12)::VARCHAR(12) as PENTIME,
        substr(raw_data, 195, 12)::VARCHAR(12) as PEKTIME,
        substr(raw_data, 207, 6)::VARCHAR(6) as CANSU,
        substr(raw_data, 213, 12)::VARCHAR(12) as CANTIME,
        substr(raw_data, 225, 6)::VARCHAR(6) as PLBSURYO,
        substr(raw_data, 231, 12)::VARCHAR(12) as PLBTIME,
        substr(raw_data, 243, 8)::VARCHAR(8) as CASENO,
        substr(raw_data, 251, 2)::VARCHAR(2) as CASECD2,
        substr(raw_data, 253, 6)::VARCHAR(6) as SKZUMSU,
        substr(raw_data, 259, 8)::VARCHAR(8) as SKZUMYMD,
        substr(raw_data, 267, 12)::VARCHAR(12) as SKZTIME,
        substr(raw_data, 279, 1)::VARCHAR(1) as SKZFLG,
        substr(raw_data, 280, 1)::VARCHAR(1) as CANZMFLG,
        substr(raw_data, 281, 1)::VARCHAR(1) as BUNKATUKBN,
        substr(raw_data, 282, 16)::VARCHAR(16) as MTUSERID,
        substr(raw_data, 298, 26)::VARCHAR(26) as MTTIME,
        substr(raw_data, 324, 8)::VARCHAR(8) as JUCHUYMD,
        substr(raw_data, 332, 9)::VARCHAR(9) as DUMMY,
        LDTS
    from {{ source('snowpipe_db_valuechain', 'raw_dvnp0700') }}
)
select * from substr_dvnp0700
        