{{ config(snowflake_warehouse='DBT_WH') }}

with substr_tbdaikl as (
    select
        substr(raw_data, 1, 5)::VARCHAR(5) as KYOUHAN,
        substr(raw_data, 6, 5)::VARCHAR(5) as USERCD,
        substr(raw_data, 11, 2)::VARCHAR(2) as KAISYA,
        substr(raw_data, 13, 14)::VARCHAR(14) as TCHUMON,
        substr(raw_data, 27, 3)::VARCHAR(3) as FRMKB,
        substr(raw_data, 30, 7)::VARCHAR(7) as FRMNO,
        substr(raw_data, 37, 20)::VARCHAR(20) as HANKATA,
        substr(raw_data, 57, 1)::VARCHAR(1) as JYOTAI,
        substr(raw_data, 58, 5)::VARCHAR(5) as HASSIN,
        substr(raw_data, 63, 2)::VARCHAR(2) as UTANTO,
        substr(raw_data, 65, 3)::VARCHAR(3) as SENTER,
        substr(raw_data, 68, 3)::VARCHAR(3) as TENPO,
        substr(raw_data, 71, 1)::VARCHAR(1) as NOHINKB,
        substr(raw_data, 72, 1)::VARCHAR(1) as FNOHINKB,
        substr(raw_data, 73, 8)::VARCHAR(8) as RIMARKU1,
        substr(raw_data, 81, 10)::VARCHAR(10) as RIMARKU2,
        substr(raw_data, 91, 2)::VARCHAR(2) as KYOTEN,
        substr(raw_data, 93, 8)::VARCHAR(8) as JZNJUSIN,
        substr(raw_data, 101, 4)::VARCHAR(4) as JZNJUSIT,
        substr(raw_data, 105, 8)::VARCHAR(8) as FINJUSIN,
        substr(raw_data, 113, 4)::VARCHAR(4) as FINJUSIT,
        substr(raw_data, 117, 8)::VARCHAR(8) as JUSIN,
        substr(raw_data, 125, 4)::VARCHAR(4) as JUSINT,
        substr(raw_data, 129, 8)::VARCHAR(8) as TTYOTE,
        substr(raw_data, 137, 8)::VARCHAR(8) as ZAIYOTE,
        substr(raw_data, 145, 8)::VARCHAR(8) as KINYOTE,
        substr(raw_data, 153, 8)::VARCHAR(8) as ZAIKYOTE,
        substr(raw_data, 161, 8)::VARCHAR(8) as CANYOTE,
        substr(raw_data, 169, 8)::VARCHAR(8) as MAETYAKO,
        substr(raw_data, 177, 8)::VARCHAR(8) as MAEZAIHO,
        substr(raw_data, 185, 8)::VARCHAR(8) as MAEKNKYU,
        substr(raw_data, 193, 8)::VARCHAR(8) as MAEZAIKO,
        substr(raw_data, 201, 8)::VARCHAR(8) as MAECAN,
        substr(raw_data, 209, 8)::VARCHAR(8) as TYAKKO,
        substr(raw_data, 217, 4)::VARCHAR(4) as TOSAIT,
        substr(raw_data, 221, 4)::VARCHAR(4) as TOSAIJ,
        substr(raw_data, 225, 4)::VARCHAR(4) as TORITUKT,
        substr(raw_data, 229, 4)::VARCHAR(4) as TORITUKJ,
        substr(raw_data, 233, 8)::VARCHAR(8) as KANSEI,
        substr(raw_data, 241, 4)::VARCHAR(4) as KANSEIT,
        substr(raw_data, 245, 4)::VARCHAR(4) as KANSEIJ,
        substr(raw_data, 249, 1)::VARCHAR(1) as ZAIHIKIF,
        substr(raw_data, 250, 8)::VARCHAR(8) as ZENHIKDD,
        substr(raw_data, 258, 8)::VARCHAR(8) as ZAIHATYU,
        substr(raw_data, 266, 8)::VARCHAR(8) as KINHATYU,
        substr(raw_data, 274, 8)::VARCHAR(8) as CANCEL,
        substr(raw_data, 282, 2)::VARCHAR(2) as SYUKTEN,
        LDTS
    from {{ source('snowpipe_db_valuechain', 'raw_tbdaikl') }}
)
select * from substr_tbdaikl
