with substr_ktrla01xzz0kv200v9 as (
    select
        substr(raw_data, 5, 1)::varchar(1) as mtkbn,
        substr(raw_data, 6, 6)::varchar(6) as catalg,
        substr(raw_data, 12, 4)::varchar(4) as syasyu,
        substr(raw_data, 16, 20)::varchar(20) as kosho,
        substr(raw_data, 36, 20)::varchar(20) as ctl,
        substr(raw_data, 63, 6)::varchar(6) as jissijkara,
        substr(raw_data, 69, 6)::varchar(6) as jissijmade,
        substr(raw_data, 75, 3)::varchar(3) as syakano,
        substr(raw_data, 78, 3)::varchar(3) as ctlgkatno,
        substr(raw_data, 81, 10)::varchar(10) as katatokuengine1,
        substr(raw_data, 91, 10)::varchar(10) as katatokuengine2,
        substr(raw_data, 101, 5)::varchar(5) as katatokutoku1,
        substr(raw_data, 106, 5)::varchar(5) as katatokutoku2,
        substr(raw_data, 111, 5)::varchar(5) as katatokutoku3,
        substr(raw_data, 116, 5)::varchar(5) as katatokutoku4,
        substr(raw_data, 121, 5)::varchar(5) as katatokutoku5,
        substr(raw_data, 126, 5)::varchar(5) as katatokutoku6,
        substr(raw_data, 131, 5)::varchar(5) as katatokutoku7,
        substr(raw_data, 136, 5)::varchar(5) as katatokutoku8,
        substr(raw_data, 141, 5)::varchar(5) as katatokutoku9,
        substr(raw_data, 146, 5)::varchar(5) as katatokutoku10,
        substr(raw_data, 151, 5)::varchar(5) as katatokutoku11,
        substr(raw_data, 156, 5)::varchar(5) as katatokutoku12,
        substr(raw_data, 161, 5)::varchar(5) as katatokutoku13,
        substr(raw_data, 166, 5)::varchar(5) as katatokutoku14,
        substr(raw_data, 171, 5)::varchar(5) as katatokutoku15,
        substr(raw_data, 176, 5)::varchar(5) as katatokutoku16,
        substr(raw_data, 181, 5)::varchar(5) as katatokutoku17,
        substr(raw_data, 186, 5)::varchar(5) as katatokutoku18,
        substr(raw_data, 191, 5)::varchar(5) as katatokutoku19,
        substr(raw_data, 196, 5)::varchar(5) as katatokutoku20,
        substr(raw_data, 56, 7)::varchar(7) as stdkata,
        substr(raw_data, 201, 11)::varchar(11) as ikkatu,
        ldts,
        line_number
    from {{ source('snowpipe_db_valuechain', 'raw_ktrla01xzz0kv200v9') }}
)
select * from substr_ktrla01xzz0kv200v9