{{ config(snowflake_warehouse='DBT_WH') }}

with substr_dvnp4520 as (
    select
        substr(raw_data, 2, 4)::VARCHAR(4) as DATAKBN4,
        substr(raw_data, 6, 6)::VARCHAR(6) as JUSINNO,
        substr(raw_data, 12, 2)::VARCHAR(2) as RENBAN2,
        substr(raw_data, 14, 7)::VARCHAR(7) as DLRCD,
        substr(raw_data, 21, 2)::VARCHAR(2) as ORDESYBT,
        substr(raw_data, 23, 1)::VARCHAR(1) as YUSOKBN,
        substr(raw_data, 24, 5)::VARCHAR(5) as ORDENO,
        substr(raw_data, 29, 20)::VARCHAR(20) as JHINBAN,
        substr(raw_data, 49, 5)::VARCHAR(5) as JUCHU5,
        substr(raw_data, 54, 1)::VARCHAR(1) as BOCD,
        substr(raw_data, 55, 10)::VARCHAR(10) as RIMAK1,
        substr(raw_data, 65, 1)::VARCHAR(1) as RIMAK2,
        substr(raw_data, 66, 1)::VARCHAR(1) as BNRKYSCD,
        substr(raw_data, 67, 8)::VARCHAR(8) as TYSSYKSITEIYMD,
        substr(raw_data, 75, 1)::VARCHAR(1) as BEKONCD,
        substr(raw_data, 76, 1)::VARCHAR(1) as KYOSEICD,
        substr(raw_data, 77, 8)::VARCHAR(8) as TKBETTAN,
        substr(raw_data, 85, 4)::VARCHAR(4) as WARIRITU,
        substr(raw_data, 89, 3)::VARCHAR(3) as SIMKMEIJP,
        substr(raw_data, 92, 20)::VARCHAR(20) as SIMKMEIK,
        substr(raw_data, 112, 4)::VARCHAR(4) as SIIRECD,
        substr(raw_data, 116, 20)::VARCHAR(20) as SHINBAN,
        substr(raw_data, 136, 2)::VARCHAR(2) as DAITITYP,
        substr(raw_data, 138, 5)::VARCHAR(5) as SYUKASU,
        substr(raw_data, 143, 1)::VARCHAR(1) as TKSKBN,
        substr(raw_data, 144, 8)::VARCHAR(8) as TYOSEIKYMD,
        substr(raw_data, 152, 8)::VARCHAR(8) as TYOSEIYMD,
        substr(raw_data, 160, 8)::VARCHAR(8) as HNOKIKTYMD,
        substr(raw_data, 168, 8)::VARCHAR(8) as HNOKKRYMD,
        substr(raw_data, 176, 8)::VARCHAR(8) as HENKAIYMD,
        substr(raw_data, 184, 8)::VARCHAR(8) as HENKARYMD,
        substr(raw_data, 192, 5)::VARCHAR(5) as BOSU5,
        substr(raw_data, 197, 8)::VARCHAR(8) as BORENYMD,
        substr(raw_data, 205, 5)::VARCHAR(5) as CANCELSU,
        substr(raw_data, 210, 8)::VARCHAR(8) as CANRRYMD,
        substr(raw_data, 218, 8)::VARCHAR(8) as JUCHUYMD,
        substr(raw_data, 226, 1)::VARCHAR(1) as KAITOUKBN,
        substr(raw_data, 227, 8)::VARCHAR(8) as SYORIYMD,
        substr(raw_data, 235, 5)::VARCHAR(5) as MISYUSU,
        substr(raw_data, 240, 1)::VARCHAR(1) as TKSSKTHIKANFLG,
        substr(raw_data, 241, 8)::VARCHAR(8) as TOKUSOKUYMD,
        substr(raw_data, 249, 6)::VARCHAR(6) as ISSUENO,
        substr(raw_data, 255, 2)::VARCHAR(2) as SYOHINCD,
        substr(raw_data, 257, 4)::VARCHAR(4) as HINMKCD,
        substr(raw_data, 261, 1)::VARCHAR(1) as GKKBN,
        substr(raw_data, 262, 6)::VARCHAR(6) as ENDKI,
        LDTS
    from {{ source('snowpipe_db_valuechain', 'raw_dvnp4520') }}
)
select * from substr_dvnp4520