{{ config(snowflake_warehouse='DBT_WH') }}

with substr_tbchznl as (
    select
        substr(raw_data, 1, 5)::varchar(5) as kyouhan,
        substr(raw_data, 6, 20)::varchar(20) as hinban,
        substr(raw_data, 26, 1)::varchar(1) as mkbn,
        substr(raw_data, 27, 2)::varchar(2) as nyukkten,
        substr(raw_data, 29, 5)::varchar(5) as chumon,
        substr(raw_data, 34, 1)::varchar(1) as hinkbn,
        substr(raw_data, 35, 1)::varchar(1) as genkacd,
        substr(raw_data, 36, 1)::varchar(1) as "PRICEKN-S",
        substr(raw_data, 37, 7)::varchar(7) as pricekn,
        substr(raw_data, 44, 1)::varchar(1) as chokso,
        substr(raw_data, 45, 5)::varchar(5) as makercd,
        substr(raw_data, 50, 1)::varchar(1) as ktenkbn,
        substr(raw_data, 51, 2)::varchar(2) as odrsbetu,
        substr(raw_data, 53, 1)::varchar(1) as yusocd,
        substr(raw_data, 54, 1)::varchar(1) as bocd,
        substr(raw_data, 55, 1)::varchar(1) as urikbn,
        substr(raw_data, 56, 8)::varchar(8) as hchuymd,
        substr(raw_data, 64, 4)::varchar(4) as hchutime,
        substr(raw_data, 68, 8)::varchar(8) as tosyoyd1,
        substr(raw_data, 76, 4)::varchar(4) as tosyotm,
        substr(raw_data, 80, 8)::varchar(8) as kaitoud1,
        substr(raw_data, 88, 8)::varchar(8) as syukayd1,
        substr(raw_data, 96, 4)::varchar(4) as syukatm1,
        substr(raw_data, 100, 8)::varchar(8) as nyukayd1,
        substr(raw_data, 108, 4)::varchar(4) as nyukatm1,
        substr(raw_data, 112, 1)::varchar(1) as nyukayk1,
        substr(raw_data, 113, 8)::varchar(8) as kaitoud2,
        substr(raw_data, 121, 8)::varchar(8) as syukayd2,
        substr(raw_data, 129, 4)::varchar(4) as syukatm2,
        substr(raw_data, 133, 8)::varchar(8) as nyukayd2,
        substr(raw_data, 141, 4)::varchar(4) as nyukatm2,
        substr(raw_data, 145, 1)::varchar(1) as nyukayk2,
        substr(raw_data, 146, 8)::varchar(8) as kaitoud3,
        substr(raw_data, 154, 8)::varchar(8) as syukayd3,
        substr(raw_data, 162, 4)::varchar(4) as syukatm3,
        substr(raw_data, 166, 8)::varchar(8) as nyukayd3,
        substr(raw_data, 174, 4)::varchar(4) as nyukatm3,
        substr(raw_data, 178, 1)::varchar(1) as nyukayk3,
        substr(raw_data, 179, 8)::varchar(8) as kaitoud4,
        substr(raw_data, 187, 8)::varchar(8) as syukayd4,
        substr(raw_data, 195, 4)::varchar(4) as syukatm4,
        substr(raw_data, 199, 8)::varchar(8) as nyukayd4,
        substr(raw_data, 207, 4)::varchar(4) as nyukatm4,
        substr(raw_data, 211, 1)::varchar(1) as nyukayk4,
        substr(raw_data, 212, 1)::varchar(1) as "HCHUSU-S",
        substr(raw_data, 213, 5)::varchar(5) as hchusu,
        substr(raw_data, 218, 1)::varchar(1) as "MITESU-S",
        substr(raw_data, 219, 5)::varchar(5) as mitesu,
        substr(raw_data, 224, 1)::varchar(1) as "NYUKKEI-S",
        substr(raw_data, 225, 5)::varchar(5) as nyukkei,
        substr(raw_data, 230, 1)::varchar(1) as nyukkflg,
        substr(raw_data, 231, 2)::varchar(2) as chuzancnt,
        substr(raw_data, 233, 8)::varchar(8) as nnyukymd,
        substr(raw_data, 241, 4)::varchar(4) as nnyuktm,
        substr(raw_data, 245, 1)::varchar(1) as mkszumcnt,
        substr(raw_data, 246, 8)::varchar(8) as mntymd,
        substr(raw_data, 254, 1)::varchar(1) as ptopflg,
        substr(raw_data, 255, 1)::varchar(1) as tensokbn,
        substr(raw_data, 256, 1)::varchar(1) as tehaiok,
        substr(raw_data, 257, 8)::varchar(8) as ltnyukayd,
        substr(raw_data, 265, 8)::varchar(8) as ltsyukayd,
        ldts
    from {{ source('snowpipe_db_valuechain', 'raw_tbchznl') }}
)
select * from substr_tbchznl
