{{ config(snowflake_warehouse='DBT_WH') }}

with substr_dvsf509a as (
    select
        substr(raw_data, 1, 20)::VARCHAR(20) as TYOTATHB,
        substr(raw_data, 21, 1)::VARCHAR(1) as KAKNOUKBN,
        substr(raw_data, 22, 4)::VARCHAR(4) as SRSIRSKCD,
        substr(raw_data, 26, 8)::VARCHAR(8) as HINBANKAISIYMD,
        substr(raw_data, 34, 8)::VARCHAR(8) as HINBANSRYOYMD,
        substr(raw_data, 42, 8)::VARCHAR(8) as TEHAIKAISIYMD,
        substr(raw_data, 50, 8)::VARCHAR(8) as TEHAISRYOYMD,
        substr(raw_data, 58, 4)::VARCHAR(4) as MOTIKOMISK,
        substr(raw_data, 62, 1)::VARCHAR(1) as KOTEIKBN,
        substr(raw_data, 63, 4)::VARCHAR(4) as BRSIRSKCD,
        substr(raw_data, 67, 5)::VARCHAR(5) as THIBUSYOCD,
        substr(raw_data, 72, 2)::VARCHAR(2) as THITATOCD,
        substr(raw_data, 74, 1)::VARCHAR(1) as TEHAIKBN,
        substr(raw_data, 75, 1)::VARCHAR(1) as ZAIHIKBN,
        substr(raw_data, 76, 1)::VARCHAR(1) as KANBNKBN,
        substr(raw_data, 77, 4)::VARCHAR(4) as CYCLE4,
        substr(raw_data, 81, 1)::VARCHAR(1) as HATYUKAISU,
        substr(raw_data, 82, 1)::VARCHAR(1) as BINSITEITAIO1,
        substr(raw_data, 83, 1)::VARCHAR(1) as BINSITEITAIO2,
        substr(raw_data, 84, 1)::VARCHAR(1) as BINSITEITAIO3,
        substr(raw_data, 85, 3)::VARCHAR(3) as KOTEIMAISUMAISU,
        substr(raw_data, 88, 6)::VARCHAR(6) as KOTEIMAISHNKYM,
        substr(raw_data, 94, 3)::VARCHAR(3) as KJNZIKNISU3,
        substr(raw_data, 97, 7)::VARCHAR(7) as KJNZIKSU,
        substr(raw_data, 104, 3)::VARCHAR(3) as ANZENZAIKONISU,
        substr(raw_data, 107, 7)::VARCHAR(7) as ANZNZKSU,
        substr(raw_data, 114, 3)::VARCHAR(3) as KOTYRYDHJOGNRIT,
        substr(raw_data, 117, 3)::VARCHAR(3) as KOTYRYDHKAGNRIT,
        substr(raw_data, 120, 3)::VARCHAR(3) as KYOTEIJOGNMAISU,
        substr(raw_data, 123, 1)::VARCHAR(1) as MIKKABARASIUM,
        substr(raw_data, 124, 6)::VARCHAR(6) as SEBANGOU,
        substr(raw_data, 130, 1)::VARCHAR(1) as KNBNZDAWSTYSKBN,
        substr(raw_data, 131, 2)::VARCHAR(2) as NONYULT,
        substr(raw_data, 133, 2)::VARCHAR(2) as HAKKOCYCLE,
        substr(raw_data, 135, 7)::VARCHAR(7) as ZAIKOITTEISU,
        substr(raw_data, 142, 1)::VARCHAR(1) as NONUKYOKBN,
        substr(raw_data, 143, 2)::VARCHAR(2) as NBSCD,
        substr(raw_data, 145, 2)::VARCHAR(2) as UKEIRECD,
        substr(raw_data, 147, 2)::VARCHAR(2) as OROSIBACD,
        substr(raw_data, 149, 1)::VARCHAR(1) as HASUSYORIUM,
        substr(raw_data, 150, 5)::VARCHAR(5) as NONYUKGCD,
        substr(raw_data, 155, 5)::VARCHAR(5) as NONYUTNI,
        substr(raw_data, 160, 1)::VARCHAR(1) as KUKURITYPE,
        substr(raw_data, 161, 5)::VARCHAR(5) as KUKURITNI,
        substr(raw_data, 166, 1)::VARCHAR(1) as KENSAKBN,
        substr(raw_data, 167, 1)::VARCHAR(1) as SRSIRSKKOJOCD,
        substr(raw_data, 168, 1)::VARCHAR(1) as BRSIRSKKOJOCD,
        substr(raw_data, 169, 3)::VARCHAR(3) as SIRSKSYUKZYOCD,
        substr(raw_data, 172, 8)::VARCHAR(8) as TEKIYOKAISIYMD,
        substr(raw_data, 180, 8)::VARCHAR(8) as TEKIYOSYURYOYMD,
        substr(raw_data, 188, 16)::VARCHAR(16) as MTUSERID,
        substr(raw_data, 204, 26)::VARCHAR(26) as MTTIME,
        LDTS
    from {{ source('snowpipe_db_valuechain', 'raw_dvsf509a') }}
)
select * from substr_dvsf509a