{{ config(snowflake_warehouse='DBT_WH') }}

with substr_dvnp4330 as (
    select
      substr(raw_data, 1, 1)::VARCHAR(1)  as MNTKBN,
      substr(raw_data, 2, 4)::VARCHAR(4)  as DATAKBN4, 
      substr(raw_data, 6, 4)::VARCHAR(4)  as SIIRECD,
      substr(raw_data, 10,1)::VARCHAR(1)  as EGSCD1,
      substr(raw_data, 11, 6)::VARCHAR(6) as JUSINNO,
      substr(raw_data, 17, 2)::VARCHAR(2) as RENBAN2,
      substr(raw_data, 19, 7)::VARCHAR(7) as DLRCD,
      substr(raw_data, 26, 2)::VARCHAR(2) as ORDESYBT,
      substr(raw_data, 28, 1)::VARCHAR(1) as YUSOKBN,
      substr(raw_data, 29, 8)::VARCHAR(8) as JUCHUYMD,
      substr(raw_data, 37, 5)::VARCHAR(5) as ORDENO,
      substr(raw_data, 42, 20)::VARCHAR(20) as SHINBAN,
      substr(raw_data, 62, 6)::VARCHAR(6) as SYUKKASU,
      substr(raw_data, 68, 8)::VARCHAR(8) as SYUKKAYMD,
      substr(raw_data, 76, 1)::VARCHAR(1)  as KAITOUKBN,
      substr(raw_data, 77, 2)::VARCHAR(2) as DAITITYP,
      substr(raw_data, 79, 6)::VARCHAR(6) as SIRISSUENO,
      substr(raw_data, 85, 6)::VARCHAR(6) as NOUBAN,
      substr(raw_data, 91, 5)::VARCHAR(5) as SYKNO,
      substr(raw_data, 96, 1)::VARCHAR(1)  as GKKBNG,
      substr(raw_data, 97, 8)::VARCHAR(8) as GKUBNKKYMD,
      substr(raw_data, 105, 1)::VARCHAR(1) as GKKBNN,
      substr(raw_data, 106, 2)::VARCHAR(2) as JUCHUKAITOCD,
      substr(raw_data, 108, 1)::VARCHAR(1)  as SIRREJECTCD,
      substr(raw_data, 109, 20)::VARCHAR(20) as SIMKMEIK,
      substr(raw_data, 129, 1)::VARCHAR(1)  as JSKDATAKBN,
      substr(raw_data, 130, 1)::VARCHAR(1)  as SUTEIKBN,
      substr(raw_data, 131, 20)::VARCHAR(20) as JHINBAN,
      substr(raw_data, 151, 5)::VARCHAR(5) as JUCHU5,
      substr(raw_data, 156, 1)::VARCHAR(1)  as BOCD,
      substr(raw_data, 157, 10)::VARCHAR(10) as RIMAK1,
      substr(raw_data, 167, 1)::VARCHAR(1)  as BNRKYSCD,
      substr(raw_data, 168, 1)::VARCHAR(1)  as RIMAK2,
      substr(raw_data, 169, 1)::VARCHAR(1)  as TKYTNKBN,
      substr(raw_data, 170, 8)::VARCHAR(8) as TANKA8,
      substr(raw_data, 178, 10)::VARCHAR(10) as SYKZMKINF,
      substr(raw_data, 188, 8)::VARCHAR(8) as HAISOUSYOKAKEF,
      substr(raw_data, 196, 8)::VARCHAR(8) as KKHTESURYOF,
      substr(raw_data, 204, 2)::VARCHAR(2) as SYOHINCD,
      substr(raw_data, 206, 4)::VARCHAR(4) as HINMKCD,
      substr(raw_data, 210, 1)::VARCHAR(1)  as SYKKAITOCD,
      substr(raw_data, 211, 1)::VARCHAR(1)  as HANKAMITEIHSICD,
      substr(raw_data, 212, 1)::VARCHAR(1)  as TKSKBN,
      substr(raw_data, 213, 8)::VARCHAR(8) as HANKAKETTEIYMD,
      substr(raw_data, 221,8)::VARCHAR(8) as JSKSYSEIYMD,
      substr(raw_data, 229, 8)::VARCHAR(8) as TKBETTAN,
      substr(raw_data, 237, 4)::VARCHAR(4) as WARIRITU,
      substr(raw_data, 241, 6)::VARCHAR(6) as IRAIDTKANRINO,
      substr(raw_data, 247, 24)::VARCHAR(24) as FILLER,
      LDTS
    from {{ source('snowpipe_db_valuechain','raw_dvnp4330') }}
)
select * from substr_dvnp4330

