- type: io.kestra.plugin.dbt.cli.DbtCLI
  forced: false
  values:
    profiles: |
      enterprise_data_products:
        target: dev
        outputs:
          dev:
            account: "{{ namespace.DBT.SNOWFLAKE_ACCOUNT }}"
            database: "{{ namespace.DBT.SNOWFLAKE_DATABASE }}"
            private_key: "{{ secret('SNOWFLAKE_PRIVATE_KEY_DBT') }}"
            private_key_passphrase: "{{ secret('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE_DBT') }}"
            role: "{{ namespace.DBT.SNOWFLAKE_ROLE }}"
            schema: "{{ namespace.DBT.SNOWFLAKE_SCHEMA }}"
            threads: 16
            type: snowflake
            user: "{{ namespace.DBT.SNOWFLAKE_USER }}"
            warehouse: "dbt_default_wh"
      elementary:
        target: dev
        outputs:
          dev:
            account: "{{ namespace.DBT.SNOWFLAKE_ACCOUNT }}"
            database: common_tbl_db
            private_key: "{{ secret('SNOWFLAKE_PRIVATE_KEY_DBT') }}"
            private_key_passphrase: "{{ secret('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE_DBT') }}"
            role: "{{ namespace.DBT.SNOWFLAKE_ROLE }}"
            schema: elementary
            threads: 16
            type: snowflake
            user: "{{ namespace.DBT.SNOWFLAKE_USER }}"
            warehouse: dbt_default_wh
    projectDir: "{{ namespace.DBT.PROJ_DIR }}"
    taskRunner:
      type: io.kestra.plugin.ee.kubernetes.runner.Kubernetes
      namespace: "{{ namespace.KUBERNETES.NAMESPACE }}"
      config:
        username: "{{ namespace.KUBERNETES.USER_NAME }}"
        masterUrl: "{{ namespace.KUBERNETES.MASTER_URL }}"
        caCertData: "{{ secret('KUBERNETES_CA_CERT_DATA') }}"
        oauthToken: "{{ secret('KUBERNETES_OAUTH_TOKEN') }}"
      pullPolicy: IF_NOT_PRESENT
    beforeCommands:
      - apt-get install git
      - git clone -b {{ namespace.GIT.BRANCH ?? inputs.branch }} http://{{ namespace.GIT.USER }}:{{ secret('GIT_PASS') }}@{{ namespace.GIT.URL_PATH }}
      - cp --force profiles.yml {{ namespace.NAME }}/{{ namespace.DBT.PROJ_DIR }}/profiles.yml
      - cd {{ namespace.NAME }}/{{ namespace.DBT.PROJ_DIR }}
      - dbt deps
    containerImage: "{{ namespace.DOCKER.IMAGE_VERSION.DBT }}"
- type: io.kestra.plugin.git
  forced: false
  values:
    url: "{{ namespace.GIT.URL }}"
- type: io.kestra.plugin.git.Clone
  forced: false
  values:
    branch: "{{ namespace.GIT.BRANCH }}"
    password: "{{ secret('GIT_PASS') }}"
    username: "{{ namespace.GIT.USER }}"
- type: io.kestra.plugin.git.PushFlows
  forced: false
  values:
    flows: "*"
    password: "{{ inputs.pass }}"
    username: "{{ inputs.user }}"
    authorEmail: "{{ inputs.email }}"
    gitDirectory: kestra/dbt_products/{{ inputs.proj_namespace }}/flows
    commitMessage: "{{ inputs.message }}"
- type: io.kestra.plugin.git.PushNamespaceFiles
  forced: false
  values:
    files: "**"
    password: "{{ inputs.pass }}"
    username: "{{ inputs.user }}"
    authorEmail: "{{ inputs.email }}"
    gitDirectory: kestra/dbt_products/{{ inputs.proj_namespace }}/files
    commitMessage: "{{ inputs.message }}"
- type: io.kestra.plugin.git.SyncFlows
  forced: false
  values:
    delete: true
    password: "{{ inputs.pass }}"
    username: "{{ inputs.user }}"
    gitDirectory: kestra/dbt_products/{{ inputs.proj_namespace }}/flows
- type: io.kestra.plugin.git.SyncNamespaceFiles
  forced: false
  values:
    delete: true
    password: "{{ inputs.pass }}"
    username: "{{ inputs.user }}"
    allowFailure: true
    allowWarning: true
    gitDirectory: kestra/dbt_products/{{ inputs.proj_namespace }}/files
- type: io.kestra.plugin.aws.sns.Publish
  forced: false
  values:
    from:
      - data: |
          The Kestra workflow execution {{ inputs.state }}. [{{ namespace.ENV }}]

          -----------------------------------------------------------------------------------------------------------------------------
          - Namespace: {{ trigger.namespace }}
          - Flow ID: {{ trigger.flowId }}
          - Execution ID: {{ trigger.executionId }}
          - Error Info: {{ inputs.error_log }}
          -----------------------------------------------------------------------------------------------------------------------------

          ※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※
          ※  下の「unsubscribe」のリンクをクリックしないでください（1番目のリンク）       ※
          ※  リンクをクリックするとKestraのエラー通知が一切飛ばなくなってしまいます       ※
          ※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※
          -
          -
          -
          -
          -
        subject: "[{{ namespace.ENV }}] Kestra Workflow {{ inputs.state }}: {{ trigger.flowId }}"
    region: "{{ namespace.ALERTS.REGION }}"
    topicArn: "{{ namespace.ALERTS.TOPIC }}"
- type: io.kestra.plugin.scripts.python.Commands
  forced: false
  values:
    taskRunner:
      type: io.kestra.plugin.ee.kubernetes.runner.Kubernetes
      namespace: "{{ namespace.KUBERNETES.NAMESPACE }}"
      config:
        username: "{{ namespace.KUBERNETES.USER_NAME }}"
        masterUrl: "{{ namespace.KUBERNETES.MASTER_URL }}"
        caCertData: "{{ secret('KUBERNETES_CA_CERT_DATA') }}"
        oauthToken: "{{ secret('KUBERNETES_OAUTH_TOKEN') }}"
      pullPolicy: IF_NOT_PRESENT
    beforeCommands:
      - pip install "{{ namespace.PYTHON.SNOWFLAKE_CONNECTOR_VERSION }}"
    containerImage: "{{ namespace.DOCKER.IMAGE_VERSION.PYTHON }}"
