id: job_build_stg_mikado_judgev
namespace: kestra_dbt_project.proj-job-judgev

labels:
  error: default_failed
  dbt: build

# 手動実行時に指定できるdbtオプション
inputs:
  - id: dbt_options
    type: SELECT
    displayName: Choose dbt options
    values:
      - --full-refresh
    required: false
    allowCustomValue: true

tasks:
  - id: clone_dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    commands:
      - dbt build
        --select +stg_saikendenpyo_joho_judgev +stg_saikenmaeuke_meisai_judgev +stg_saikentorihikisaki_meisai_judgev +stg_saimudenpyo_meisai_judgev +stg_hinmoku_meisai_judgev +stg_torihikisaki_masta_judgev +stg_furikomikoza_masta_judgev +stg_torihikitanto_kaigai_masta_judgev +stg_seikyusofu_kokunai_masta_judgev +stg_shinsei_header_judgev +stg_torihiki_tekiyo_judgev +stg_torihiki_meisai_judgev +stg_kosaihijizen_meisai_judgev +stg_busyo_meisai_judgev +stg_zeimu_himoduke_judgev +stg_zeimu_meisai_judgev +stg_jugyoin_masta_judgev +stg_jcard_meisai_judgev +stg_bumonctl_masta_judgev +stg_yosankbn_masta_judgev +stg_yosankmk_masta_judgev +stg_yosanhmk_masta_judgev
        --vars '{"DBT_JOB_NAME":"_stg_mikado_judgev"}'
        {{ inputs.dbt_options ?? "" }}

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "00 01 * * 6"
    timezone: Asia/Tokyo

# エラーログを出力
errors:
  - id: error_log
    type: io.kestra.plugin.core.debug.Return
    format: "{{ errorLogs()[0]['message'] }}"

outputs: 
  - id: output_error_log
    type: STRING
    value: "{{ outputs.error_log.value ?? 'No message found.' }}"
  - id: output_state
    type: STRING
    value: "{{ tasks.dbt.state ?? 'No state' }}"

# ログ出力
finally:
  - id: finally_log 
    type: io.kestra.plugin.core.log.Log
    message: 
      - "Git branch -> {{ namespace.GIT.BRANCH }}"
      - "dbt options -> {{ inputs.dbt_options ?? '' }}"
      
disabled: false