/*
tsjfa38tはマルチレイアウトであり、このsubstrは仕様マスタ（型式）のレイアウトで分割している
仕様マスタ（チェック）と仕様マスタ（ジェネレート）のレコードは正しく分割されていない
rtrim(segmei,' 　') = 'EA31022'のデータのみstg_siyoumst_katashikiに取り込まれる
*/
with substr_tsjfa38t1 as (
    select
        substr(raw_data, 1, 1)::varchar(1) as mtkbn, --C,U,Dのメンテ区分
        substr(raw_data, 3, 8)::varchar(8) as segmei,
        substr(raw_data, 11, 20)::varchar(20) as renkey_hkata,
        substr(raw_data, 31, 1)::varchar(1) as renkey_sedai,
        substr(raw_data, 132, 20)::varchar(20) as hkata,
        substr(raw_data, 152, 1)::varchar(1) as sedai,
        substr(raw_data, 153, 4)::varchar(4) as jkkyy,
        substr(raw_data, 157, 2)::varchar(2) as jkkmm,
        substr(raw_data, 159, 2)::varchar(2) as jkkdd,
        substr(raw_data, 161, 4)::varchar(4) as jkmyy,
        substr(raw_data, 165, 2)::varchar(2) as jkmmm,
        substr(raw_data, 167, 2)::varchar(2) as jkmdd,
        substr(raw_data, 169, 4)::varchar(4) as dkkyy,
        substr(raw_data, 173, 2)::varchar(2) as dkkmm,
        substr(raw_data, 175, 2)::varchar(2) as dkkdd,
        substr(raw_data, 177, 4)::varchar(4) as dkmyy,
        substr(raw_data, 181, 2)::varchar(2) as dkmmm,
        substr(raw_data, 183, 2)::varchar(2) as dkmdd,
        substr(raw_data, 185, 2)::varchar(2) as syamei,
        substr(raw_data, 187, 2)::varchar(2) as sno,
        substr(raw_data, 189, 1)::varchar(1) as odt,
        substr(raw_data, 190, 5)::varchar(5) as katacd,
        substr(raw_data, 195, 20)::varchar(20) as bkata,
        substr(raw_data, 215, 16)::varchar(16) as ckata,
        substr(raw_data, 231, 1)::varchar(1) as fix,
        substr(raw_data, 232, 1)::varchar(1) as seikbn1,
        substr(raw_data, 233, 1)::varchar(1) as seijbn1,
        substr(raw_data, 234, 5)::varchar(5) as seiyk1,
        substr(raw_data, 239, 1)::varchar(1) as seibkbn1,
        substr(raw_data, 240, 1)::varchar(1) as seikbn2,
        substr(raw_data, 241, 1)::varchar(1) as seijbn2,
        substr(raw_data, 242, 5)::varchar(5) as seiyk2,
        substr(raw_data, 247, 1)::varchar(1) as seibkbn2,
        substr(raw_data, 248, 1)::varchar(1) as seikbn3,
        substr(raw_data, 249, 1)::varchar(1) as seijbn3,
        substr(raw_data, 250, 5)::varchar(5) as seiyk3,
        substr(raw_data, 255, 1)::varchar(1) as seibkbn3,
        substr(raw_data, 256, 1)::varchar(1) as seikbn4,
        substr(raw_data, 257, 1)::varchar(1) as seijbn4,
        substr(raw_data, 258, 5)::varchar(5) as seiyk4,
        substr(raw_data, 263, 1)::varchar(1) as seibkbn4,
        substr(raw_data, 264, 1)::varchar(1) as seikbn5,
        substr(raw_data, 265, 1)::varchar(1) as seijbn5,
        substr(raw_data, 266, 5)::varchar(5) as seiyk5,
        substr(raw_data, 271, 1)::varchar(1) as seibkbn5,
        substr(raw_data, 272, 1)::varchar(1) as seikbn6,
        substr(raw_data, 273, 1)::varchar(1) as seijbn6,
        substr(raw_data, 274, 5)::varchar(5) as seiyk6,
        substr(raw_data, 279, 1)::varchar(1) as seibkbn6,
        substr(raw_data, 280, 1)::varchar(1) as seikbn7,
        substr(raw_data, 281, 1)::varchar(1) as seijbn7,
        substr(raw_data, 282, 5)::varchar(5) as seiyk7,
        substr(raw_data, 287, 1)::varchar(1) as seibkbn7,
        substr(raw_data, 288, 1)::varchar(1) as seikbn8,
        substr(raw_data, 289, 1)::varchar(1) as seijbn8,
        substr(raw_data, 290, 5)::varchar(5) as seiyk8,
        substr(raw_data, 295, 1)::varchar(1) as seibkbn8,
        substr(raw_data, 296, 1)::varchar(1) as seikbn9,
        substr(raw_data, 297, 1)::varchar(1) as seijbn9,
        substr(raw_data, 298, 5)::varchar(5) as seiyk9,
        substr(raw_data, 303, 1)::varchar(1) as seibkbn9,
        substr(raw_data, 304, 1)::varchar(1) as seikbn10,
        substr(raw_data, 305, 1)::varchar(1) as seijbn10,
        substr(raw_data, 306, 5)::varchar(5) as seiyk10,
        substr(raw_data, 311, 1)::varchar(1) as seibkbn10,
        substr(raw_data, 312, 1)::varchar(1) as tecs,
        substr(raw_data, 313, 5)::varchar(5) as kmaker,
        substr(raw_data, 318, 1)::varchar(1) as hassou,
        substr(raw_data, 319, 1)::varchar(1) as sofu,
        substr(raw_data, 320, 1)::varchar(1) as lflg,
        ldts,
        line_number
    from {{source('snowpipe_db_supplydemand', 'raw_tsjfa38t')}}
)
select * from substr_tsjfa38t1