with substr_tsjfa38t2 as (
    select
        substr(raw_data, 1, 1)::varchar(1) as mtkbn, --C,U,Dのメンテ区分
        substr(raw_data, 2, 1)::varchar(4) as dum1,
        substr(raw_data, 3, 8)::varchar(8) as segmei,
        substr(raw_data, 11, 20)::varchar(20) as renkey_hkata,
        substr(raw_data, 31, 1)::varchar(1) as renkey_sedai,
        substr(raw_data, 32, 1)::varchar(1) as renkey_psign,
        substr(raw_data, 33, 1)::varchar(1) as renkey_keykbn,
        substr(raw_data, 34, 5)::varchar(5) as renkey_chk,
        substr(raw_data, 39, 2)::varchar(2) as renkey_renban,
        substr(raw_data, 41, 91)::varchar(91) as dum2,
        substr(raw_data, 132, 1)::varchar(1) as psign,
        substr(raw_data, 133, 1)::varchar(1) as keykbn,
        substr(raw_data, 134, 5)::varchar(5) as chk,
        substr(raw_data, 139, 2)::varchar(2) as renban,
        substr(raw_data, 141, 4)::varchar(4) as jkkyy,
        substr(raw_data, 145, 2)::varchar(2) as jkkmm,
        substr(raw_data, 147, 2)::varchar(2) as jkkdd,
        substr(raw_data, 149, 4)::varchar(4) as jkmyy,
        substr(raw_data, 153, 2)::varchar(2) as jkmmm,
        substr(raw_data, 155, 2)::varchar(2) as jkmdd,
        substr(raw_data, 157, 4)::varchar(4) as dkkyy,
        substr(raw_data, 161, 2)::varchar(2) as dkkmm,
        substr(raw_data, 163, 2)::varchar(2) as dkkdd,
        substr(raw_data, 165, 4)::varchar(4) as dkmyy,
        substr(raw_data, 169, 2)::varchar(2) as dkmmm,
        substr(raw_data, 171, 2)::varchar(2) as dkmdd,
        substr(raw_data, 173, 1)::varchar(1) as setkbn1,
        substr(raw_data, 174, 4)::varchar(4) as seiyak1,
        substr(raw_data, 178, 1)::varchar(1) as setkbn2,
        substr(raw_data, 179, 4)::varchar(4) as seiyak2,
        substr(raw_data, 183, 1)::varchar(1) as setkbn3,
        substr(raw_data, 184, 4)::varchar(4) as seiyak3,
        substr(raw_data, 188, 1)::varchar(1) as setkbn4,
        substr(raw_data, 189, 4)::varchar(4) as seiyak4,
        substr(raw_data, 193, 1)::varchar(1) as setkbn5,
        substr(raw_data, 194, 4)::varchar(4) as seiyak5,
        substr(raw_data, 198, 1)::varchar(1) as setkbn6,
        substr(raw_data, 199, 4)::varchar(4) as seiyak6,
        substr(raw_data, 203, 1)::varchar(1) as setkbn7,
        substr(raw_data, 204, 4)::varchar(4) as seiyak7,
        substr(raw_data, 208, 123)::varchar(123) as dum3,
        ldts,
        line_number
    from {{source('snowpipe_db_supplydemand', 'raw_tsjfa38t')}}
)
select * from substr_tsjfa38t2
