with substr_tsjfa393 as (
    select
        substr(raw_data, 2, 1)::varchar(1) as cdno,
        substr(raw_data, 3, 2)::varchar(2) as idln,
        substr(raw_data, 5, 2)::varchar(2) as idmm,
        substr(raw_data, 7, 2)::varchar(2) as iddd,
        substr(raw_data, 9, 4)::varchar(4) as idren,
        substr(raw_data, 13, 1)::varchar(1) as tskbn,
        substr(raw_data, 14, 2)::varchar(2) as sno,
        substr(raw_data, 16, 5)::varchar(5) as ktcd,
        substr(raw_data, 21, 1)::varchar(1) as odt,
        substr(raw_data, 22, 3)::varchar(3) as smkcd,
        substr(raw_data, 25, 5)::varchar(5) as dfsc,
        substr(raw_data, 30, 3)::varchar(3) as frkbn,
        substr(raw_data, 33, 1)::varchar(1) as mdlyr,
        substr(raw_data, 34, 1)::varchar(1) as kjcd,
        substr(raw_data, 35, 6)::varchar(6) as dum1,
        substr(raw_data, 41, 3)::varchar(3) as wmi,
        substr(raw_data, 44, 6)::varchar(6) as vds,
        substr(raw_data, 50, 2)::varchar(2) as mkrln,
        substr(raw_data, 52, 1)::varchar(1) as smkbn,
        substr(raw_data, 53, 1)::varchar(1) as smkms,
        substr(raw_data, 54, 1)::varchar(1) as stkh,
        substr(raw_data, 55, 6)::varchar(6) as dum2,
        substr(raw_data, 61, 7)::varchar(7) as frno,
        substr(raw_data, 68, 2)::varchar(2) as dum3,
        substr(raw_data, 70, 1)::varchar(1) as ipkbn,
        substr(raw_data, 71, 5)::varchar(5) as dum4,
        substr(raw_data, 76, 2)::varchar(2) as kyy,
        substr(raw_data, 78, 2)::varchar(2) as kmm,
        substr(raw_data, 80, 2)::varchar(2) as kdd,
        substr(raw_data, 82, 9)::varchar(9) as dum5,
        ldts,
    from {{ source('snowpipe_db_supplydemand', 'raw_tsjfa393') }}
)
select * from substr_tsjfa393