with substr_hostalc_na_cka01t0990 as (
  select
    substr(raw_data, 1, 2)::varchar(2) as psc,
    substr(raw_data, 3, 1)::varchar(1) as plantcode,
    substr(raw_data, 4, 8)::varchar(8) as lodate,
    substr(raw_data, 12, 10)::varchar(10) as idno,
    substr(raw_data, 22, 1)::varchar(1) as prsntstatline,
    substr(raw_data, 23, 2)::varchar(2) as holdtp,
    substr(raw_data, 25, 3)::varchar(3) as bcseqno,
    substr(raw_data, 28, 1)::varchar(1) as prsnttimes,
    substr(raw_data, 29, 15)::varchar(15) as lattppdate,
    substr(raw_data, 44, 14)::varchar(14) as lattpdate,
    substr(raw_data, 58, 1)::varchar(1) as prsntline,
    substr(raw_data, 59, 2)::varchar(2) as prsntlocat,
    substr(raw_data, 61, 1)::varchar(1) as latrpline,
    substr(raw_data, 62, 2)::varchar(2) as latrprp,
    substr(raw_data, 64, 3)::varchar(3) as latrpbcno,
    substr(raw_data, 67, 1)::varchar(1) as latrpcount,
    substr(raw_data, 68, 15)::varchar(15) as latrppdate,
    substr(raw_data, 83, 14)::varchar(14) as latrpdate,
    substr(raw_data, 97, 1)::varchar(1) as repairprocline,
    substr(raw_data, 98, 2)::varchar(2) as repairprocproc,
    substr(raw_data, 100, 1)::varchar(1) as repflg,
    substr(raw_data, 101, 1)::varchar(1) as pttreftpline,
    substr(raw_data, 102, 2)::varchar(2) as pttreftptp,
    substr(raw_data, 104, 1)::varchar(1) as latpointline,
    substr(raw_data, 105, 2)::varchar(2) as latpointpoint,
    substr(raw_data, 107, 3)::varchar(3) as latpointbcno,
    substr(raw_data, 110, 1)::varchar(1) as latpointcount,
    substr(raw_data, 111, 15)::varchar(15) as latpointpdate,
    substr(raw_data, 126, 14)::varchar(14) as latpointdate,
    substr(raw_data, 140, 1)::varchar(1) as physprocessline,
    substr(raw_data, 141, 2)::varchar(2) as physprocessproc,
    substr(raw_data, 143, 7)::varchar(7) as delaytime,
    substr(raw_data, 150, 1)::varchar(1) as prgrssgn,
    substr(raw_data, 151, 7)::varchar(7) as csprlatest,
    substr(raw_data, 158, 7)::varchar(7) as csprbyo,
    substr(raw_data, 165, 7)::varchar(7) as csprdeli,
    substr(raw_data, 172, 7)::varchar(7) as leadtime,
    substr(raw_data, 179, 7)::varchar(7) as leadtimebs,
    substr(raw_data, 186, 1)::varchar(1) as rejectstatusflg,
    substr(raw_data, 187, 17)::varchar(17) as frmstamp,
    substr(raw_data, 204, 17)::varchar(17) as vinno,
    substr(raw_data, 221, 1)::varchar(1) as vincd,
    substr(raw_data, 222, 12)::varchar(12) as apvprnotpca,
    substr(raw_data, 234, 1)::varchar(1) as inspectsign,
    substr(raw_data, 235, 1)::varchar(1) as accident,
    substr(raw_data, 236, 1)::varchar(1) as holdingline,
    substr(raw_data, 237, 2)::varchar(2) as holdingtp,
    substr(raw_data, 239, 2)::varchar(2) as holdingcode1,
    substr(raw_data, 241, 2)::varchar(2) as holdingcode2,
    substr(raw_data, 243, 2)::varchar(2) as holdingcode3,
    substr(raw_data, 245, 13)::varchar(13) as holdingpdatetm,
    substr(raw_data, 258, 8)::varchar(8) as delbasedate,
    substr(raw_data, 266, 14)::varchar(14) as erasetime,
    substr(raw_data, 280, 14)::varchar(14) as echangtime,
    substr(raw_data, 294, 14)::varchar(14) as amendtime,
    substr(raw_data, 308, 14)::varchar(14) as amenddfsctime,
    substr(raw_data, 322, 14)::varchar(14) as amendentrytime,
    substr(raw_data, 336, 14)::varchar(14) as cancelmvtm,
    substr(raw_data, 350, 6)::varchar(6) as jt5month,
    substr(raw_data, 356, 14)::varchar(14) as stschangetime,
    substr(raw_data, 370, 1)::varchar(1) as inpttrm,
    substr(raw_data, 371, 1)::varchar(1) as echangflg,
    substr(raw_data, 372, 1)::varchar(1) as newmodelflg,
    substr(raw_data, 373, 1)::varchar(1) as spvehicleflg,
    substr(raw_data, 374, 3)::varchar(3) as condcd1,
    substr(raw_data, 377, 3)::varchar(3) as condcd2,
    substr(raw_data, 380, 3)::varchar(3) as condcd3,
    substr(raw_data, 383, 3)::varchar(3) as condcd4,
    substr(raw_data, 386, 3)::varchar(3) as condcd5,
    substr(raw_data, 389, 3)::varchar(3) as condcd6,
    substr(raw_data, 392, 3)::varchar(3) as condcd7,
    substr(raw_data, 395, 3)::varchar(3) as condcd8,
    substr(raw_data, 398, 3)::varchar(3) as condcd9,
    substr(raw_data, 401, 3)::varchar(3) as condcd10,
    substr(raw_data, 404, 3)::varchar(3) as combino,
    substr(raw_data, 407, 20)::varchar(20) as combinosub,
    substr(raw_data, 427, 1)::varchar(1) as dockingstatus,
    substr(raw_data, 428, 14)::varchar(14) as updateymdel14dg,
    ldts,
    line_number
  from {{ ref('tmp_hostalc_na_cka01t0990')}}
)

select * from substr_hostalc_na_cka01t0990