with substr_da5a216a as (
    select
        substr(raw_data, 1, 1)::varchar(1) as mtkbn,
        substr(raw_data, 2, 1)::varchar(1) as lok_y4,
        substr(raw_data, 3, 9)::varchar(9) as syadai_kt,
        substr(raw_data, 12, 7)::varchar(7) as frmno,
        substr(raw_data, 19, 3)::varchar(3) as wmi,
        substr(raw_data, 22, 6)::varchar(6) as vds,
        substr(raw_data, 28, 1)::varchar(1) as mdlyr,
        substr(raw_data, 29, 1)::varchar(1) as vin_vds_cd,
        substr(raw_data, 30, 4)::varchar(4) as lok_y,
        substr(raw_data, 34, 2)::varchar(2) as lok_m,
        substr(raw_data, 36, 1)::varchar(1) as pline,
        substr(raw_data, 37, 2)::varchar(2) as tp,
        substr(raw_data, 39, 2)::varchar(2) as pretp_kbn,
        substr(raw_data, 41, 1)::varchar(1) as pass,
        substr(raw_data, 42, 2)::varchar(2) as seq,
        substr(raw_data, 44, 3)::varchar(3) as bcno,
        substr(raw_data, 47, 4)::varchar(4) as pld_y,
        substr(raw_data, 51, 2)::varchar(2) as pld_m,
        substr(raw_data, 53, 2)::varchar(2) as pld_d,
        substr(raw_data, 55, 1)::varchar(1) as pld_c,
        substr(raw_data, 56, 2)::varchar(2) as pld_mm,
        substr(raw_data, 58, 2)::varchar(2) as pld_nn,
        substr(raw_data, 60, 4)::varchar(4) as date_y,
        substr(raw_data, 64, 2)::varchar(2) as date_m,
        substr(raw_data, 66, 2)::varchar(2) as date_d,
        substr(raw_data, 68, 2)::varchar(2) as date_mm,
        substr(raw_data, 70, 2)::varchar(2) as date_nn,
        substr(raw_data, 72, 7)::varchar(7) as delaytime,
        substr(raw_data, 79, 7)::varchar(7) as tukayoyu,
        substr(raw_data, 86, 7)::varchar(7) as prodyoyu,
        substr(raw_data, 93, 7)::varchar(7) as hsuyoyu,
        substr(raw_data, 100, 7)::varchar(7) as leadtime,
        substr(raw_data, 107, 7)::varchar(7) as leadtimebs,
        substr(raw_data, 114, 1)::varchar(1) as pre,
        substr(raw_data, 115, 2)::varchar(2) as end_tp,
        substr(raw_data, 117, 2)::varchar(2) as gentp,
        substr(raw_data, 119, 1)::varchar(1) as keikoku,
        substr(raw_data, 120, 1)::varchar(1) as rireki,
        substr(raw_data, 121, 13)::varchar(13) as createuser,
        substr(raw_data, 134, 26)::varchar(26) as createtime,
        substr(raw_data, 160, 13)::varchar(13) as updateuser,
        substr(raw_data, 173, 26)::varchar(26) as updatetime,
        ldts
    from {{source('snowpipe_db_supplydemand', 'raw_da5a216a')}}
)
select * from substr_da5a216a