with substr_hostalc_na_cka01t0060 as (
  select
    substr(raw_data, 1, 2)::varchar(2) as psc,
    substr(raw_data, 3, 1)::varchar(1) as plantcode,
    substr(raw_data, 4, 8)::varchar(8) as lodate,
    substr(raw_data, 12, 10)::varchar(10) as idno,
    substr(raw_data, 22, 1)::varchar(1) as line,
    substr(raw_data, 23, 2)::varchar(2) as tp,
    substr(raw_data, 25, 8)::varchar(8) as schymdplant,
    substr(raw_data, 33, 1)::varchar(1) as schshplant,
    substr(raw_data, 34, 4)::varchar(4) as schhmplant,
    substr(raw_data, 38, 8)::varchar(8) as schymddate,
    substr(raw_data, 46, 4)::varchar(4) as schhmdate,
    substr(raw_data, 50, 8)::varchar(8) as schpsseqno,
    substr(raw_data, 58, 1)::varchar(1) as schkakeltaddcd,
    substr(raw_data, 59, 8)::varchar(8) as bdsschymdplant,
    substr(raw_data, 67, 1)::varchar(1) as bdsschshplant,
    substr(raw_data, 68, 4)::varchar(4) as bdsschhmplant,
    substr(raw_data, 72, 8)::varchar(8) as bdsschymddate,
    substr(raw_data, 80, 4)::varchar(4) as bdsschhmdate,
    substr(raw_data, 84, 8)::varchar(8) as bdsschpsseqno,
    substr(raw_data, 92, 1)::varchar(1) as bdsschkakeaddcd,
    substr(raw_data, 93, 8)::varchar(8) as latschymdplant,
    substr(raw_data, 101, 1)::varchar(1) as latschshplant,
    substr(raw_data, 102, 4)::varchar(4) as latschhmplant,
    substr(raw_data, 106, 8)::varchar(8) as latschymddate,
    substr(raw_data, 114, 4)::varchar(4) as latschhmdate,
    substr(raw_data, 118, 8)::varchar(8) as latpsseqno,
    substr(raw_data, 126, 1)::varchar(1) as latkakeltaddcd,
    substr(raw_data, 127, 8)::varchar(8) as tmpschymdplant,
    substr(raw_data, 135, 1)::varchar(1) as tmpschshplant,
    substr(raw_data, 136, 4)::varchar(4) as tmpschhmplant,
    substr(raw_data, 140, 8)::varchar(8) as tmpschymddate,
    substr(raw_data, 148, 4)::varchar(4) as tmpschhmdate,
    substr(raw_data, 152, 8)::varchar(8) as tmpschpsseqno,
    substr(raw_data, 160, 1)::varchar(1) as tmpsckakeltadcd,
    substr(raw_data, 161, 8)::varchar(8) as orgschtpymdpdt,
    substr(raw_data, 169, 1)::varchar(1) as orgschtpshpdt,
    substr(raw_data, 170, 4)::varchar(4) as orgschtphmpdt,
    substr(raw_data, 174, 8)::varchar(8) as orgschtpymdndt,
    substr(raw_data, 182, 4)::varchar(4) as orgschtphmndt,
    substr(raw_data, 186, 8)::varchar(8) as orgschpsseqno,
    substr(raw_data, 194, 1)::varchar(1) as orgsckakeltadcd,
    substr(raw_data, 195, 8)::varchar(8) as orgbdstpymdpdt,
    substr(raw_data, 203, 1)::varchar(1) as orgbdstpshpdt,
    substr(raw_data, 204, 4)::varchar(4) as orgbdstphmpdt,
    substr(raw_data, 208, 8)::varchar(8) as orgbdstpymdndt,
    substr(raw_data, 216, 4)::varchar(4) as orgbdstphmndt,
    substr(raw_data, 220, 8)::varchar(8) as orgbdspsseqno,
    substr(raw_data, 228, 1)::varchar(1) as orgbdkakeltadcd,
    substr(raw_data, 229, 7)::varchar(7) as bsdlytsc,
    substr(raw_data, 236, 7)::varchar(7) as bsdlysch,
    substr(raw_data, 243, 7)::varchar(7) as planlt,
    substr(raw_data, 250, 7)::varchar(7) as ldplanbs,
    substr(raw_data, 257, 14)::varchar(14) as updateymdel14dg,
    ldts,
    line_number
  from {{ ref('tmp_hostalc_na_cka01t0060')}}
)

select * from substr_hostalc_na_cka01t0060