with substr_tsjfa391 as (
    select
        substr(raw_data, 2, 2)::varchar(2) as sofc,
        substr(raw_data, 4, 3)::varchar(3) as recno,
        substr(raw_data, 7, 4)::varchar(4) as maker,
        substr(raw_data, 11, 2)::varchar(2) as line,
        substr(raw_data, 13, 1)::varchar(1) as pcode,
        substr(raw_data, 14, 2)::varchar(2) as sno,
        substr(raw_data, 16, 1)::varchar(1) as odt,
        substr(raw_data, 17, 5)::varchar(5) as odno,
        substr(raw_data, 22, 1)::varchar(1) as simei,
        substr(raw_data, 23, 2)::varchar(2) as ssyy,
        substr(raw_data, 25, 2)::varchar(2) as ssmm,
        substr(raw_data, 27, 2)::varchar(2) as ssdd,
        substr(raw_data, 29, 4)::varchar(4) as dais,
        substr(raw_data, 33, 4)::varchar(4) as daih,
        substr(raw_data, 37, 2)::varchar(2) as symei,
        substr(raw_data, 39, 3)::varchar(3) as gascd,
        substr(raw_data, 42, 1)::varchar(1) as dum1,
        substr(raw_data, 43, 3)::varchar(3) as frkbn,
        substr(raw_data, 46, 5)::varchar(5) as lktcd,
        substr(raw_data, 51, 15)::varchar(15) as lkata,
        substr(raw_data, 66, 5)::varchar(5) as hktcd,
        substr(raw_data, 71, 15)::varchar(15) as hkata,
        substr(raw_data, 86, 16)::varchar(16) as ckata,
        substr(raw_data, 102, 4)::varchar(4) as gaicd,
        substr(raw_data, 106, 4)::varchar(4) as ucd,
        substr(raw_data, 110, 1)::varchar(1) as nisgt,
        substr(raw_data, 111, 3)::varchar(3) as smkcd,
        substr(raw_data, 114, 10)::varchar(10) as smkk,
        substr(raw_data, 124, 1)::varchar(1) as steki,
        substr(raw_data, 125, 1)::varchar(1) as smkbr,
        substr(raw_data, 126, 2)::varchar(2) as kdlkd,
        substr(raw_data, 128, 4)::varchar(4) as kdlno,
        substr(raw_data, 132, 1)::varchar(1) as kdlsb,
        substr(raw_data, 133, 2)::varchar(2) as kdsiz,
        substr(raw_data, 135, 1)::varchar(1) as dskbn,
        substr(raw_data, 136, 3)::varchar(3) as wmi,
        substr(raw_data, 139, 6)::varchar(6) as vds,
        substr(raw_data, 145, 1)::varchar(1) as my,
        substr(raw_data, 146, 1)::varchar(1) as vinkbn,
        substr(raw_data, 147, 1)::varchar(1) as sketa,
        substr(raw_data, 148, 2)::varchar(2) as aite,
        substr(raw_data, 150, 1)::varchar(1) as unit,
        substr(raw_data, 151, 1)::varchar(1) as dum2,
        substr(raw_data, 152, 10)::varchar(10) as idno,
        substr(raw_data, 162, 10)::varchar(10) as skata,
        substr(raw_data, 172, 200)::varchar(200) as jkspc,
        substr(raw_data, 372, 200)::varchar(200) as jhspc,
        substr(raw_data, 572, 9)::varchar(9) as dum3,
        ldts
    from {{ source('snowpipe_db_supplydemand', 'raw_tsjfa391') }}
)
select * from substr_tsjfa391