with substr_da5a215a as (
    select
        substr(raw_data, 2, 6)::varchar(6) as syadai_kt,
        substr(raw_data, 8, 7)::varchar(7) as frmno,
        substr(raw_data, 15, 3)::varchar(3) as vin_wmi,
        substr(raw_data, 18, 6)::varchar(6) as vin_vds,
        substr(raw_data, 24, 8)::varchar(8) as vin_vis,
        substr(raw_data, 32, 1)::varchar(1) as mdlyr,
        substr(raw_data, 33, 1)::varchar(1) as vin_vds_cd,
        substr(raw_data, 34, 10)::varchar(10) as idntno,
        substr(raw_data, 44, 2)::varchar(2) as siyono,
        substr(raw_data, 46, 1)::varchar(1) as odt,
        substr(raw_data, 47, 5)::varchar(5) as dfscedno,
        substr(raw_data, 52, 2)::varchar(2) as syameicd,
        substr(raw_data, 54, 1)::varchar(1) as nisgt,
        substr(raw_data, 55, 5)::varchar(5) as hi_ktcd,
        substr(raw_data, 60, 15)::varchar(15) as hi_kt,
        substr(raw_data, 75, 5)::varchar(5) as lo_ktcd,
        substr(raw_data, 80, 15)::varchar(15) as lo_kt,
        substr(raw_data, 95, 4)::varchar(4) as gaihncd,
        substr(raw_data, 99, 4)::varchar(4) as utibrcd,
        substr(raw_data, 103, 200)::varchar(200) as sn_spec,
        substr(raw_data, 303, 3)::varchar(3) as smkcd,
        substr(raw_data, 306, 1)::varchar(1) as kojyo_kbn,
        substr(raw_data, 307, 2)::varchar(2) as tmkr2_r,
        substr(raw_data, 309, 2)::varchar(2) as tmkr2_s,
        substr(raw_data, 311, 8)::varchar(8) as k1ymd,
        substr(raw_data, 319, 8)::varchar(8) as sk_ymd,
        substr(raw_data, 327, 7)::varchar(7) as engno,
        substr(raw_data, 334, 4)::varchar(4) as sire_dai,
        substr(raw_data, 338, 3)::varchar(3) as frkbn,
        substr(raw_data, 341, 4)::varchar(4) as sms_syasyucd,
        substr(raw_data, 345, 5)::varchar(5) as hnbaitncd,
        substr(raw_data, 350, 4)::varchar(4) as haisya_y,
        substr(raw_data, 354, 2)::varchar(2) as haisya_m,
        substr(raw_data, 356, 2)::varchar(2) as haisya_d,
        substr(raw_data, 358, 13)::varchar(13) as createuser,
        substr(raw_data, 371, 26)::varchar(26) as createtime,
        substr(raw_data, 397, 13)::varchar(13) as updateuser,
        substr(raw_data, 410, 26)::varchar(26) as updatetime,
        ldts
    from {{source('snowpipe_db_supplydemand', 'raw_da5a215a')}}
)
select * from substr_da5a215a