with substr_da5a218a as (
    select
        substr(raw_data, 1, 1)::varchar(1) as mtkbn,
        substr(raw_data, 2, 1)::varchar(1) as knp_yr4,
        substr(raw_data, 3, 4)::varchar(4) as knp_yr,
        substr(raw_data, 7, 10)::varchar(10) as idntno,
        substr(raw_data, 17, 6)::varchar(6) as syadai_kt,
        substr(raw_data, 23, 7)::varchar(7) as frmno,
        substr(raw_data, 30, 3)::varchar(3) as vin_wmi,
        substr(raw_data, 33, 6)::varchar(6) as vin_vds,
        substr(raw_data, 39, 8)::varchar(8) as vin_vis,
        substr(raw_data, 47, 1)::varchar(1) as mdlyr,
        substr(raw_data, 48, 2)::varchar(2) as kdlotcd,
        substr(raw_data, 50, 4)::varchar(4) as kdlotno,
        substr(raw_data, 54, 2)::varchar(2) as kd_hnbtcd,
        substr(raw_data, 56, 2)::varchar(2) as siyono,
        substr(raw_data, 58, 2)::varchar(2) as syameicd,
        substr(raw_data, 60, 4)::varchar(4) as sms_syasyucd,
        substr(raw_data, 64, 16)::varchar(16) as ctl_kt,
        substr(raw_data, 96, 5)::varchar(5) as hi_ktcd,
        substr(raw_data, 101, 15)::varchar(15) as hi_kt,
        substr(raw_data, 116, 5)::varchar(5) as lo_ktcd,
        substr(raw_data, 121, 15)::varchar(15) as lo_kt,
        substr(raw_data, 136, 4)::varchar(4) as gaihncd,
        substr(raw_data, 140, 4)::varchar(4) as utibrcd,
        substr(raw_data, 144, 200)::varchar(200) as sn_spec,
        substr(raw_data, 344, 3)::varchar(3) as smkcd,
        substr(raw_data, 347, 1)::varchar(1) as odt,
        substr(raw_data, 348, 5)::varchar(5) as dfscedno,
        substr(raw_data, 353, 1)::varchar(1) as nisgt,
        substr(raw_data, 354, 1)::varchar(1) as smkbnrui,
        substr(raw_data, 355, 1)::varchar(1) as smkmeisai,
        substr(raw_data, 356, 1)::varchar(1) as siteitkh,
        substr(raw_data, 357, 4)::varchar(4) as lok_y,
        substr(raw_data, 361, 2)::varchar(2) as lok_m,
        substr(raw_data, 363, 2)::varchar(2) as	lok_d,
        substr(raw_data, 365, 2)::varchar(2) as lok_mkr,
        substr(raw_data, 367, 4)::varchar(4) as loj_y,
        substr(raw_data, 371, 2)::varchar(2) as loj_m,
        substr(raw_data, 373, 2)::varchar(2) as loj_d,
        substr(raw_data, 375, 1)::varchar(1) as kjcyoku,
        substr(raw_data, 376, 2)::varchar(2) as sk_kmkr,
        substr(raw_data, 378, 4)::varchar(4) as sk_y,
        substr(raw_data, 382, 2)::varchar(2) as sk_m,
        substr(raw_data, 384, 2)::varchar(2) as sk_d,
        substr(raw_data, 386, 4)::varchar(4) as hkate_y,
        substr(raw_data, 390, 2)::varchar(2) as hkate_m,
        substr(raw_data, 392, 2)::varchar(2) as hkate_d,
        substr(raw_data, 394, 7)::varchar(7) as engno,
        substr(raw_data, 401, 1)::varchar(1) as tiremkr_r,
        substr(raw_data, 402, 7)::varchar(7) as syukei_daisu,
        substr(raw_data, 409, 13)::varchar(13) as createuser,
        substr(raw_data, 422, 26)::varchar(26) as createtime,
        substr(raw_data, 448, 13)::varchar(13) as updateuser,
        substr(raw_data, 461, 26)::varchar(26) as updatetime,
        ldts
    from {{source('snowpipe_db_supplydemand', 'raw_da5a218a')}}
)
select * from substr_da5a218a