id: job_build_dm_variation_seisan_daisu
namespace: kestra_dbt_project.proj-job-seisan-shiyou-jisseki
labels:
  error: default_failed
  dbt: build

retry:
  behavior: CREATE_NEW_EXECUTION # or RETRY_FAILED_TASK
  type: exponential
  interval: PT5S
  maxAttempts: 7
  maxInterval: PT720S
  delayFactor: 30

# 手動実行時に指定できるdbtオプション
inputs:
  - id: dbt_options
    type: SELECT
    displayName: Choose dbt options
    values:
      - --full-refresh
    required: false
    allowCustomValue: true

variables: 
  dbt_command: 
    --select +dm_variation_seisan_daisu
    --exclude +dm_vinhis_spec200_allsalecar +stg_color_no +stg_siyouhenkan +stg_syasyu_siyousho
    --vars '{"DBT_JOB_NAME":"_dm_variation_seisan_daisu"}'

tasks:
  - id: clone_dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    commands:
      - dbt build {{ vars.dbt_command }}
        {{ inputs.dbt_options ?? "" }}

  - id: fetch_warning_logs
    type: io.kestra.plugin.core.log.Fetch
    level: WARN

  - id: get_warning_message
    type: io.kestra.plugin.transform.jsonata.TransformItems
    from: "{{ outputs.fetch_warning_logs.uri }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "00 09 05 * *"
    timezone: Asia/Tokyo

# エラーログを出力
errors:
  - id: fetch_error_logs
    type: io.kestra.plugin.core.log.Fetch

  - id: get_error_message
    type: io.kestra.plugin.transform.jsonata.TransformItems

outputs: 
  - id: output_error_log
    type: STRING
    value: "{{ read(outputs.get_error_message.uri) ?? read(outputs.get_warning_message.uri) | default('No message found.') }}"
  - id: output_state
    type: STRING
    value: "{{ tasks.clone_dbt_build.state ?? 'No state' }}"

# ログ出力
finally:
  - id: finally_log 
    type: io.kestra.plugin.core.log.Log
    message: 
      - "Git branch -> {{ namespace.GIT.BRANCH }}"
      - "dbt options -> {{ inputs.dbt_options ?? '' }}"
      - "dbt commands -> {{ vars.dbt_command }}"
      
disabled: false