{% snapshot scd_kokunaijutyujisseki_daily_atop %}
{{
    config(
        unique_key="concat_ws('-',
                    iff(jhinban is null, '', jhinban),
                    iff(tiikicd2 is null, '', tiikicd2),
                    iff(jcym is null, '', jcym),
                    iff(orgjcsu_1d is null, 0, orgjcsu_1d),
                    iff(orgrjtjcsu_1d is null, 0, orgrjtjcsu_1d),
                    iff(orghind_1d is null, 0, orghind_1d),
                    iff(ysjcsu_1d is null, 0, ysjcsu_1d),
                    iff(orgjcsu_2d is null, 0, orgjcsu_2d),
                    iff(orgrjtjcsu_2d is null, 0, orgrjtjcsu_2d),
                    iff(orghind_2d is null, 0, orghind_2d),
                    iff(ysjcsu_2d is null, 0, ysjcsu_2d),
                    iff(orgjcsu_3d is null, 0, orgjcsu_3d),
                    iff(orgrjtjcsu_3d is null, 0, orgrjtjcsu_3d),
                    iff(orghind_3d is null, 0, orghind_3d),
                    iff(ysjcsu_3d is null, 0, ysjcsu_3d),
                    iff(orgjcsu_4d is null, 0, orgjcsu_4d),
                    iff(orgrjtjcsu_4d is null, 0, orgrjtjcsu_4d),
                    iff(orghind_4d is null, 0, orghind_4d),
                    iff(ysjcsu_4d is null, 0, ysjcsu_4d),
                    iff(orgjcsu_5d is null, 0, orgjcsu_5d),
                    iff(orgrjtjcsu_5d is null, 0, orgrjtjcsu_5d),
                    iff(orghind_5d is null, 0, orghind_5d),
                    iff(ysjcsu_5d is null, 0, ysjcsu_5d),
                    iff(orgjcsu_6d is null, 0, orgjcsu_6d),
                    iff(orgrjtjcsu_6d is null, 0, orgrjtjcsu_6d),
                    iff(orghind_6d is null, 0, orghind_6d),
                    iff(ysjcsu_6d is null, 0, ysjcsu_6d),
                    iff(orgjcsu_7d is null, 0, orgjcsu_7d),
                    iff(orgrjtjcsu_7d is null, 0, orgrjtjcsu_7d),
                    iff(orghind_7d is null, 0, orghind_7d),
                    iff(ysjcsu_7d is null, 0, ysjcsu_7d),
                    iff(orgjcsu_8d is null, 0, orgjcsu_8d),
                    iff(orgrjtjcsu_8d is null, 0, orgrjtjcsu_8d),
                    iff(orghind_8d is null, 0, orghind_8d),
                    iff(ysjcsu_8d is null, 0, ysjcsu_8d),
                    iff(orgjcsu_9d is null, 0, orgjcsu_9d),
                    iff(orgrjtjcsu_9d is null, 0, orgrjtjcsu_9d),
                    iff(orghind_9d is null, 0, orghind_9d),
                    iff(ysjcsu_9d is null, 0, ysjcsu_9d),
                    iff(orgjcsu_10d is null, 0, orgjcsu_10d),
                    iff(orgrjtjcsu_10d is null, 0, orgrjtjcsu_10d),
                    iff(orghind_10d is null, 0, orghind_10d),
                    iff(ysjcsu_10d is null, 0, ysjcsu_10d),
                    iff(orgjcsu_11d is null, 0, orgjcsu_11d),
                    iff(orgrjtjcsu_11d is null, 0, orgrjtjcsu_11d),
                    iff(orghind_11d is null, 0, orghind_11d),
                    iff(ysjcsu_11d is null, 0, ysjcsu_11d),
                    iff(orgjcsu_12d is null, 0, orgjcsu_12d),
                    iff(orgrjtjcsu_12d is null, 0, orgrjtjcsu_12d),
                    iff(orghind_12d is null, 0, orghind_12d),
                    iff(ysjcsu_12d is null, 0, ysjcsu_12d),
                    iff(orgjcsu_13d is null, 0, orgjcsu_13d),
                    iff(orgrjtjcsu_13d is null, 0, orgrjtjcsu_13d),
                    iff(orghind_13d is null, 0, orghind_13d),
                    iff(ysjcsu_13d is null, 0, ysjcsu_13d),
                    iff(orgjcsu_14d is null, 0, orgjcsu_14d),
                    iff(orgrjtjcsu_14d is null, 0, orgrjtjcsu_14d),
                    iff(orghind_14d is null, 0, orghind_14d),
                    iff(ysjcsu_14d is null, 0, ysjcsu_14d),
                    iff(orgjcsu_15d is null, 0, orgjcsu_15d),
                    iff(orgrjtjcsu_15d is null, 0, orgrjtjcsu_15d),
                    iff(orghind_15d is null, 0, orghind_15d),
                    iff(ysjcsu_15d is null, 0, ysjcsu_15d),
                    iff(orgjcsu_16d is null, 0, orgjcsu_16d),
                    iff(orgrjtjcsu_16d is null, 0, orgrjtjcsu_16d),
                    iff(orghind_16d is null, 0, orghind_16d),
                    iff(ysjcsu_16d is null, 0, ysjcsu_16d),
                    iff(orgjcsu_17d is null, 0, orgjcsu_17d),
                    iff(orgrjtjcsu_17d is null, 0, orgrjtjcsu_17d),
                    iff(orghind_17d is null, 0, orghind_17d),
                    iff(ysjcsu_17d is null, 0, ysjcsu_17d),
                    iff(orgjcsu_18d is null, 0, orgjcsu_18d),
                    iff(orgrjtjcsu_18d is null, 0, orgrjtjcsu_18d),
                    iff(orghind_18d is null, 0, orghind_18d),
                    iff(ysjcsu_18d is null, 0, ysjcsu_18d),
                    iff(orgjcsu_19d is null, 0, orgjcsu_19d),
                    iff(orgrjtjcsu_19d is null, 0, orgrjtjcsu_19d),
                    iff(orghind_19d is null, 0, orghind_19d),
                    iff(ysjcsu_19d is null, 0, ysjcsu_19d),
                    iff(orgjcsu_20d is null, 0, orgjcsu_20d),
                    iff(orgrjtjcsu_20d is null, 0, orgrjtjcsu_20d),
                    iff(orghind_20d is null, 0, orghind_20d),
                    iff(ysjcsu_20d is null, 0, ysjcsu_20d),
                    iff(orgjcsu_21d is null, 0, orgjcsu_21d),
                    iff(orgrjtjcsu_21d is null, 0, orgrjtjcsu_21d),
                    iff(orghind_21d is null, 0, orghind_21d),
                    iff(ysjcsu_21d is null, 0, ysjcsu_21d),
                    iff(orgjcsu_22d is null, 0, orgjcsu_22d),
                    iff(orgrjtjcsu_22d is null, 0, orgrjtjcsu_22d),
                    iff(orghind_22d is null, 0, orghind_22d),
                    iff(ysjcsu_22d is null, 0, ysjcsu_22d),
                    iff(orgjcsu_23d is null, 0, orgjcsu_23d),
                    iff(orgrjtjcsu_23d is null, 0, orgrjtjcsu_23d),
                    iff(orghind_23d is null, 0, orghind_23d),
                    iff(ysjcsu_23d is null, 0, ysjcsu_23d),
                    iff(orgjcsu_24d is null, 0, orgjcsu_24d),
                    iff(orgrjtjcsu_24d is null, 0, orgrjtjcsu_24d),
                    iff(orghind_24d is null, 0, orghind_24d),
                    iff(ysjcsu_24d is null, 0, ysjcsu_24d),
                    iff(orgjcsu_25d is null, 0, orgjcsu_25d),
                    iff(orgrjtjcsu_25d is null, 0, orgrjtjcsu_25d),
                    iff(orghind_25d is null, 0, orghind_25d),
                    iff(ysjcsu_25d is null, 0, ysjcsu_25d),
                    iff(orgjcsu_26d is null, 0, orgjcsu_26d),
                    iff(orgrjtjcsu_26d is null, 0, orgrjtjcsu_26d),
                    iff(orghind_26d is null, 0, orghind_26d),
                    iff(ysjcsu_26d is null, 0, ysjcsu_26d),
                    iff(orgjcsu_27d is null, 0, orgjcsu_27d),
                    iff(orgrjtjcsu_27d is null, 0, orgrjtjcsu_27d),
                    iff(orghind_27d is null, 0, orghind_27d),
                    iff(ysjcsu_27d is null, 0, ysjcsu_27d),
                    iff(orgjcsu_28d is null, 0, orgjcsu_28d),
                    iff(orgrjtjcsu_28d is null, 0, orgrjtjcsu_28d),
                    iff(orghind_28d is null, 0, orghind_28d),
                    iff(ysjcsu_28d is null, 0, ysjcsu_28d),
                    iff(orgjcsu_29d is null, 0, orgjcsu_29d),
                    iff(orgrjtjcsu_29d is null, 0, orgrjtjcsu_29d),
                    iff(orghind_29d is null, 0, orghind_29d),
                    iff(ysjcsu_29d is null, 0, ysjcsu_29d),
                    iff(orgjcsu_30d is null, 0, orgjcsu_30d),
                    iff(orgrjtjcsu_30d is null, 0, orgrjtjcsu_30d),
                    iff(orghind_30d is null, 0, orghind_30d),
                    iff(ysjcsu_30d is null, 0, ysjcsu_30d),
                    iff(orgjcsu_31d is null, 0, orgjcsu_31d),
                    iff(orgrjtjcsu_31d is null, 0, orgrjtjcsu_31d),
                    iff(orghind_31d is null, 0, orghind_31d),
                    iff(ysjcsu_31d is null, 0, ysjcsu_31d),
                    iff(mtuserid is null, '', mtuserid),
                    iff(mttime is null, '1970-01-01 00:00:00.000', mttime),
                    ldts)",

        strategy='timestamp',
        updated_at='ldts',
        invalidate_hard_deletes=true,
    )
}}
select * from {{ ref('stg_kokunaijutyujisseki_daily_atop') }}
{% endsnapshot %}