with stg_yohinmaster_pixy as (
    select 
        syameino::varchar(12) as syameino, 
        tuikou::varchar(32) as tuikou, 
        seg::varchar(12) as seg, 
        seq::varchar(12) as seq, 
        tuimei::varchar(120) as tuimei, 
        katbitno::varchar(280) as katbitno, 
        naigai::varchar(4) as naigai, 
        tekiir1::varchar(16) as tekiir1, 
        tekiir2::varchar(16) as tekiir2, 
        tekiir3::varchar(16) as tekiir3, 
        tekiir4::varchar(16) as tekiir4, 
        tekiir5::varchar(16) as tekiir5, 
        tekiir6::varchar(16) as tekiir6, 
        tekiir7::varchar(16) as tekiir7, 
        tekiir8::varchar(16) as tekiir8, 
        tekiir9::varchar(16) as tekiir9, 
        tekiir10::varchar(16) as tekiir10, 
        tekiir11::varchar(16) as tekiir11, 
        tekiir12::varchar(16) as tekiir12, 
        tekiir13::varchar(16) as tekiir13, 
        tekiir14::varchar(16) as tekiir14, 
        tekiir15::varchar(16) as tekiir15, 
        tekiir16::varchar(16) as tekiir16, 
        tekiir17::varchar(16) as tekiir17, 
        tekiir18::varchar(16) as tekiir18, 
        tekiir19::varchar(16) as tekiir19, 
        tekiir20::varchar(16) as tekiir20, 
        tekiir21::varchar(16) as tekiir21, 
        tekiir22::varchar(16) as tekiir22, 
        tekiir23::varchar(16) as tekiir23, 
        tekiir24::varchar(16) as tekiir24, 
        tekiir25::varchar(16) as tekiir25, 
        tekiir26::varchar(16) as tekiir26, 
        tekiir27::varchar(16) as tekiir27, 
        tekiir28::varchar(16) as tekiir28, 
        tekiir29::varchar(16) as tekiir29, 
        tekiir30::varchar(16) as tekiir30, 
        hinban::varchar(40) as hinban, 
        ruibet::varchar(8) as ruibet, 
        hinmei::varchar(204) as hinmei, 
        ruimei::varchar(80) as ruimei, 
        tekikr::varchar(24) as tekikr, 
        tekimd::varchar(24) as tekimd, 
        sochak::varchar(12) as sochak, 
        tekicm::varchar(200) as tekicm, 
        to_number(kosuu,8,0)::number(8,0) as kosuu, 
        to_number(lp,32,0)::number(32,0) as lp, 
        dn::varchar(32) as dn, 
        torihi::varchar(32) as torihi, 
        torijkn::varchar(8) as torijkn, 
        syohincd::varchar(24) as syohincd, 
        treecd::varchar(28) as treecd, 
        syasin::varchar(12) as syasin, 
        suisyo::varchar(4) as suisyo, 
        sakujo::varchar(4) as sakujo, 
        syorikbn::varchar(4) as syorikbn, 
        touroku::varchar(32) as touroku, 
        _fivetran_synced::timestamp_ntz as ldts
    from {{ source('fivetran_database_idr_pixy_dxpfy2d','raw_cva97dxyohinm') }}
    where _fivetran_deleted = 'false'
)
select * from stg_yohinmaster_pixy