with stg_tuikouoyakokanren_pixy as (
    select 
        syameino::varchar(12) as syameino, 
        oyatui::varchar(32) as oyatui, 
        setcd::varchar(4) as setcd, 
        syasin::varchar(12) as syasin, 
        suisyo::varchar(4) as suisyo, 
        tuimei::varchar(120) as tuimei, 
        kotui1::varchar(32) as kotui1, 
        kotui2::varchar(32) as kotui2, 
        kotui3::varchar(32) as kotui3, 
        kotui4::varchar(32) as kotui4, 
        kotui5::varchar(32) as kotui5, 
        kotui6::varchar(32) as kotui6, 
        kotui7::varchar(32) as kotui7, 
        kotui8::varchar(32) as kotui8, 
        kotui9::varchar(32) as kotui9, 
        kotui10::varchar(32) as kotui10, 
        kotui11::varchar(32) as kotui11, 
        kotui12::varchar(32) as kotui12, 
        kotui13::varchar(32) as kotui13, 
        kotui14::varchar(32) as kotui14, 
        kotui15::varchar(32) as kotui15, 
        kotui16::varchar(32) as kotui16, 
        kotui17::varchar(32) as kotui17, 
        kotui18::varchar(32) as kotui18, 
        kotui19::varchar(32) as kotui19, 
        kotui20::varchar(32) as kotui20, 
        kotui21::varchar(32) as kotui21, 
        kotui22::varchar(32) as kotui22, 
        kotui23::varchar(32) as kotui23, 
        kotui24::varchar(32) as kotui24, 
        kotui25::varchar(32) as kotui25, 
        kotui26::varchar(32) as kotui26, 
        kotui27::varchar(32) as kotui27, 
        kotui28::varchar(32) as kotui28, 
        kotui29::varchar(32) as kotui29, 
        kotui30::varchar(32) as kotui30, 
        touroku::varchar(32) as touroku, 
        kousin::varchar(32) as kousin, 
        tantou::varchar(28) as tantou, 
        _fivetran_synced::timestamp_ntz as ldts
    from {{ source('fivetran_database_idr_pixy_dxpfy2d','raw_cva97oyakot') }}
    where _fivetran_deleted = 'false'
)
select * from stg_tuikouoyakokanren_pixy
