with stg_yohinmaster_pixy as (
    select 
        syameino::varchar(3) as syameino, 
        tuikou::varchar(8) as tuikou, 
        seg::varchar(3) as seg, 
        seq::varchar(3) as seq, 
        tuimei::varchar(30) as tuimei, 
        katbitno::varchar(70) as katbitno, 
        naigai::varchar(1) as naigai, 
        tekiir1::varchar(4) as tekiir1, 
        tekiir2::varchar(4) as tekiir2, 
        tekiir3::varchar(4) as tekiir3, 
        tekiir4::varchar(4) as tekiir4, 
        tekiir5::varchar(4) as tekiir5, 
        tekiir6::varchar(4) as tekiir6, 
        tekiir7::varchar(4) as tekiir7, 
        tekiir8::varchar(4) as tekiir8, 
        tekiir9::varchar(4) as tekiir9, 
        tekiir10::varchar(4) as tekiir10, 
        tekiir11::varchar(4) as tekiir11, 
        tekiir12::varchar(4) as tekiir12, 
        tekiir13::varchar(4) as tekiir13, 
        tekiir14::varchar(4) as tekiir14, 
        tekiir15::varchar(4) as tekiir15, 
        tekiir16::varchar(4) as tekiir16, 
        tekiir17::varchar(4) as tekiir17, 
        tekiir18::varchar(4) as tekiir18, 
        tekiir19::varchar(4) as tekiir19, 
        tekiir20::varchar(4) as tekiir20, 
        tekiir21::varchar(4) as tekiir21, 
        tekiir22::varchar(4) as tekiir22, 
        tekiir23::varchar(4) as tekiir23, 
        tekiir24::varchar(4) as tekiir24, 
        tekiir25::varchar(4) as tekiir25, 
        tekiir26::varchar(4) as tekiir26, 
        tekiir27::varchar(4) as tekiir27, 
        tekiir28::varchar(4) as tekiir28, 
        tekiir29::varchar(4) as tekiir29, 
        tekiir30::varchar(4) as tekiir30, 
        hinban::varchar(10) as hinban, 
        ruibet::varchar(2) as ruibet, 
        hinmei::varchar(51) as hinmei, 
        ruimei::varchar(20) as ruimei, 
        tekikr::varchar(6) as tekikr, 
        tekimd::varchar(6) as tekimd, 
        sochak::varchar(3) as sochak, 
        tekicm::varchar(50) as tekicm, 
        to_number(kosuu,2,0)::number(2,0) as kosuu, 
        to_number(lp,8,0)::number(8,0) as lp, 
        dn::varchar(8) as dn, 
        torihi::varchar(8) as torihi, 
        torijkn::varchar(2) as torijkn, 
        syohincd::varchar(6) as syohincd, 
        treecd::varchar(7) as treecd, 
        syasin::varchar(3) as syasin, 
        suisyo::varchar(1) as suisyo, 
        sakujo::varchar(1) as sakujo, 
        syorikbn::varchar(1) as syorikbn, 
        touroku::varchar(8) as touroku,  
        _fivetran_synced::timestamp_ntz as ldts
    from {{ source('fivetran_database_idr_pixy_dxpfy2d','raw_cva97dxyohinm') }}
    where _fivetran_deleted = 'false'
)
select * from stg_yohinmaster_pixy