with stg_tuikouoyakokanren_pixy as (
    select 
        syameino::varchar(3) as syameino, 
        oyatui::varchar(8) as oyatui, 
        setcd::varchar(1) as setcd, 
        syasin::varchar(3) as syasin, 
        suisyo::varchar(1) as suisyo, 
        tuimei::varchar(30) as tuimei, 
        kotui1::varchar(8) as kotui1, 
        kotui2::varchar(8) as kotui2, 
        kotui3::varchar(8) as kotui3, 
        kotui4::varchar(8) as kotui4, 
        kotui5::varchar(8) as kotui5, 
        kotui6::varchar(8) as kotui6, 
        kotui7::varchar(8) as kotui7, 
        kotui8::varchar(8) as kotui8, 
        kotui9::varchar(8) as kotui9, 
        kotui10::varchar(8) as kotui10, 
        kotui11::varchar(8) as kotui11, 
        kotui12::varchar(8) as kotui12, 
        kotui13::varchar(8) as kotui13, 
        kotui14::varchar(8) as kotui14, 
        kotui15::varchar(8) as kotui15, 
        kotui16::varchar(8) as kotui16, 
        kotui17::varchar(8) as kotui17, 
        kotui18::varchar(8) as kotui18, 
        kotui19::varchar(8) as kotui19, 
        kotui20::varchar(8) as kotui20, 
        kotui21::varchar(8) as kotui21, 
        kotui22::varchar(8) as kotui22, 
        kotui23::varchar(8) as kotui23, 
        kotui24::varchar(8) as kotui24, 
        kotui25::varchar(8) as kotui25, 
        kotui26::varchar(8) as kotui26, 
        kotui27::varchar(8) as kotui27, 
        kotui28::varchar(8) as kotui28, 
        kotui29::varchar(8) as kotui29, 
        kotui30::varchar(8) as kotui30, 
        touroku::varchar(8) as touroku, 
        kousin::varchar(8) as kousin, 
        tantou::varchar(7) as tantou,  
        _fivetran_synced::timestamp_ntz as ldts
    from {{ source('fivetran_database_idr_pixy','raw_cva97oyakot') }}
    where _fivetran_deleted = 'false'
)
select * from stg_tuikouoyakokanren_pixy
