{{
    config(
        materialized='incremental',
        incremental_strategy = 'append'
    )
}}

with stg_hunadumijisseki_atop as (
    select
        iff(rtrim(hkanri, ' 　') = '', null, rtrim(hkanri, ' 　'))::varchar(4) as hkanri,
        iff(rtrim(senmei, ' 　') = '', null, rtrim(senmei, ' 　'))::varchar(30) as senmei,
        iff(rtrim(disksmscd, ' 　') = '', null, rtrim(disksmscd, ' 　'))::varchar(7) as disksmscd,
        iff(rtrim(sensyacd, ' 　') = '', null, rtrim(sensyacd, ' 　'))::varchar(3) as sensyacd,
        iff(rtrim(yusokbn, ' 　') = '', null, rtrim(yusokbn, ' 　'))::varchar(1) as yusokbn,
        iff(rtrim(tumimei, ' 　') = '', null, rtrim(tumimei, ' 　'))::varchar(10) as tumimei,
        iff(rtrim(niagmei, ' 　') = '', null, rtrim(niagmei, ' 　'))::varchar(20) as niagmei,
        iff(rtrim(tumisvkbn, ' 　') = '', null, rtrim(tumisvkbn, ' 　'))::varchar(1) as tumisvkbn,
        iff(rtrim(csymd, ' 　') = '', null, to_date(csymd, 'yyyymmdd'))::date as csymd,
        iff(rtrim(funaymd, ' 　') = '', null, to_date(funaymd, 'yyyymmdd'))::date as funaymd,
        iff(rtrim(eta, ' 　') = '', null, to_date(eta, 'yyyymmdd'))::date as eta,
        iff(rtrim(sstcd, ' 　') = '', null, rtrim(sstcd, ' 　'))::varchar(1) as sstcd,
        iff(rtrim(fnsshiuntnfgox, ' 　') = '', null, to_decimal(fnsshiuntnfgox)/power(10,2))::number(13,2) as fnsshiuntnfgox,
        iff(rtrim(fnzmjsklclhiy, ' 　') = '', null,rtrim(fnzmjsklclhiy, ' 　'))::varchar(13) as fnzmjsklclhiy,
        iff(rtrim(blno20c, ' 　') = '', null,rtrim(blno20c, ' 　'))::varchar(20) as blno20c,
        iff(rtrim(invno, ' 　') = '', null,rtrim(invno, ' 　'))::varchar(10) as invno,
        iff(rtrim(dlrcd_g_dist, ' 　') = '', null,rtrim(dlrcd_g_dist, ' 　'))::varchar(5) as dlrcd_g_dist,
        iff(rtrim(dlrcd_g_fd, ' 　') = '', null,rtrim(dlrcd_g_fd, ' 　'))::varchar(2) as dlrcd_g_fd,
        iff(rtrim(hanbaicd, ' 　') = '', null,rtrim(hanbaicd, ' 　'))::varchar(1) as hanbaicd,
        iff(rtrim(syohnkbn, ' 　') = '', null,rtrim(syohnkbn, ' 　'))::varchar(1) as syohnkbn,
        iff(rtrim(syosyakbn, ' 　') = '', null,rtrim(syosyakbn, ' 　'))::varchar(1) as syosyakbn,
        iff(rtrim(tatnkbn, ' 　') = '', null,rtrim(tatnkbn, ' 　'))::varchar(1) as tatnkbn,
        iff(rtrim(hanstsakcd, ' 　') = '', null,rtrim(hanstsakcd, ' 　'))::varchar(3) as hanstsakcd,
        iff(rtrim(kessai, ' 　') = '', null,rtrim(kessai, ' 　'))::varchar(2) as kessai,
        iff(rtrim(yumukbn, ' 　') = '', null,rtrim(yumukbn, ' 　'))::varchar(1) as yumukbn,
        iff(rtrim(tndkinv, ' 　') = '', null,rtrim(tndkinv, ' 　'))::varchar(1) as tndkinv,
        iff(rtrim(invhktka, ' 　') = '', null,rtrim(invhktka, ' 　'))::varchar(1) as invhktka,
        iff(rtrim(tkytankainvgokx, ' 　') = '', null, to_decimal(tkytankainvgokx)/power(10,2))::number(13,2) as tkytankainvgokx,
        iff(rtrim(tkytankayengokx, ' 　') = '', null, to_decimal(tkytankayengokx)/power(10,1))::number(13,1) as tkytankayengokx,
        iff(rtrim(invaun, ' 　') = '', null, to_decimal(invaun)/power(10,2))::number(13,2) as invaun,
        iff(rtrim(hnhokn, ' 　') = '', null, to_decimal(hnhokn)/power(10,2))::number(11,2) as hnhokn,
        iff(rtrim(pmkbn, ' 　') = '', null, rtrim(pmkbn, ' 　'))::varchar(1) as pmkbn,
        iff(rtrim(hntsrkgi, ' 　') = '', null, to_decimal(hntsrkgi)/power(10,2))::number(11,2) as hntsrkgi,
        iff(rtrim(gystl, ' 　') = '', null, to_decimal(gystl)/power(10,3))::number(7,3) as gystl,
        iff(rtrim(invtnisyksukei, ' 　') = '', null, to_decimal(invtnisyksukei))::number(7,0) as invtnisyksukei,
        iff(rtrim(casesuinvgokx, ' 　') = '', null, to_decimal(casesuinvgokx))::number(7,0) as casesuinvgokx,
        iff(rtrim(invbiymd, ' 　') = '', null, to_date(invbiymd, 'yyyymmdd'))::date as invbiymd,
        iff(rtrim(kansanratesyax, ' 　') = '', null, to_decimal(kansanratesyax)/power(10,6))::number(9,6) as kansanratesyax,
        iff(rtrim(kansanratesyox, ' 　') = '', null, to_decimal(kansanratesyox)/power(10,6))::number(9,6) as kansanratesyox,
        iff(rtrim(toricd, ' 　') = '', null, rtrim(toricd, ' 　'))::varchar(5) as toricd,
        iff(rtrim(gifsyohizei13, ' 　') = '', null, to_decimal(gifsyohizei13)/power(10,2))::number(13,2) as gifsyohizei13,
        iff(rtrim(uriageymd, ' 　') = '', null, to_date(uriageymd, 'yyyymmdd'))::date as uriageymd,
        iff(rtrim(pkgsutal, ' 　') = '', null, to_decimal(pkgsutal))::number(5,0) as pkgsutal,
        iff(rtrim(blno20i, ' 　') = '', null, rtrim(blno20i, ' 　'))::varchar(20) as blno20i,
        iff(rtrim(drftno, ' 　') = '', null, rtrim(drftno, ' 　'))::varchar(10) as drftno,
        iff(rtrim(caseno, ' 　') = '', null, rtrim(caseno, ' 　'))::varchar(8) as caseno,
        iff(rtrim(grwtkg, ' 　') = '', null, to_decimal(grwtkg)/power(10,1))::number(5,1) as grwtkg,
        iff(rtrim(ysgrs, ' 　') = '', null, to_decimal(ysgrs)/power(10,3))::number(5,3) as ysgrs,
        iff(rtrim(pkgsu2, ' 　') = '', null, to_decimal(pkgsu2)/power(10,1))::number(2,1) as pkgsu2,
        iff(rtrim(kpkytnkbn, ' 　') = '', null, rtrim(kpkytnkbn, ' 　'))::varchar(1) as kpkytnkbn,
        iff(rtrim(tomkmkbn, ' 　') = '', null, rtrim(tomkmkbn, ' 　'))::varchar(1) as tomkmkbn,
        iff(rtrim(pshukakbn, ' 　') = '', null, rtrim(pshukakbn, ' 　'))::varchar(1) as pshukakbn,
        iff(rtrim(casecd, ' 　') = '', null, rtrim(casecd, ' 　'))::varchar(2) as casecd,
        iff(rtrim(hanyymd, ' 　') = '', null, to_date(hanyymd, 'yyyymmdd'))::date as hanyymd,
        iff(rtrim(konknymd, ' 　') = '', null, to_date(konknymd, 'yyyymmdd'))::date as konknymd,
        iff(rtrim(nisgt, ' 　') = '', null, rtrim(nisgt, ' 　'))::varchar(1) as nisgt,
        iff(rtrim(rtkbn, ' 　') = '', null, rtrim(rtkbn, ' 　'))::varchar(1) as rtkbn,
        iff(rtrim(shinban, ' 　') = '', null, rtrim(shinban, ' 　'))::varchar(20) as shinban,
        iff(rtrim(odrno, ' 　') = '', null, rtrim(odrno, ' 　'))::varchar(8) as odrno,
        iff(rtrim(itemno, ' 　') = '', null, rtrim(itemno, ' 　'))::varchar(4) as itemno,
        iff(rtrim(juchuymd, ' 　') = '', null, to_date(juchuymd, 'yyyymmdd'))::date as juchuymd,
        iff(rtrim(syusiymd, ' 　') = '', null, to_date(syusiymd, 'yyyymmdd'))::date as syusiymd,
        iff(rtrim(shinmei, ' 　') = '', null, rtrim(shinmei, ' 　'))::varchar(20) as shinmei,
        iff(rtrim(syukkasu, ' 　') = '', null, to_decimal(syukkasu))::number(6,0) as syukkasu,
        iff(rtrim(syukancd, ' 　') = '', null, rtrim(syukancd, ' 　'))::varchar(1) as syukancd,
        iff(rtrim(tekiyotankaen, ' 　') = '', null, to_decimal(tekiyotankaen)/power(10,1))::number(13,1) as tekiyotankaen,
        iff(rtrim(tekiyotankainv, ' 　') = '', null, to_decimal(tekiyotankainv)/power(10,2))::number(13,2) as tekiyotankainv,
        iff(rtrim(tokeibricd, ' 　') = '', null, rtrim(tokeibricd, ' 　'))::varchar(3) as tokeibricd,
        iff(rtrim(kyokacd, ' 　') = '', null, rtrim(kyokacd, ' 　'))::varchar(1) as kyokacd,
        iff(rtrim(raisenscd, ' 　') = '', null, rtrim(raisenscd, ' 　'))::varchar(1) as raisenscd,
        iff(rtrim(kknhncd, ' 　') = '', null, rtrim(kknhncd, ' 　'))::varchar(1) as kknhncd,
        iff(rtrim(basecd, ' 　') = '', null, rtrim(basecd, ' 　'))::varchar(2) as basecd,
        iff(rtrim(tarifcd, ' 　') = '', null, rtrim(tarifcd, ' 　'))::varchar(3) as tarifcd,
        iff(rtrim(zonecd, ' 　') = '', null, rtrim(zonecd, ' 　'))::varchar(2) as zonecd,
        iff(rtrim(daicom, ' 　') = '', null, rtrim(daicom, ' 　'))::varchar(8) as daicom,
        iff(rtrim(odrzok, ' 　') = '', null, rtrim(odrzok, ' 　'))::varchar(1) as odrzok,
        iff(rtrim(knkyudo, ' 　') = '', null, rtrim(knkyudo, ' 　'))::varchar(1) as knkyudo,
        iff(rtrim(tkytnkbn, ' 　') = '', null, rtrim(tkytnkbn, ' 　'))::varchar(1) as tkytnkbn,
        iff(rtrim(endsijymd, ' 　') = '', null, to_date(endsijymd, 'yyyymmdd'))::date as endsijymd,
        iff(rtrim(bokbn, ' 　') = '', null, rtrim(bokbn, ' 　'))::varchar(1) as bokbn,
        iff(rtrim(pfcd, ' 　') = '', null, rtrim(pfcd, ' 　'))::varchar(2) as pfcd,
        iff(rtrim(syohincd, ' 　') = '', null, rtrim(syohincd, ' 　'))::varchar(2) as syohincd,
        iff(rtrim(hinmkcd, ' 　') = '', null, rtrim(hinmkcd, ' 　'))::varchar(4) as hinmkcd,
        iff(rtrim(brnet, ' 　') = '', null, to_decimal(brnet)/power(10,1))::number(9,1) as brnet,
        iff(rtrim(tskbn, ' 　') = '', null, rtrim(tskbn, ' 　'))::varchar(1) as tskbn,
        iff(rtrim(gaikoksngaihkbn, ' 　') = '', null, rtrim(gaikoksngaihkbn, ' 　'))::varchar(1) as gaikoksngaihkbn,
        ldts::timestamp_ntz(9) as ldts,
    from {{ref('substr_ktrla01vzz0kvp00q4')}}
    {% if is_incremental() %}
        where ldts > (select max(ldts) from {{this}})
    {% endif %}
)
select * from stg_hunadumijisseki_atop