with stg_battingjoho_pixy as (
    select 
        syameino::varchar(3) as syameino, 
        tuikocd::varchar(8) as tuikocd, 
        seg::varchar(3) as seg, 
        seq::varchar(3) as seq, 
        renban::varchar(2) as renban, 
        hsopt1::varchar(4) as hsopt1, 
        hsopt2::varchar(4) as hsopt2, 
        hsopt3::varchar(4) as hsopt3, 
        hkopt1::varchar(4) as hkopt1, 
        hkopt2::varchar(4) as hkopt2, 
        hkopt3::varchar(4) as hkopt3, 
        hkopt4::varchar(4) as hkopt4, 
        hkopt5::varchar(4) as hkopt5, 
        hkopt6::varchar(4) as hkopt6, 
        hkopt7::varchar(4) as hkopt7, 
        hkopt8::varchar(4) as hkopt8, 
        touroku::varchar(8) as touroku, 
        kousin::varchar(8) as kousin, 
        tantou::varchar(7) as tantou, 
        hsopt4::varchar(4) as hsopt4, 
        hsopt5::varchar(4) as hsopt5, 
        hsopt6::varchar(4) as hsopt6, 
        hsopt7::varchar(4) as hsopt7, 
        hsopt8::varchar(4) as hsopt8, 
        hsopt9::varchar(4) as hsopt9, 
        hsopt10::varchar(4) as hsopt10, 
        hkopt9::varchar(4) as hkopt9, 
        hkopt10::varchar(4) as hkopt10, 
        hkopt11::varchar(4) as hkopt11, 
        hkopt12::varchar(4) as hkopt12, 
        hkopt13::varchar(4) as hkopt13, 
        hkopt14::varchar(4) as hkopt14, 
        hkopt15::varchar(4) as hkopt15, 
        hkopt16::varchar(4) as hkopt16, 
        hkopt17::varchar(4) as hkopt17, 
        hkopt18::varchar(4) as hkopt18, 
        hkopt19::varchar(4) as hkopt19, 
        hkopt20::varchar(4) as hkopt20, 
        hkopt21::varchar(4) as hkopt21, 
        hkopt22::varchar(4) as hkopt22, 
        hkopt23::varchar(4) as hkopt23, 
        hkopt24::varchar(4) as hkopt24, 
        hkopt25::varchar(4) as hkopt25, 
        hkopt26::varchar(4) as hkopt26, 
        hkopt27::varchar(4) as hkopt27, 
        hkopt28::varchar(4) as hkopt28, 
        hkopt29::varchar(4) as hkopt29, 
        hkopt30::varchar(4) as hkopt30,  
        _fivetran_synced::timestamp_ntz as ldts
    from {{ source('fivetran_database_idr_pixy','raw_cva97batjoho') }}
    where _fivetran_deleted = 'false'
)
select * from stg_battingjoho_pixy
