{{ config(
      materialized='view'
   )
}}

with stg_hachuhuka_maps_view as (
  select
    odr_rqe_id::varchar(15) as odr_rqe_id, -- 発注依頼_ID
    arrangement_serial_no::varchar(6) as arrangement_serial_no, -- 手配連番
    control_key::varchar(1) as control_key, -- コントロールキー
    order_qty_per_sheet::varchar(11) as order_qty_per_sheet, -- 発注数量/枚
    measure_delivery_qty::varchar(11) as measure_delivery_qty, -- 計量数量_納入数量
    weight_necessity_cls::varchar(1) as weight_necessity_cls, -- 計量要否区分
    gi_wh_code::varchar(2) as gi_wh_code, -- 出庫倉庫コード
    y_item_no::varchar(10) as y_item_no, -- Y品番
    supplier_code::varchar(4) as supplier_code, -- 仕入先コード
    maker_code::varchar(4) as maker_code, -- 製造メーカーコード
    standard_weight::varchar(5) as standard_weight, -- 基準重量
    minimum_necessary_wt::varchar(5) as minimum_necessary_wt, -- 最低必要重量
    gi_post_no::varchar(3) as gi_post_no, -- 出庫ポストNo
    burden_post_no::varchar(3) as burden_post_no, -- 負担ポストNo
    gi_order::varchar(15) as gi_order, -- 出庫オーダー
    subject::varchar(1) as subject, -- 科目
    factory_code::varchar(1) as factory_code, -- 工場コード
    read_odr_cls::varchar(1) as read_odr_cls, -- 読取発注区分
    repair_supplier_code::varchar(4) as repair_supplier_code, -- 修理仕入先コード
    gi_depart_code::varchar(5) as gi_depart_code, -- 出庫部署コード
    burden_depart_code::varchar(5) as burden_depart_code, -- 負担部署コード
    procurement_cls::varchar(1) as procurement_cls, -- 調達区分
    z_item_cls::varchar(1) as z_item_cls, -- Z品区分
    new_used_cls::varchar(1) as new_used_cls, -- 新品中古区分
    in_house_make_item_cls::varchar(1) as in_house_make_item_cls, -- 内製製作品区分
    in_house_repair_item_cls::varchar(1) as in_house_repair_item_cls, -- 内製修理品区分
    wh_code_intensive_in::varchar(2) as wh_code_intensive_in, -- 集中在庫倉庫
    order_quantity_summary::varchar(11) as order_quantity_summary, -- 発注数(サマリ)
    kanban_sheet_qty_summary::varchar(3) as kanban_sheet_qty_summary, -- かんばん枚数(サマリ)
    req_wh_code::varchar(2) as req_wh_code, -- 依頼倉庫コード
    entry_test_mtl_cls::varchar(1) as entry_test_mtl_cls, -- 号口テスト材区分
    location_code_serial_number::varchar(4) as location_code_serial_number, -- 所番地連番
    kanban_destination_no_sup::varchar(3) as kanban_destination_no_sup, -- かんばん行先No_調達拠点
    kanban_destination_no_proc::varchar(3) as kanban_destination_no_proc, -- かんばん行先No_統括拠点
    coil_width::varchar(9) as coil_width, -- コイル幅
    order_qty_uom_name::varchar(4) as order_qty_uom_name, -- 発注数量単位名称
    weight_cv_cls::varchar(1) as weight_cv_cls, -- 重量変換区分
    location_code::varchar(10) as location_code, -- 所番地
    new_repair_order_cls::varchar(1) as new_repair_order_cls, -- 新品修理発注区分
    new_supplier::varchar(4) as new_supplier, -- 新品仕入先
    scheme_no::varchar(7) as scheme_no, -- 工整書No
    supplier_post_no::varchar(5) as supplier_post_no, -- 仕入先ポストNo
    sheet_quantity::varchar(5) as sheet_quantity, -- シート数・本数
    sheet_quantity_unit::varchar(1) as sheet_quantity_unit, -- シート数・本数単位
    delivery_lt::varchar(3) as delivery_lt, -- 手配LT
    delivery_cycle::varchar(6) as delivery_cycle, -- 納入サイクル
    order_output_cls::varchar(1) as order_output_cls, -- 発注出力先区分
    in_wh_location_code::varchar(10) as in_wh_location_code, -- 集中倉庫所番地
    kanban_total_sheet_qty::varchar(3) as kanban_total_sheet_qty, -- かんばん総枚数
    order_point::varchar(11) as order_point, -- 発注点
    order_point_cm::varchar(2) as order_point_cm, -- 発注点(cm)
    scheme_supply_cls::varchar(1) as scheme_supply_cls, -- 工整書支給区分
    machine_number::varchar(8) as machine_number, -- 機番
    st_no::varchar(2) as st_no, -- ST-No
    upos_srl_num::varchar(7) as upos_srl_num, -- UPOS連番
    discharge_place::varchar(6) as discharge_place, -- 荷卸場
    spot_location_code::varchar(6) as spot_location_code, -- 現場所番地
    supply_dest_code::varchar(4) as supply_dest_code, -- 支給先コード
    cart_no::varchar(6) as cart_no, -- 台車No
    req_depart_name::varchar(8) as req_depart_name, -- 依頼部署名
    req_depart_code::varchar(5) as req_depart_code, -- 依頼部署コード
    spec::varchar(59) as spec, -- スペック
    item_name::varchar(15) as item_name, -- 品名
    nekase_cls::varchar(1) as nekase_cls, -- ねかせ区分
    divers_cls::varchar(1) as divers_cls, -- 転用区分
    transmission_yn_cls::varchar(1) as transmission_yn_cls, -- 伝送可否区分
    order_date::varchar(14) as order_date, -- 発注日
    order_date_truck::varchar(2) as order_date_truck, -- 発注日便
    delivery_date_chg_count::varchar(2) as delivery_date_chg_count, -- 納期変更回数
    latest_delivery_date::varchar(14) as latest_delivery_date, -- 最新納期
    latest_delivery_date_truck::varchar(2) as latest_delivery_date_truck, -- 納期(最新)便
    first_delivery_date::varchar(14) as first_delivery_date, -- 1回目納期
    first_delivery_date_truck::varchar(2) as first_delivery_date_truck, -- 1回目納期便
    second_delivery_date::varchar(14) as second_delivery_date, -- 2回目納期
    second_delivery_date_truck::varchar(2) as second_delivery_date_truck, -- 2回目納期便
    third_delivery_date::varchar(14) as third_delivery_date, -- 3回目納期
    third_delivery_date_truck::varchar(2) as third_delivery_date_truck, -- 3回目納期便
    actual_delivery_date::varchar(14) as actual_delivery_date, -- 納入年月日
    delivery_number::varchar(5) as delivery_number, -- 納入番号
    odr_can_date::varchar(14) as odr_can_date, -- 発注キャンセル年月日
    chg_date::varchar(14) as chg_date, -- 変更年月日
    can_chg_date::varchar(14) as can_chg_date, -- キャンセル変更年月日
    arrangement_cls::varchar(1) as arrangement_cls, -- 手配区分
    minimum_odr_quantity::varchar(11) as minimum_odr_quantity, -- 最少発注数
    inspect_wh::varchar(2) as inspect_wh, -- 検収倉庫
    packing::varchar(2) as packing, -- 荷姿
    packing_weight::varchar(9) as packing_weight, -- 荷姿重量
    packing_quantity::varchar(6) as packing_quantity, -- 荷姿数量
    small_large_qty_cls::varchar(1) as small_large_qty_cls, -- 少多区分
    reserve_item_no::varchar(10) as reserve_item_no, -- 引当部品品番
    step::varchar(6) as step, -- 工程
    b_l_line::varchar(4) as b_l_line, -- B/Lライン
    base_metal_arrangement_no::varchar(12) as base_metal_arrangement_no, -- 母材手配連番
    spls_mtl_mmt_no::varchar(12) as spls_mtl_mmt_no, -- 余剰材管理No
    req_date::varchar(14) as req_date, -- 依頼年月日
    wh_processing_date::varchar(14) as wh_processing_date, -- 倉庫処理年月日
    office_date::varchar(14) as office_date, -- 事務所処理年月日
    procurement_decision_date::varchar(14) as procurement_decision_date, -- 調達決裁年月日
    furnish_qty_per_machine_no::varchar(3) as furnish_qty_per_machine_no, -- 取付数/機番・台
    actual_delivery_date_truck::varchar(2) as actual_delivery_date_truck, -- 納入年月日便
    rep_order::varchar(15) as rep_order, -- 修理オーダー
    supplier_name::varchar(8) as supplier_name, -- 仕入先名称
    maker_name::varchar(8) as maker_name, -- 製造メーカー名称
    kanban_destination_name::varchar(16) as kanban_destination_name, -- かんばん行先名称
    entry_cls::varchar(1) as entry_cls, -- 号口区分
    global_id::varchar(10) as global_id, -- グローバルID
    pre_study_no::varchar(10) as pre_study_no, -- 事前検討No
    color_dif_application::varchar(1) as color_dif_application, -- 色違い製品申請
    supplier_meeting_date::varchar(14) as supplier_meeting_date, -- 仕入先打合せ年月日
    rep_burden_depart::varchar(5) as rep_burden_depart, -- 修理負担部署
    dunning_cls::varchar(1) as dunning_cls, -- 督促区分
    dunning_cls_update_reason::varchar(1) as dunning_cls_update_reason, -- 督促区分更新理由
    delivery_delay_dunning::varchar(14) as delivery_delay_dunning, -- 納期遅れ督促日
    delat_reason::varchar(90) as delat_reason, -- 遅れ理由
    delivery_delay_count::varchar(2) as delivery_delay_count, -- 納期遅れ回数
    toyota_note::varchar(30) as toyota_note, -- トヨタ備考
    preferred_delivery_date::varchar(14) as preferred_delivery_date, -- 希望納期
    desired_delivery_req_date::varchar(14) as desired_delivery_req_date, -- 希望納期依頼年月日
    delivery_chg_dept_code::varchar(5) as delivery_chg_dept_code, -- 納期変更(部署コード)
    delivery_chg_update::varchar(14) as delivery_chg_update, -- 納期変更(更新日時)
    kanban_odr_dept_code::varchar(5) as kanban_odr_dept_code, -- かんばん発注者(部署コード)
    kanban_odr_update::varchar(14) as kanban_odr_update, -- かんばん発注者(更新日時)
    accepted_dept_code::varchar(5) as accepted_dept_code, -- 検収(部署コード)
    accepted_update_dttm::varchar(14) as accepted_update_dttm, -- 検収(更新日時)
    odr_can_dept_code::varchar(5) as odr_can_dept_code, -- 発注キャンセル(部署コード)
    odr_can_reason::varchar(60) as odr_can_reason, -- 発注キャンセル理由
    form_no::varchar(4) as form_no, -- 帳票No
    delivery_date::varchar(14) as delivery_date, -- 納期
    provisional_unit_price::varchar(12) as provisional_unit_price, -- 仮単価
    prov_unit_price_due_date::varchar(14) as prov_unit_price_due_date, -- 仮単価決定期限
    provisional_amount::varchar(12) as provisional_amount, -- 仮金額
    provision_amnt_reason_proc::varchar(150) as provision_amnt_reason_proc, -- 仮金額理由(調達)
    purchase_unit_price::varchar(12) as purchase_unit_price, -- 購入単価
    purchase_amount::varchar(12) as purchase_amount, -- 購入金額
    currency_code::varchar(3) as currency_code, -- 通貨コード
    accounts_payable_flag::varchar(1) as accounts_payable_flag, -- 買掛照合フラグ
    delivery_delay_days::varchar(3) as delivery_delay_days, -- 納期遅れ日数
    standard_delivery_date::varchar(14) as standard_delivery_date, -- 標準納期
    reodr_conf::varchar(1) as reodr_conf, -- 受注確認
    shipping_instructions::varchar(1) as shipping_instructions, -- 出荷指示
    rep_item_take_back::varchar(14) as rep_item_take_back, -- 修理品引取予定日
    rep_item_take_back_place::varchar(2) as rep_item_take_back_place, -- 修理品引取場所
    rep_item_take_back_delivery::varchar(14) as rep_item_take_back_delivery, -- 修理納期
    rep_item_take_back_qty::varchar(5) as rep_item_take_back_qty, -- 修理数量
    repairable_flag::varchar(1) as repairable_flag, -- 修理可否
    repairable_decision_result::varchar(1) as repairable_decision_result, -- 修理可否判定結果
    rep_processing::varchar(1) as rep_processing, -- 修理状況
    rep_contents::varchar(80) as rep_contents, -- 修理内容（通常修理） 
    estimate_rep_amount::varchar(10) as estimate_rep_amount, -- 推定修理金額
    in_house_rep_status::varchar(1) as in_house_rep_status, -- 内製修理ステータス
    odr_chg_type::varchar(1) as odr_chg_type, -- 発注変更種別
    odr_chg_status::varchar(1) as odr_chg_status, -- 発注変更ステータス
    odr_comp_mail_necessity_cls::varchar(1) as odr_comp_mail_necessity_cls, -- 発注完了お知らせメール要否
    deli_comp_mail_necessity_cls::varchar(1) as deli_comp_mail_necessity_cls, -- 納入完了お知らせメール要否
    delivery_location_code::varchar(3) as delivery_location_code, -- 納入先ロケーション
    tank_no::varchar(3) as tank_no, -- タンクNo
    wh_issue_flag::varchar(1) as wh_issue_flag, -- 自倉庫発行フラグ
    emergency_proc_code::varchar(2) as emergency_proc_code, -- 緊急時調達係コード
    emergency_proc_rp_code::varchar(1) as emergency_proc_rp_code, -- 緊急時調達担当コード
    recm_disagreement_reason::varchar(2) as recm_disagreement_reason, -- 推奨不一致理由
    recm_disagree_reason_note::varchar(30) as recm_disagree_reason_note, -- 推奨不一致理由記述
    maker_disagreement_reason::varchar(2) as maker_disagreement_reason, -- 商社メーカー不一致理由
    kanban_print_date::varchar(14) as kanban_print_date, -- かんばん印刷日
    if_created_date::varchar(14) as if_created_date, -- IF作成日
    office_contact_code::varchar(2) as office_contact_code, -- 事務所担当者コード
    measure_delivery1::varchar(11) as measure_delivery1, -- 計量品納入数量1
    measure_delivery2::varchar(11) as measure_delivery2, -- 計量品納入数量2
    measure_delivery3::varchar(11) as measure_delivery3, -- 計量品納入数量3
    measure_delivery4::varchar(11) as measure_delivery4, -- 計量品納入数量4
    measure_delivery5::varchar(11) as measure_delivery5, -- 計量品納入数量5
    rep_pattern::varchar(1) as rep_pattern, -- 修理パターン
    rep_pattern_before::varchar(1) as rep_pattern_before, -- 修理パターン_変更前
    rep_spec_responce_user::varchar(15) as rep_spec_responce_user, -- 修理仕様回答者
    csv_output_date::varchar(14) as csv_output_date, -- CSV出力日
    supplier_remarks::varchar(80) as supplier_remarks, -- 仕入先備考
    to_address_sup::varchar(4) as to_address_sup, -- 宛先アドレス(調達)
    to_sub_address_sup::varchar(3) as to_sub_address_sup, -- 宛先サブアドレス(調達)
    process_cls_sup::varchar(1) as process_cls_sup, -- 取引区分(調達)
    to_address_proc::varchar(4) as to_address_proc, -- 宛先アドレス(統括)
    to_sub_address_proc::varchar(3) as to_sub_address_proc, -- 宛先サブアドレス(統括)
    process_cls_proc::varchar(1) as process_cls_proc, -- 取引区分(統括)
    tns_date::varchar(14) as tns_date, -- TNS処理日時
    spls_arrange_order_srl_num::varchar(6) as spls_arrange_order_srl_num, -- 余剰関連手配連番
    fixed_amount_unit_price::varchar(12) as fixed_amount_unit_price, -- 定額単価
    actual_no1::varchar(20) as actual_no1, -- 現品No.1
    actual_no2::varchar(20) as actual_no2, -- 現品No.2
    actual_no3::varchar(20) as actual_no3, -- 現品No.3
    actual_no4::varchar(20) as actual_no4, -- 現品No.4
    actual_no5::varchar(20) as actual_no5, -- 現品No.5
    on_hold_memo_status::varchar(1) as on_hold_memo_status, -- 引取保留メモ出力ステータス
    tool_no::varchar(24) as tool_no, -- ツールNo
    upper_limit_existing::varchar(1) as upper_limit_existing, -- 上限指定有無
    upper_limit_price::varchar(7) as upper_limit_price, -- 上限金額(%)
    add_cost_existing::varchar(1) as add_cost_existing, -- 追加費用発生有無
    initial_order_qty::varchar(9) as initial_order_qty, -- 初回発注数量
    ih_make_outside_rep_cls::varchar(1) as ih_make_outside_rep_cls, -- 内製外注修理区分
    use_transfer_flag::varchar(1) as use_transfer_flag, -- 活用品振替フラグ
    tool_sys_sent_flag::varchar(1) as tool_sys_sent_flag, -- 工具システム連携済みフラグ
    object_version_number::varchar(9) as object_version_number, -- Object Version Number
    creation_date::varchar(14) as creation_date, -- 作成日時
    last_update_date::varchar(14) as last_update_date, -- 最終更新日時
    request_id::varchar(15) as request_id, -- 要求ID
    program_application_id::varchar(15) as program_application_id, -- コンカレント・プログラム・アプリケーションID
    program_id::varchar(15) as program_id, -- コンカレント・プログラムID
    program_update_date::varchar(14) as program_update_date, -- プログラム更新日時
    org_id::varchar(15) as org_id, -- 営業単位ID
    delivery_wh::varchar(2) as delivery_wh, -- 納入倉庫
    rep_can_date::varchar(14) as rep_can_date, -- 修理依頼キャンセル日
    return_quantity::varchar(11) as return_quantity, -- 返却数量
    repair_quantity::varchar(11) as repair_quantity, -- 修理可能数量
    rqe_from_kanban_cls::varchar(1) as rqe_from_kanban_cls, -- 依頼元かんばん新古区分
    kanban_issued_place_cls::varchar(1) as kanban_issued_place_cls, -- かんばん発行場所
    init_fixed_amount_unit_price::varchar(12) as init_fixed_amount_unit_price, -- 発注時定額単価
    measure_delivery6::varchar(11) as measure_delivery6, -- 計量品納入数量6
    measure_delivery7::varchar(11) as measure_delivery7, -- 計量品納入数量7
    measure_delivery8::varchar(11) as measure_delivery8, -- 計量品納入数量8
    measure_delivery9::varchar(11) as measure_delivery9, -- 計量品納入数量9
    measure_delivery10::varchar(11) as measure_delivery10, -- 計量品納入数量10
    actual_no6::varchar(20) as actual_no6, -- 現品No.6
    actual_no7::varchar(20) as actual_no7, -- 現品No.7
    actual_no8::varchar(20) as actual_no8, -- 現品No.8
    actual_no9::varchar(20) as actual_no9, -- 現品No.9
    actual_no10::varchar(20) as actual_no10, -- 現品No.10
    insp_ticket_issue_flag::varchar(1) as insp_ticket_issue_flag, -- 検収チケット発行フラグ
    reserve_odr_emergency_flag::varchar(1) as reserve_odr_emergency_flag, -- 引当発注緊急フラグ
    rep_pattern_supplier_answer::varchar(1) as rep_pattern_supplier_answer, -- 修理パターン（仕入先回答）
    po_line_id::varchar(15) as po_line_id, -- 購入単価明細ID
    ldts -- B層取込日時
  from {{source('manufacturing_db_public', 'raw_stg_hachuhuka')}}
)
select * from stg_hachuhuka_maps_view