with
    stg_hinban_hikiate_koumusms as (select * from {{ ref('stg_hinban_hikiate_koumusms') }}), --品番引当
    stg_syasyu_tmc_sms as (select distinct syasyu from {{ ref('stg_syasyu_tmc_sms') }}) --車種(トヨタ車種限定)

select
    a.jigyoutaicd::varchar(2) as jigyoutaicd, --事業体コード
    a.kouku::varchar(1) as kouku, --工区
    a.renban::varchar(1) as renban, --連番
    a.syasyu::varchar(4) as syasyu, --車種コード
    a.siyoubui::varchar(10) as siyoubui, --使用部位
    a.oyahin::varchar(10) as oyahin, --親品番／使用部位／ＢＬＫ
    a.gc::varchar(2) as gc, --グループコード
    a.kohin::varchar(10) as kohin, --子品番／使用部位／ＢＬＫ
    a.ruibetu::varchar(2) as ruibetu, --類別
    a.smskosu::varchar(3) as smskosu, --ＳＭＳ使用個数
    a.psmskosu::varchar(3) as psmskosu, --Ｐ－ＳＭＳ使用個数
    a.hikikosu::varchar(3) as hikikosu, --引当個数
    a.sentaku::varchar(2) as sentaku, --選択符号
    a.com11umukbn::varchar(1) as com11umukbn, --11コメント有無区分
    a.com15umukbn::varchar(1) as com15umukbn, --15コメント有無区分
    a.com16umukbn::varchar(1) as com16umukbn, --16コメント有無区分
    a.com18umukbn::varchar(1) as com18umukbn, --18コメント有無区分
    a.taisyogaikbn::varchar(1) as taisyogaikbn, --対象外区分
    a.ktchk::varchar(1) as ktchk, --工程チェック
    a.kanrikt::varchar(6) as kanrikt, --管理工程
    a.ktkigo::varchar(2) as ktkigo, --工程記号
    a.jikt01::varchar(6) as jikt01, --自工程工程符号１
    a.jikt02::varchar(6) as jikt02, --自工程工程符号２
    a.jikt03::varchar(6) as jikt03, --自工程工程符号３
    a.jikt04::varchar(6) as jikt04, --自工程工程符号４
    a.jikt05::varchar(6) as jikt05, --自工程工程符号５
    a.jikt06::varchar(6) as jikt06, --自工程工程符号６
    a.jikt07::varchar(6) as jikt07, --自工程工程符号７
    a.jikt08::varchar(6) as jikt08, --自工程工程符号８
    a.jikt09::varchar(6) as jikt09, --自工程工程符号９
    a.jikt10::varchar(6) as jikt10, --自工程工程符号１０
    a.jikt11::varchar(6) as jikt11, --自工程工程符号１１
    a.jikt12::varchar(6) as jikt12, --自工程工程符号１２
    a.jikt13::varchar(6) as jikt13, --自工程工程符号１３
    a.jikt14::varchar(6) as jikt14, --自工程工程符号１４
    a.oyakt::varchar(6) as oyakt, --親工程工程符号
    a.seppenk::varchar(10) as seppenk, --設変№カラ
    a.seppenm::varchar(10) as seppenm, --設変№マデ
    a.shinkyu::varchar(4) as shinkyu, --新旧区分
    a.tck::varchar(8) as tck, --工場Ｔ／Ｃカラ
    a.tcm::varchar(8) as tcm, --工場Ｔ／Ｃマデ
    a.naigaikbn::varchar(1) as naigaikbn, --内外区分
    a.tehaishogokey::varchar(6) as tehaishogokey, --手配照合キー
    a.idline::varchar(5) as idline, --ｱｲﾃﾞﾝﾄﾗｲﾝ/LOT符号
    a.unitkbn::varchar(1) as unitkbn, --ユニット区分
    a.nisugata::varchar(1) as nisugata, --荷姿
    a.hkbn::varchar(1) as hkbn, --比率条件区分
    a.hkosu::varchar(3) as hkosu, --比率条件比率／個数
    a.dkbn::varchar(1) as dkbn, --代表品番区分
    a.dhinban::varchar(10) as dhinban, --代表品番品番
    a.druibetu::varchar(2) as druibetu, --代表品番類別
    a.dkosu::varchar(3) as dkosu, --代表品番個数
    a.com::varchar(20) as com, --工場コメント
    a.oderkbn::varchar(1) as oderkbn, --オーダー区分
    a.shimukecd::varchar(3) as shimukecd, --仕向地ｺｰﾄﾞ
    a.shimukekouku::varchar(1) as shimukekouku, --現地工区
    a.togosyasyu::varchar(4) as togosyasyu, --統合車種ｺｰﾄﾞ
    a.konpoukouku::varchar(1) as konpoukouku, --梱包工区
    a.setblukkbn::varchar(1) as setblukkbn, --セット／バルク区分
    a.sentakuumuopm::varchar(1) as sentakuumuopm, --選択符号(OPM)有無
    a.multisspkbn::varchar(1) as multisspkbn, --ﾏﾙﾁｿｰｽSSP区分
    a.jyohomotokbn::varchar(1) as jyohomotokbn, --情報元区分
    a.hosenyouflg::varchar(1) as hosenyouflg, --補給専用ＦＬＧ
    a.hosiyoubui::varchar(10) as hosiyoubui, --所番地
    a.seiyakuumukbn::varchar(1) as seiyakuumukbn, --制約条件有無区分
    a.tyofuku::varchar(10) as tyofuku, --重複記載
    a.blkcd::varchar(10) as blkcd, --BLKｺｰﾄﾞ
    a.unitcd::varchar(4) as unitcd, --ﾕﾆｯﾄｺｰﾄﾞ
    a.torokujunk::varchar(9) as torokujunk, --登録/生認順カラ
    a.torokujunopmk::varchar(9) as torokujunopmk, --登録/生認順ｶﾗ(海生)
    a.torokujunm::varchar(9) as torokujunm, --登録/生認順マデ
    a.torokujunopmm::varchar(9) as torokujunopmm, --登録/生認順ﾏﾃﾞ(海生)
    a.sakuseitime::varchar(16) as sakuseitime, --作成日時
    a.kousintime::varchar(16) as kousintime, --更新日時
    a.ldts::timestamp_ntz as ldts --B層取込日時
from stg_hinban_hikiate_koumusms a
inner join stg_syasyu_tmc_sms b
    on trim(a.syasyu) = trim(b.syasyu)