id: job_build_dm_kousei_plantjiseki_kata
namespace: kestra_dbt_project.proj-job-area35

labels:
  error: default_failed
  dbt: build

retry:
  behavior: CREATE_NEW_EXECUTION # or RETRY_FAILED_TASK 
  type: exponential
  interval: PT5S
  maxAttempts: 7
  maxInterval: PT720S
  delayFactor: 30

# 手動実行時に指定できるdbtオプション
inputs:
  - id: dbt_options
    type: SELECT
    displayName: Choose dbt options
    values:
      - --full-refresh
    required: false
    allowCustomValue: true

tasks:
  - id: clone_dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    commands:
      - dbt build
        --select +dm_kousei_plantjiseki_kata
        --vars '{"DBT_JOB_NAME":"_dm_kousei_plantjiseki_kata"}'

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "00 12 * * *"
    timezone: Asia/Tokyo

# エラーログを出力
errors:
  - id: error_log
    type: io.kestra.plugin.core.debug.Return
    format: "{{ errorLogs()[0]['message'] }}"

outputs: 
  - id: output_error_log
    type: STRING
    value: "{{ outputs.error_log.value ?? 'No message found.' }}"
  - id: output_state
    type: STRING
    value: "{{ tasks.clone_dbt_build.state ?? 'No state' }}"

# ログ出力
finally:
  - id: finally_log 
    type: io.kestra.plugin.core.log.Log
    message: 
      - "Git branch -> {{ namespace.GIT.BRANCH }}"
      - "dbt options -> {{ inputs.dbt_options ?? '' }}"
      
disabled: false