id: job_build_stg_mashotoroku
namespace: kestra_dbt_project.proj-job-rism-changeif

labels:
  error: default_failed
  dbt: build

tasks:
  - id: dbt

    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone

      - id: dbt_build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        commands:
          - dbt build
            --select +stg_mashotoroku
            --vars '{"DBT_JOB_NAME":"_stg_mashotoroku"}'
            --project-dir "{{ namespace.DBT.PROJ_DIR }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "45 10 * * 1,2,3,4,5"
    timezone: Asia/Tokyo

# エラーログを出力
errors:
  - id: error_log
    type: io.kestra.plugin.core.debug.Return
    format: "{{ errorLogs()[0]['message'] }}"

outputs: 
  - id: output_error_log
    type: STRING
    value: "{{ outputs.error_log.value ?? 'No message found.' }}"

# ログ出力
finally:
  - id: finally_log 
    type: io.kestra.plugin.core.log.Log
    message: 
      - "Git branch -> {{ namespace.GIT.BRANCH }}"
      
disabled: false