{{ config(
      materialized='view'
   )
}}

with stg_hachuirai_maps_view as (
  select
    odr_rqe_id::varchar(15) as odr_rqe_id, -- 発注依頼_ID
    arrangement_serial_no::varchar(6) as arrangement_serial_no, -- 手配連番
    item_name::varchar(15) as item_name, -- 品名
    spec::varchar(59) as spec, -- スペック
    office_date::varchar(14) as office_date, -- 事務所処理年月日
    y_item_no::varchar(10) as y_item_no, -- Y品番
    req_depart_code::varchar(5) as req_depart_code, -- 依頼部署コード
    req_depart_decision_date::varchar(14) as req_depart_decision_date, -- 依頼部署決裁年月日
    preferred_delivery_date::varchar(14) as preferred_delivery_date, -- 希望納期
    preferred_supplier_code::varchar(4) as preferred_supplier_code, -- 希望仕入先コード
    preferred_supplier_name::varchar(8) as preferred_supplier_name, -- 希望仕入先名称
    preferred_maker_code::varchar(4) as preferred_maker_code, -- 希望(製造)メーカー
    preferred_maker_name::varchar(8) as preferred_maker_name, -- 希望(製造)メーカー名称
    procurement_decision_date::varchar(14) as procurement_decision_date, -- 調達決裁年月日
    procurement_approval_date::varchar(14) as procurement_approval_date, -- 調達承認年月日
    req_depart_name::varchar(8) as req_depart_name, -- 依頼部署名
    wh_code::varchar(2) as wh_code, -- 倉庫コード
    office_contact_code::varchar(2) as office_contact_code, -- 事務所担当者コード
    office_contact_name::varchar(10) as office_contact_name, -- 事務所担当者名
    procurement_group_code::varchar(2) as procurement_group_code, -- 調達係コード
    procurement_personnel_code::varchar(1) as procurement_personnel_code, -- 調達担当コード
    sha2('prc_approver_emp_code', 256) as prc_approver_emp_code, -- 調達決裁者従業員コード
    req_date::varchar(14) as req_date, -- 依頼年月日
    estimated_total_amount::varchar(8) as estimated_total_amount, -- 総額(推定)
    order_quantity::varchar(11) as order_quantity, -- 発注数量
    order_qty_uom::varchar(2) as order_qty_uom, -- 発注数量単位
    order_qty_uom_name::varchar(4) as order_qty_uom_name, -- 発注数量単位名称
    delivery_date::varchar(14) as delivery_date, -- 納期
    sha2('req_dep_approver_emp_code', 256) as req_dep_approver_emp_code, -- 依頼部署決裁者従業員コード
    procurement_cls::varchar(1) as procurement_cls, -- 調達区分
    procurement_contents::varchar(8) as procurement_contents, -- 調達内容
    item_cls::varchar(12) as item_cls, -- 品目分類
    item_content::varchar(18) as item_content, -- 品目内容
    transfer_group_code::varchar(2) as transfer_group_code, -- 転送元係コード
    transfer_group_rp_code::varchar(1) as transfer_group_rp_code, -- 転送元担当者コード
    wh_processing_date::varchar(14) as wh_processing_date, -- 倉庫処理年月日
    stock_req_cls::varchar(1) as stock_req_cls, -- 在庫依頼進捗区分
    stock_req_exam_flag::varchar(1) as stock_req_exam_flag, -- 在庫依頼検討フラグ
    stock_req_exam_contents::varchar(6) as stock_req_exam_contents, -- 在庫依頼検討内容
    reason_for_return::varchar(2) as reason_for_return, -- 返却理由
    reason_for_return_contents::varchar(50) as reason_for_return_contents, -- 返却理由内容
    return_date::varchar(14) as return_date, -- 返却年月日
    prc_reason_for_re_cls::varchar(2) as prc_reason_for_re_cls, -- 調達返却理由区分
    prc_reason_return_contents::varchar(20) as prc_reason_return_contents, -- 調達返却理由内容
    prc_return_date::varchar(14) as prc_return_date, -- 調達返却年月日
    req_data_abls_rep_cls::varchar(1) as req_data_abls_rep_cls, -- 依頼データ廃止修正区分
    study_out_contents::varchar(1) as study_out_contents, -- 検討書出力状況内容
    actual_goods_out_cls::varchar(1) as actual_goods_out_cls, -- 現品票出力区分
    req_necessity_cls::varchar(1) as req_necessity_cls, -- 依頼書作成要否区分
    reserve_delivery_date::varchar(14) as reserve_delivery_date, -- 引当納期
    minimum_odr_quantity::varchar(11) as minimum_odr_quantity, -- 最少発注数
    use_purpose::varchar(2) as use_purpose, -- 使用目的
    use_purpose_note::varchar(30) as use_purpose_note, -- 使用目的記述
    factory_code::varchar(1) as factory_code, -- 工場コード
    factory_name::varchar(3) as factory_name, -- 工場名
    supplier_meeting::varchar(1) as supplier_meeting, -- 仕入先事前打合
    equipment_maker::varchar(8) as equipment_maker, -- 設備メーカー
    sha2('req_code', 256) as req_code, -- 依頼者コード
    poisonous_mtls_cls::varchar(1) as poisonous_mtls_cls, -- 毒劇物区分
    req_dep_mgr_decision_conts::varchar(1) as req_dep_mgr_decision_conts, -- 依頼部署部長決裁内容
    packing::varchar(2) as packing, -- 荷姿
    packing_name::varchar(6) as packing_name, -- 荷姿名称
    packing_weight::varchar(9) as packing_weight, -- 荷姿重量
    packing_quantity::varchar(6) as packing_quantity, -- 荷姿数量
    remarks::varchar(30) as remarks, -- 備考
    provisional_amount_reason::varchar(1) as provisional_amount_reason, -- 仮金額理由
    provisional_amt_reason_cont::varchar(11) as provisional_amt_reason_cont, -- 仮金額理由内容
    small_large_qty_cls::varchar(1) as small_large_qty_cls, -- 少多区分
    small_large_qty_content::varchar(1) as small_large_qty_content, -- 少多内容
    sheet_quantity::varchar(5) as sheet_quantity, -- シート数・本数
    sheet_number_unit_cls::varchar(1) as sheet_number_unit_cls, -- シート数・本数単位区分
    sheet_quantity_unit::varchar(1) as sheet_quantity_unit, -- シート数・本数単位
    gi_depart_code::varchar(5) as gi_depart_code, -- 出庫部署コード
    gi_depart::varchar(8) as gi_depart, -- 出庫部署名
    supply_dest_code::varchar(4) as supply_dest_code, -- 支給先コード
    supply_dest_name::varchar(8) as supply_dest_name, -- 支給先名称
    burden_depart_code::varchar(5) as burden_depart_code, -- 負担部署コード
    burden_depart_name::varchar(8) as burden_depart_name, -- 負担部署名
    gi_order::varchar(15) as gi_order, -- 出庫オーダー
    pro_tech_appr_necessity_cls::varchar(1) as pro_tech_appr_necessity_cls, -- 生技決裁要否区分
    pro_tech_appr_necessity_cont::varchar(1) as pro_tech_appr_necessity_cont, -- 生技決裁要否内容
    outside_repair_yn_cls::varchar(1) as outside_repair_yn_cls, -- 外注修理可否区分
    outside_repair_yn_contents::varchar(2) as outside_repair_yn_contents, -- 外注修理可否内容
    switch_name::varchar(24) as switch_name, -- 切替名称
    processing_item_name::varchar(24) as processing_item_name, -- 加工品名
    quantity_per_times::varchar(5) as quantity_per_times, -- 使用量/回
    furnish_qty_per_machine_no::varchar(3) as furnish_qty_per_machine_no, -- 取付数/機番・台
    delivery_lt::varchar(3) as delivery_lt, -- 手配LT
    delivery_cycle::varchar(6) as delivery_cycle, -- 納入サイクル
    un_total_cls::varchar(1) as un_total_cls, -- 非集計区分
    weight_necessity_cls::varchar(1) as weight_necessity_cls, -- 計量要否区分
    necessity_content::varchar(1) as necessity_content, -- 計量要否内容
    decision_srl_num::varchar(6) as decision_srl_num, -- 決裁連番
    transfer_reason_contents::varchar(20) as transfer_reason_contents, -- 転送理由内容
    multiple_companies_order_cls::varchar(1) as multiple_companies_order_cls, -- 複社発注区分
    mul_cos_contents::varchar(5) as mul_cos_contents, -- 複社発注内容
    weight_cv_cls::varchar(1) as weight_cv_cls, -- 重量変換区分
    weight_chg_contents::varchar(3) as weight_chg_contents, -- 重量変換内容
    z_item_cls::varchar(1) as z_item_cls, -- Z品区分
    z_item_content::varchar(3) as z_item_content, -- Z品内容
    product_mfg_cls::varchar(1) as product_mfg_cls, -- 製品製造区分
    product_mfg_cls_contents::varchar(3) as product_mfg_cls_contents, -- 製品製造区分内容
    wh_code_intensive_in::varchar(2) as wh_code_intensive_in, -- 集中在庫倉庫
    standard_weight::varchar(5) as standard_weight, -- 基準重量
    req_decision_input_date::varchar(14) as req_decision_input_date, -- 依頼書決裁入力年月日
    req_decision_input_rp_name::varchar(10) as req_decision_input_rp_name, -- 依頼書決裁入力担当者名
    req_creation_date::varchar(14) as req_creation_date, -- 依頼書作成年月日
    wh_rp_name::varchar(10) as wh_rp_name, -- 倉庫担当者名
    type_code::varchar(4) as type_code, -- 種別コード
    existing_cls::varchar(1) as existing_cls, -- 有無区分
    existing_cls_content::varchar(4) as existing_cls_content, -- 有無内容
    delivery_note_sheet_qty::varchar(3) as delivery_note_sheet_qty, -- 納品書枚数
    arrangement_year_month_from::varchar(6) as arrangement_year_month_from, -- 手配年月カラ
    arrangement_yeras_to::varchar(6) as arrangement_yeras_to, -- 手配年月マデ
    reserve_item_no::varchar(10) as reserve_item_no, -- 引当部品品番
    step::varchar(6) as step, -- 工程
    b_l_line::varchar(4) as b_l_line, -- B/Lライン
    base_metal_arrangement_no::varchar(12) as base_metal_arrangement_no, -- 母材手配連番
    kanban_dest_name_sup::varchar(16) as kanban_dest_name_sup, -- かんばん行先名称_調達拠点
    arrangement_cls::varchar(1) as arrangement_cls, -- 手配区分
    arrangement_contents::varchar(4) as arrangement_contents, -- 手配内容
    spls_mtl_mmt_no::varchar(12) as spls_mtl_mmt_no, -- 余剰材管理No
    transfer_wh_from::varchar(2) as transfer_wh_from, -- 転送元倉庫
    req_wh_code::varchar(2) as req_wh_code, -- 依頼側倉庫コード
    divers_cls::varchar(1) as divers_cls, -- 転用区分
    kanban_reserve_contents::varchar(6) as kanban_reserve_contents, -- かんばん引当内容
    location_code::varchar(10) as location_code, -- 所番地
    kanban_sheet_qty::varchar(3) as kanban_sheet_qty, -- かんばん枚数
    order_qty_per_sheet::varchar(11) as order_qty_per_sheet, -- 発注数量/枚
    gi_post_no::varchar(3) as gi_post_no, -- 出庫ポストNo
    burden_post_no::varchar(3) as burden_post_no, -- 負担ポストNo
    discharge_place::varchar(6) as discharge_place, -- 荷卸場
    spot_location_code::varchar(6) as spot_location_code, -- 現場所番地
    scheme_no::varchar(7) as scheme_no, -- 工整書No
    office_kanban_gi_wh_code::varchar(2) as office_kanban_gi_wh_code, -- 社内かんばん出庫元倉庫
    tool_classification_code::varchar(1) as tool_classification_code, -- 工具種別コード
    importance_mmt_mtl::varchar(1) as importance_mmt_mtl, -- 重点管理資材
    notices::varchar(60) as notices, -- 特記事項
    entry_cls::varchar(1) as entry_cls, -- 号口区分
    supplier_contact_name::varchar(10) as supplier_contact_name, -- 仕入先担当者名
    wh_decision_sup_contact_name::varchar(10) as wh_decision_sup_contact_name, -- 倉庫決裁時仕入先担当者名
    supplier_contact_tel::varchar(13) as supplier_contact_tel, -- 仕入先担当者TEL
    wh_decision_sup_contact_tel::varchar(13) as wh_decision_sup_contact_tel, -- 倉庫決裁時仕入先担当者TEL
    global_id::varchar(10) as global_id, -- グローバルID
    pre_study_no::varchar(10) as pre_study_no, -- 事前検討No
    color_dif_application::varchar(1) as color_dif_application, -- 色違い製品申請
    supply_cls::varchar(1) as supply_cls, -- 支給区分
    office_remarks::varchar(30) as office_remarks, -- 事務所備考
    pe_remarks::varchar(30) as pe_remarks, -- PE部備考
    safety_remarks::varchar(30) as safety_remarks, -- 安推部備考
    permission_cls::varchar(1) as permission_cls, -- 許可制区分
    odr_remand_date::varchar(14) as odr_remand_date, -- 発注先決定差戻年月日
    supplier_answer_lt::varchar(3) as supplier_answer_lt, -- 仕入先回答LT
    urgent_order_reason::varchar(30) as urgent_order_reason, -- 緊急発注理由
    urgent_judgment_cls::varchar(1) as urgent_judgment_cls, -- 緊急判定区分
    req_dep_decision_due_date::varchar(14) as req_dep_decision_due_date, -- 依頼部署決裁期限
    office_decision_due_date::varchar(14) as office_decision_due_date, -- 事務所決裁期限
    subcontract_act_cls::varchar(1) as subcontract_act_cls, -- 下請法対象区分
    sha2('office_approver_emp_cd', 256) as office_approver_emp_cd, -- 事務所決裁者従業員コード
    delivery_lt_cal::varchar(3) as delivery_lt_cal, -- 納LT(計算用)
    unit_price_decision_due_date::varchar(14) as unit_price_decision_due_date, -- 単価決定期限
    provisional_unit_price::varchar(12) as provisional_unit_price, -- 仮単価
    prov_unit_price_due_date::varchar(14) as prov_unit_price_due_date, -- 仮単価決定期限
    provisional_amount::varchar(12) as provisional_amount, -- 仮金額
    provision_amnt_reason_proc::varchar(100) as provision_amnt_reason_proc, -- 仮金額理由(調達)
    purchase_unit_price::varchar(12) as purchase_unit_price, -- 購入単価
    purchase_amount::varchar(12) as purchase_amount, -- 購入金額
    vote_cls::varchar(1) as vote_cls, -- 値決区分
    quotation_issue_flag::varchar(1) as quotation_issue_flag, -- 見積書発行フラグ
    procurement_delivery_date::varchar(14) as procurement_delivery_date, -- 調達設定納期
    sheet_number_weight::varchar(8) as sheet_number_weight, -- シート数・本数重量
    internal_capacity::varchar(20) as internal_capacity, -- 内容量(入数)
    st_no::varchar(2) as st_no, -- ST-No
    kanban_destination_no_proc::varchar(3) as kanban_destination_no_proc, -- かんばん行先No_統括拠点
    kanban_dest_name_proc::varchar(16) as kanban_dest_name_proc, -- かんばん行先名称_統括拠点
    gi_wh_code::varchar(2) as gi_wh_code, -- 出庫倉庫コード
    supplier_code::varchar(4) as supplier_code, -- 仕入先コード
    maker_code::varchar(4) as maker_code, -- メーカーコード
    control_key::varchar(1) as control_key, -- コントロールキー
    card_identification_cls::varchar(1) as card_identification_cls, -- カード識別区分
    new_date::varchar(14) as new_date, -- 新設年月日
    processing_time::varchar(6) as processing_time, -- 処理時間
    issue_type::varchar(1) as issue_type, -- 発行種類
    screen_id::varchar(3) as screen_id, -- 画面ID
    processing_no::varchar(1) as processing_no, -- 処理番号
    subject::varchar(1) as subject, -- 科目
    read_odr_cls::varchar(1) as read_odr_cls, -- 読取発注区分
    repair_supplier_code::varchar(4) as repair_supplier_code, -- 修理仕入先コード
    z_item_cls_card::varchar(1) as z_item_cls_card, -- Z品区分_カード
    new_used_cls::varchar(1) as new_used_cls, -- 新品中古区分
    order_quantity_summary::varchar(11) as order_quantity_summary, -- 発注数(サマリ)
    kanban_total_sheet_qty::varchar(3) as kanban_total_sheet_qty, -- かんばん総枚数
    kanban_sheet_qty_summary::varchar(3) as kanban_sheet_qty_summary, -- かんばん枚数(サマリ)
    entry_test_mtl_cls::varchar(1) as entry_test_mtl_cls, -- 号口テスト材区分
    coil_width::varchar(9) as coil_width, -- コイル幅
    new_repair_order_cls::varchar(1) as new_repair_order_cls, -- 新品修理発注区分
    order_output_cls::varchar(1) as order_output_cls, -- 発注出力先区分
    delivery_date_truck::varchar(2) as delivery_date_truck, -- 納期便
    machine_number::varchar(8) as machine_number, -- 機番
    toyota_note::varchar(30) as toyota_note, -- トヨタ備考
    requester_name::varchar(10) as requester_name, -- 依頼者名
    order_date::varchar(14) as order_date, -- 発注日
    order_date_truck::varchar(2) as order_date_truck, -- 発注日便
    fr_use_yn::varchar(1) as fr_use_yn, -- 部品取品活用区分
    in_house_make_item_cls::varchar(1) as in_house_make_item_cls, -- 内製製作品区分
    in_house_repair_item_cls::varchar(1) as in_house_repair_item_cls, -- 内製修理品区分
    kanban_destination_no_sup::varchar(3) as kanban_destination_no_sup, -- かんばん行先No_調達拠点
    supplier_post_no::varchar(5) as supplier_post_no, -- 仕入先ポストNo
    order_point::varchar(11) as order_point, -- 発注点
    cart_no::varchar(6) as cart_no, -- 台車No
    transmission_yn_cls::varchar(1) as transmission_yn_cls, -- 伝送可否区分
    supplier_odr_cls::varchar(1) as supplier_odr_cls, -- 仕入先発注区分
    form_no::varchar(4) as form_no, -- 帳票No
    poisonous_mtls_use_no::varchar(9) as poisonous_mtls_use_no, -- 毒劇物使用届出書No
    kanban_odr_name::varchar(10) as kanban_odr_name, -- かんばん発注(氏名)
    kanban_odr_dept_code::varchar(5) as kanban_odr_dept_code, -- かんばん発注者(部署コード)
    sha2('kanban_odr_emp_code', 256) as kanban_odr_emp_code, -- かんばん発注(従業員コード)
    kanban_odr_update::varchar(14) as kanban_odr_update, -- かんばん発注者(更新日時)
    identification_cls::varchar(2) as identification_cls, -- 識別区分
    on_hold_flag::varchar(1) as on_hold_flag, -- 保留対象フラグ
    odr_on_hold_date::varchar(14) as odr_on_hold_date, -- 発注保留年月日
    design_delivery_date_flag::varchar(1) as design_delivery_date_flag, -- 指定納期有無フラグ
    upos_srl_num::varchar(7) as upos_srl_num, -- UPOS連番
    remote_cls::varchar(1) as remote_cls, -- 遠隔地区分
    self_repairable_cls::varchar(1) as self_repairable_cls, -- 自社修理可否区分
    return_mark::varchar(2) as return_mark, -- 返却マーク
    no_slip_cls::varchar(1) as no_slip_cls, -- ノー伝区分
    issue_wh_code::varchar(2) as issue_wh_code, -- 発行倉庫コード
    unit_price_standard::varchar(2) as unit_price_standard, -- 単価基準
    subject_name::varchar(4) as subject_name, -- 科目名称
    supplier_name::varchar(8) as supplier_name, -- 仕入先名称
    maker_name::varchar(8) as maker_name, -- メーカー名称
    transfer_wh_to::varchar(2) as transfer_wh_to, -- 転送先倉庫
    reserve_odr_prog_cls::varchar(1) as reserve_odr_prog_cls, -- 引当発注進捗区分
    new_time::varchar(6) as new_time, -- 新設時間
    update_date::varchar(14) as update_date, -- 更新年月日
    odr_comp_mail_necessity_cls::varchar(1) as odr_comp_mail_necessity_cls, -- 発注完了お知らせメール要否
    deli_comp_mail_necessity_cls::varchar(1) as deli_comp_mail_necessity_cls, -- 納入完了お知らせメール要否
    delivery_location_code::varchar(3) as delivery_location_code, -- 納入先ロケーション
    tl_rep::varchar(1) as tl_rep, -- 工具修正品
    rep_y_item_no::varchar(10) as rep_y_item_no, -- 修正品Y品番
    new_y_item_no::varchar(10) as new_y_item_no, -- 新品Y品番
    office_decision_plan_date::varchar(14) as office_decision_plan_date, -- 社内決裁完了予定日
    req_nomal_delivery_date::varchar(14) as req_nomal_delivery_date, -- 依頼時標準納期
    wh_decision_nomal_dd::varchar(14) as wh_decision_nomal_dd, -- 倉庫決裁時標準納期
    office_decision_nomal_dd::varchar(14) as office_decision_nomal_dd, -- 事務所決裁時標準納期
    tank_no::varchar(3) as tank_no, -- タンクNo
    add_reserved_machine_no::varchar(450) as add_reserved_machine_no, -- 追加機番
    shop_code::varchar(1) as shop_code, -- ショップコード
    equipment_axis_1::varchar(3) as equipment_axis_1, -- 設備軸1
    equipment_axis_2::varchar(3) as equipment_axis_2, -- 設備軸2
    preliminary_axis::varchar(3) as preliminary_axis, -- 予備軸
    machine_no_mmt_unneeded_cls::varchar(1) as machine_no_mmt_unneeded_cls, -- 機番管理不要区分
    annual_order_count::varchar(5) as annual_order_count, -- 年間発注回数
    current_use_number::varchar(10) as current_use_number, -- 現行使用品番
    repair_regist_need_flag::varchar(1) as repair_regist_need_flag, -- 修理登録要否
    hazardous_mtl_cls::varchar(1) as hazardous_mtl_cls, -- 危険物区分
    inexpensive_item_cls::varchar(2) as inexpensive_item_cls, -- 安価品区分
    recycle_item_cls::varchar(1) as recycle_item_cls, -- 再生品区分
    wh_issue_flag::varchar(1) as wh_issue_flag, -- 自倉庫発行フラグ
    storage_cls::varchar(1) as storage_cls, -- 保管区分
    storage_details_condition::varchar(100) as storage_details_condition, -- 保管詳細条件
    cost_reduction_act_deadline::varchar(14) as cost_reduction_act_deadline, -- 原低活動不可期限
    base_metal_item_no::varchar(54) as base_metal_item_no, -- 母材品番
    emergency_proc_code::varchar(2) as emergency_proc_code, -- 緊急時調達係コード
    emergency_proc_rp_code::varchar(1) as emergency_proc_rp_code, -- 緊急時調達担当コード
    recm_disagreement_reason::varchar(2) as recm_disagreement_reason, -- 推奨不一致理由
    recm_disagree_reason_note::varchar(30) as recm_disagree_reason_note, -- 推奨不一致理由記述
    maker_disagreement_reason::varchar(2) as maker_disagreement_reason, -- 商社メーカー不一致理由
    new_item_no_reason::varchar(2) as new_item_no_reason, -- 品番新設理由
    sha2('return_approver_emp_code', 256) as return_approver_emp_code, -- 返却決裁者従業員コード
    proc_pre_adjust::varchar(1) as proc_pre_adjust, -- 調達事前調整済
    requester_tel_extension::varchar(13) as requester_tel_extension, -- 依頼者TEL(内線)
    requester_tel_external::varchar(13) as requester_tel_external, -- 依頼者TEL(外線)
    office_rp_extension::varchar(13) as office_rp_extension, -- 事務所担当者(内線)
    office_rp_outside_line::varchar(13) as office_rp_outside_line, -- 事務所担当者(外線)
    spec_unneeded_char_del::varchar(59) as spec_unneeded_char_del, -- スペック(不要文字削除)
    shortening_spec::varchar(59) as shortening_spec, -- 短縮スペック
    item_name_unneeded_char_del::varchar(15) as item_name_unneeded_char_del, -- 品名(不要文字削除)
    req_status::varchar(2) as req_status, -- 依頼ステータス
    wh_decision_reason::varchar(2) as wh_decision_reason, -- 倉庫決裁対象理由
    small_qty_use_item_mfg_lt::varchar(3) as small_qty_use_item_mfg_lt, -- 少使用品製造LT
    small_qty_use_item_log_lt::varchar(3) as small_qty_use_item_log_lt, -- 少使用品物流LT
    mtl_standard_unit_price::varchar(10) as mtl_standard_unit_price, -- 資材基準単価
    currency_code::varchar(3) as currency_code, -- 通貨コード
    new_supplier::varchar(4) as new_supplier, -- 新品仕入先
    upper_limit_existing::varchar(1) as upper_limit_existing, -- 上限指定有無
    upper_limit_price::varchar(7) as upper_limit_price, -- 上限金額(%)
    rep_burden_depart::varchar(5) as rep_burden_depart, -- 修理負担部署
    take_back_necessity_cls::varchar(1) as take_back_necessity_cls, -- 引取日回答要否
    take_back_place::varchar(2) as take_back_place, -- 引取場所
    take_back_req_exisitng::varchar(1) as take_back_req_exisitng, -- 引取依頼通知有無
    sha2('rep_req', 256) as rep_req, -- 修理依頼者
    rep_req_e_mail::varchar(248) as rep_req_e_mail, -- 修理依頼者メールアドレス
    tl_cls::varchar(4) as tl_cls, -- 工具分類_発注依頼
    gas_cylinder_mmt_cls::varchar(1) as gas_cylinder_mmt_cls, -- ガスボンベ管理区分
    estimated_unit_price::varchar(12) as estimated_unit_price, -- 単価(推定)
    on_hold_flag_status::varchar(1) as on_hold_flag_status, -- 保留ステータス
    office_column::varchar(30) as office_column, -- 事務所進捗欄
    mfg_days::varchar(3) as mfg_days, -- 製造日数
    odr_type::varchar(2) as odr_type, -- 発注種別
    can_item_no_abolishment::varchar(1) as can_item_no_abolishment, -- キャンセル時品番廃止
    delivery_date_reason::varchar(60) as delivery_date_reason, -- 納期指定理由
    decision_hold_date::varchar(14) as decision_hold_date, -- 決裁保留日
    sha2('decision_hold_user', 256) as decision_hold_user, -- 決裁保留者
    spls_arrange_order_srl_num::varchar(6) as spls_arrange_order_srl_num, -- 余剰関連手配連番
    spls_use_yn::varchar(1) as spls_use_yn, -- 余剰活用可否
    st_mtr_appricable_period_to::varchar(14) as st_mtr_appricable_period_to, -- 鋼材手配適用期間マデ
    rep_pattern::varchar(1) as rep_pattern, -- 修理パターン
    fixed_amount_unit_price::varchar(12) as fixed_amount_unit_price, -- 定額単価
    ih_make_outside_rep_cls::varchar(1) as ih_make_outside_rep_cls, -- 内製外注修理区分
    odr_group_id::varchar(15) as odr_group_id, -- 発注グループID
    decision_hold_reason::varchar(50) as decision_hold_reason, -- 決裁保留理由
    tool_no::varchar(24) as tool_no, -- ツールNo
    return_reason_contents_more::varchar(50) as return_reason_contents_more, -- 返却理由内容詳細
    transfer_reason_conts_more::varchar(50) as transfer_reason_conts_more, -- 転送理由内容詳細
    take_back_on_hold_group_cd::varchar(10) as take_back_on_hold_group_cd, -- 引取保留メモグループコード
    nekase_cls::varchar(1) as nekase_cls, -- ねかせ区分
    minimum_necessary_wt::varchar(5) as minimum_necessary_wt, -- 最低必要重量
    supplier_design_cls::varchar(1) as supplier_design_cls, -- 仕入先指定区分
    iron_test_mtl_loc_regist_yn::varchar(1) as iron_test_mtl_loc_regist_yn, -- 鉄テスト材所番地登録
    acceptance_delivery_note_no::varchar(5) as acceptance_delivery_note_no, -- 既受入品返却出庫票・納品書No
    supplier_meeting_date::varchar(14) as supplier_meeting_date, -- 仕入先打合せ年月日
    add_cost_existing::varchar(1) as add_cost_existing, -- 追加費用発生有無
    mil_code::varchar(3) as mil_code, -- ミルコード
    scheme_supply_cls::varchar(1) as scheme_supply_cls, -- 工整書支給区分
    old_arrangement_serial_no::varchar(12) as old_arrangement_serial_no, -- 旧手配連番
    location_code_not_iron_id::varchar(15) as location_code_not_iron_id, -- 所番地ID
    tool_management_cls::varchar(2) as tool_management_cls, -- 工具管理用区分
    delivery_wh::varchar(2) as delivery_wh, -- 納入倉庫
    repair_order_function::varchar(2) as repair_order_function, -- 修理発注機能
    ex_location_code_id::varchar(15) as ex_location_code_id, -- 交換品所番地ID
    ex_storage_shelf_id::varchar(15) as ex_storage_shelf_id, -- 交換品保管棚ID
    object_version_number::varchar(9) as object_version_number, -- Object Version Number
    sha2('created_by', 256) as created_by, -- 作成者
    created_user_name::varchar(30) as created_user_name, -- 作成者ユーザー名
    creation_date::varchar(14) as creation_date, -- 作成日時
    sha2('last_updated_by', 256) as last_updated_by, -- 最終更新者
    last_updated_user_name::varchar(30) as last_updated_user_name, -- 最終更新者ユーザー名
    last_update_date::varchar(14) as last_update_date, -- 最終更新日時
    sha2('last_update_login', 256) as last_update_login, -- 最終更新ログイン
    last_upd_login_user_name::varchar(30) as last_upd_login_user_name, -- 最終更新ログインユーザー名
    request_id::varchar(15) as request_id, -- 要求ID
    program_application_id::varchar(15) as program_application_id, -- コンカレント・プログラム・アプリケーションID
    program_id::varchar(15) as program_id, -- コンカレント・プログラムID
    program_update_date::varchar(14) as program_update_date, -- プログラム更新日時
    org_id::varchar(15) as org_id, -- 営業単位ID
    old_arrangement_branch_no::varchar(6) as old_arrangement_branch_no, -- 旧手配連番枝番
    transfer_office_contact_code::varchar(2) as transfer_office_contact_code, -- 転送元事務所担当者コード
    rqe_from_kanban_cls::varchar(1) as rqe_from_kanban_cls, -- 依頼元かんばん新古区分
    new_order_pullback_reason::varchar(1) as new_order_pullback_reason, -- 依頼引戻理由
    new_order_pullback_reason_more::varchar(60) as new_order_pullback_reason_more, -- 依頼引戻理由詳細
    delete_supplier_contact::varchar(10) as delete_supplier_contact, -- 取消調整時仕入先担当者
    delete_supplier_meeting_date::varchar(14) as delete_supplier_meeting_date, -- 取消時仕入先打合せ年月日
    preferred_maker_name_20::varchar(20) as preferred_maker_name_20, -- 希望(製造)メーカー名称（20）
    old_y_item_no::varchar(10) as old_y_item_no, -- 旧手配Y品番
    old_subinventory_code::varchar(2) as old_subinventory_code, -- 旧手配保管場所コード
    old_gi_bs_post_no::varchar(3) as old_gi_bs_post_no, -- 旧手配出庫ポストNo
    old_tank_no::varchar(3) as old_tank_no, -- 旧手配タンクNo
    old_new_repair_order_cls::varchar(1) as old_new_repair_order_cls, -- 旧手配新品修理発注区分
    old_procurement_cls::varchar(1) as old_procurement_cls, -- 旧手配調達区分
    supplier_confirmation_date::varchar(14) as supplier_confirmation_date, -- 仕入先確認日
    radio_law_report_necessity::varchar(1) as radio_law_report_necessity, -- 電波法届出要否
    reserve_odr_emergency_flag::varchar(1) as reserve_odr_emergency_flag, -- 引当発注緊急フラグ
    ldts -- B層取込日時
  from {{source('manufacturing_db_public', 'raw_stg_hachuirai')}}
)
select * from stg_hachuirai_maps_view