{{ config(
      materialized='view'
   )
}}

{% set source_table = source('manufacturing_db_public', 'raw_stg_sizainaiji') %}

with stg_sizainaiji_maps_view as (
  select
    mtl_mtl_rqi_id::varchar(15) as mtl_mtl_rqi_id, -- 資材内示ID
    year_month::varchar(6) as year_month, -- 年月
    creation_number::varchar(2) as creation_number, -- 作成回
    inventory_item_id::varchar(15) as inventory_item_id, -- 品目ID
    y_item_no::varchar(10) as y_item_no, -- Y品番
    subinventory_code::varchar(2) as subinventory_code, -- 保管場所コード
    supplier_id::varchar(15) as supplier_id, -- 仕入先ID
    supplier_code::varchar(4) as supplier_code, -- 仕入先コード
    supplier_abbreviation::varchar(8) as supplier_abbreviation, -- 仕入先名
    maker_id::varchar(15) as maker_id, -- メーカーID
    preferred_maker_code::varchar(4) as preferred_maker_code, -- メーカーコード
    preferred_maker_name::varchar(8) as preferred_maker_name, -- メーカー名
    arrangement_cls::varchar(1) as arrangement_cls, -- 手配区分
    new_spec_cls::varchar(1) as new_spec_cls, -- 新スペック区分
    comments::varchar(400) as comments, -- コメント
    error_contents_1::varchar(1) as error_contents_1, -- 異常内容1
    error_contents_2::varchar(1) as error_contents_2, -- 異常内容2
    error_contents_3::varchar(1) as error_contents_3, -- 異常内容3
    error_contents_4::varchar(1) as error_contents_4, -- 異常内容4
    error_contents_5::varchar(1) as error_contents_5, -- 異常内容5
    error_contents_6::varchar(1) as error_contents_6, -- 異常内容6
    error_contents_7::varchar(1) as error_contents_7, -- 異常内容7
    error_contents_8::varchar(1) as error_contents_8, -- 異常内容8
    error_contents_9::varchar(1) as error_contents_9, -- 異常内容9
    old_total_mtl_rqi_2ma::varchar(8) as old_total_mtl_rqi_2ma, -- 修正前TOTAL内示量(N+2月)
    old_mtl_rqi_2month_after::varchar(8) as old_mtl_rqi_2month_after, -- 修正前内示量(N+2月)
    new_mtl_rqi_2month_after::varchar(8) as new_mtl_rqi_2month_after, -- 修正後内示量(N+2月)
    operation_days_2month_after::varchar(2) as operation_days_2month_after, -- 稼働日数(N+2月)
    day_mtl_rqi_qty_2ma::varchar(8) as day_mtl_rqi_qty_2ma, -- 日当り内示量(N+2月)
    old_total_mtl_rqi_1ma::varchar(8) as old_total_mtl_rqi_1ma, -- 修正前TOTAL内示量(N+1月)
    old_mtl_rqi_1month_after::varchar(8) as old_mtl_rqi_1month_after, -- 修正前内示量(N+1月)
    new_mtl_rqi_1month_after::varchar(8) as new_mtl_rqi_1month_after, -- 修正後内示量(N+1月)
    operation_days_1month_after::varchar(2) as operation_days_1month_after, -- 稼働日数(N+1月)
    day_mtl_rqi_qty_1ma::varchar(8) as day_mtl_rqi_qty_1ma, -- 日当り内示量(N+1月)
    old_last_mtl_rqi_1ma::varchar(8) as old_last_mtl_rqi_1ma, -- 修正前前回内示量(N+1月)
    new_last_mtl_rqi_1ma::varchar(8) as new_last_mtl_rqi_1ma, -- 修正後前回内示量(N+1月)
    diff_3_1month_after::varchar(9) as diff_3_1month_after, -- 差異3(N+1月)
    diff_rate_3_1month_after::varchar(6) as diff_rate_3_1month_after, -- 差異率3(N+1月)
    old_total_mtl_rqi_month::varchar(8) as old_total_mtl_rqi_month, -- 修正前TOTAL内示量(N月)
    old_mtl_rqi_month::varchar(8) as old_mtl_rqi_month, -- 修正前内示量(N月)
    new_mtl_rqi_month::varchar(8) as new_mtl_rqi_month, -- 修正後内示量(N月)
    operation_days_month::varchar(2) as operation_days_month, -- 稼働日数(N月)
    day_mtl_rqi_qty_month::varchar(8) as day_mtl_rqi_qty_month, -- 日当り内示量(N月)
    old_befo_last_mtl_rqi_month::varchar(8) as old_befo_last_mtl_rqi_month, -- 修正前前ー回内示量(N月)
    new_befo_last_mtl_rqi_month::varchar(8) as new_befo_last_mtl_rqi_month, -- 修正後前ー回内示量(N月)
    old_last_mtl_rqi_month::varchar(8) as old_last_mtl_rqi_month, -- 修正前前回内示量(N月)
    new_last_mtl_rqi_month::varchar(8) as new_last_mtl_rqi_month, -- 修正後前回内示量(N月)
    diff_2_month::varchar(9) as diff_2_month, -- 差異2(N月)
    diff_rate_2_month::varchar(6) as diff_rate_2_month, -- 差異率2(N月)
    old_total_mtl_rqi_1mb::varchar(8) as old_total_mtl_rqi_1mb, -- 修正前TOTAL内示量(N-1月)
    new_total_mtl_rqi_1mb::varchar(8) as new_total_mtl_rqi_1mb, -- 修正後TOTAL内示量(N-1月)
    old_mtl_rqi_1month_before::varchar(8) as old_mtl_rqi_1month_before, -- 修正前内示量(N-1月)
    new_mtl_rqi_1month_before::varchar(8) as new_mtl_rqi_1month_before, -- 修正後内示量(N-1月)
    operation_days_1month_before::varchar(2) as operation_days_1month_before, -- 稼働日数(N-1月)
    day_mtl_rqi_qty_1mb::varchar(8) as day_mtl_rqi_qty_1mb, -- 日当り内示量(N-1月)
    operation_1month_before::varchar(2) as operation_1month_before, -- 稼動数(N-1月)
    delivery_actual_1mb::varchar(8) as delivery_actual_1mb, -- 納入実績(N-1月)
    actual_rate_1month_before::varchar(6) as actual_rate_1month_before, -- 実績比率(N-1月)
    old_total_mtl_rqi_2mb::varchar(8) as old_total_mtl_rqi_2mb, -- 修正前TOTAL内示量(N-2月)
    new_total_mtl_rqi_2mb::varchar(8) as new_total_mtl_rqi_2mb, -- 修正後TOTAL内示量(N-2月)
    old_mtl_rqi_2month_before::varchar(8) as old_mtl_rqi_2month_before, -- 修正前内示量(N-2月)
    new_mtl_rqi_2month_before::varchar(8) as new_mtl_rqi_2month_before, -- 修正後内示量(N-2月)
    use_actual_2month_before::varchar(9) as use_actual_2month_before, -- 使用実績(N-2月)
    actual_diff_2month_before::varchar(5) as actual_diff_2month_before, -- 実績差(N-2月)
    not_entry_actual_2mb::varchar(8) as not_entry_actual_2mb, -- 号口外使用実績(N-2月)
    total_delivery_actual_2mb::varchar(8) as total_delivery_actual_2mb, -- TOTAL納入実績(N-2月)
    delivery_actual_2mb::varchar(8) as delivery_actual_2mb, -- 納入実績(N-2月)
    month_end_stock_2mb::varchar(8) as month_end_stock_2mb, -- 月末在庫(N-2月)
    operation_days_2month_before::varchar(2) as operation_days_2month_before, -- 稼働日数(N-2月)
    error_cls_2month_before::varchar(1) as error_cls_2month_before, -- 異常区分(N-2月)
    old_total_mtl_rqi_3mb::varchar(8) as old_total_mtl_rqi_3mb, -- 修正前TOTAL内示量(N-3月)
    new_total_mtl_rqi_3mb::varchar(8) as new_total_mtl_rqi_3mb, -- 修正後TOTAL内示量(N-3月)
    old_mtl_rqi_3month_before::varchar(8) as old_mtl_rqi_3month_before, -- 修正前内示量(N-3月)
    new_mtl_rqi_3month_before::varchar(8) as new_mtl_rqi_3month_before, -- 修正後内示量(N-3月)
    use_actual_3month_before::varchar(9) as use_actual_3month_before, -- 使用実績(N-3月)
    actual_diff_3month_before::varchar(5) as actual_diff_3month_before, -- 実績差(N-3月)
    not_entry_actual_3mb::varchar(8) as not_entry_actual_3mb, -- 号口外使用実績(N-3月)
    total_delivery_actual_3mb::varchar(8) as total_delivery_actual_3mb, -- TOTAL納入実績(N-3月)
    delivery_actual_3mb::varchar(8) as delivery_actual_3mb, -- 納入実績(N-3月)
    month_end_stock_3mb::varchar(8) as month_end_stock_3mb, -- 月末在庫(N-3月)
    operation_days_3month_before::varchar(2) as operation_days_3month_before, -- 稼働日数(N-3月)
    error_cls_3month_before::varchar(1) as error_cls_3month_before, -- 異常区分(N-3月)
    old_total_mtl_rqi_4mb::varchar(8) as old_total_mtl_rqi_4mb, -- 修正前TOTAL内示量(N-4月)
    new_total_mtl_rqi_4mb::varchar(8) as new_total_mtl_rqi_4mb, -- 修正後TOTAL内示量(N-4月)
    old_mtl_rqi_4month_before::varchar(8) as old_mtl_rqi_4month_before, -- 修正前内示量(N-4月)
    new_mtl_rqi_4month_before::varchar(8) as new_mtl_rqi_4month_before, -- 修正後内示量(N-4月)
    use_actual_4month_before::varchar(9) as use_actual_4month_before, -- 使用実績(N-4月)
    actual_diff_4month_before::varchar(5) as actual_diff_4month_before, -- 実績差(N-4月)
    not_entry_actual_4mb::varchar(8) as not_entry_actual_4mb, -- 号口外使用実績(N-4月)
    total_delivery_actual_4mb::varchar(8) as total_delivery_actual_4mb, -- TOTAL納入実績(N-4月)
    delivery_actual_4mb::varchar(8) as delivery_actual_4mb, -- 納入実績(N-4月)
    month_end_stock_4mb::varchar(8) as month_end_stock_4mb, -- 月末在庫(N-4月)
    operation_days_4month_before::varchar(2) as operation_days_4month_before, -- 稼働日数(N-4月)
    error_cls_4month_before::varchar(1) as error_cls_4month_before, -- 異常区分(N-4月)
    old_total_mtl_rqi_5mb::varchar(8) as old_total_mtl_rqi_5mb, -- 修正前TOTAL内示量(N-5月)
    new_total_mtl_rqi_5mb::varchar(8) as new_total_mtl_rqi_5mb, -- 修正後TOTAL内示量(N-5月)
    old_mtl_rqi_5month_before::varchar(8) as old_mtl_rqi_5month_before, -- 修正前内示量(N-5月)
    new_mtl_rqi_5month_before::varchar(8) as new_mtl_rqi_5month_before, -- 修正後内示量(N-5月)
    use_actual_5month_before::varchar(9) as use_actual_5month_before, -- 使用実績(N-5月)
    actual_diff_5month_before::varchar(5) as actual_diff_5month_before, -- 実績差(N-5月)
    not_entry_actual_5mb::varchar(8) as not_entry_actual_5mb, -- 号口外使用実績(N-5月)
    total_delivery_actual_5mb::varchar(8) as total_delivery_actual_5mb, -- TOTAL納入実績(N-5月)
    delivery_actual_5mb::varchar(8) as delivery_actual_5mb, -- 納入実績(N-5月)
    month_end_stock_5mb::varchar(8) as month_end_stock_5mb, -- 月末在庫(N-5月)
    operation_days_5month_before::varchar(2) as operation_days_5month_before, -- 稼働日数(N-5月)
    error_cls_5month_before::varchar(1) as error_cls_5month_before, -- 異常区分(N-5月)
    old_total_mtl_rqi_6mb::varchar(8) as old_total_mtl_rqi_6mb, -- 修正前TOTAL内示量(N-6月)
    new_total_mtl_rqi_6mb::varchar(8) as new_total_mtl_rqi_6mb, -- 修正後TOTAL内示量(N-6月)
    old_mtl_rqi_6month_before::varchar(8) as old_mtl_rqi_6month_before, -- 修正前内示量(N-6月)
    new_mtl_rqi_6month_before::varchar(8) as new_mtl_rqi_6month_before, -- 修正後内示量(N-6月)
    use_actual_6month_before::varchar(9) as use_actual_6month_before, -- 使用実績(N-6月)
    actual_diff_6month_before::varchar(5) as actual_diff_6month_before, -- 実績差(N-6月)
    not_entry_actual_6mb::varchar(8) as not_entry_actual_6mb, -- 号口外使用実績(N-6月)
    total_delivery_actual_6mb::varchar(8) as total_delivery_actual_6mb, -- TOTAL納入実績(N-6月)
    delivery_actual_6mb::varchar(8) as delivery_actual_6mb, -- 納入実績(N-6月)
    month_end_stock_6mb::varchar(8) as month_end_stock_6mb, -- 月末在庫(N-6月)
    operation_days_6month_before::varchar(2) as operation_days_6month_before, -- 稼働日数(N-6月)
    error_cls_6month_before::varchar(1) as error_cls_6month_before, -- 異常区分(N-6月)
    old_total_mtl_rqi_7mb::varchar(8) as old_total_mtl_rqi_7mb, -- 修正前TOTAL内示量(N-7月)
    new_total_mtl_rqi_7mb::varchar(8) as new_total_mtl_rqi_7mb, -- 修正後TOTAL内示量(N-7月)
    old_mtl_rqi_7month_before::varchar(8) as old_mtl_rqi_7month_before, -- 修正前内示量(N-7月)
    new_mtl_rqi_7month_before::varchar(8) as new_mtl_rqi_7month_before, -- 修正後内示量(N-7月)
    use_actual_7month_before::varchar(9) as use_actual_7month_before, -- 使用実績(N-7月)
    actual_diff_7month_before::varchar(5) as actual_diff_7month_before, -- 実績差(N-7月)
    not_entry_actual_7mb::varchar(8) as not_entry_actual_7mb, -- 号口外使用実績(N-7月)
    total_delivery_actual_7mb::varchar(8) as total_delivery_actual_7mb, -- TOTAL納入実績(N-7月)
    delivery_actual_7mb::varchar(8) as delivery_actual_7mb, -- 納入実績(N-7月)
    month_end_stock_7mb::varchar(8) as month_end_stock_7mb, -- 月末在庫(N-7月)
    operation_days_7month_before::varchar(2) as operation_days_7month_before, -- 稼働日数(N-7月)
    error_cls_7month_before::varchar(1) as error_cls_7month_before, -- 異常区分(N-7月)
    difference_4::varchar(9) as difference_4, -- 差異4
    difference_5::varchar(9) as difference_5, -- 差異5
    difference_rate_4::varchar(6) as difference_rate_4, -- 差異率4
    difference_rate_5::varchar(6) as difference_rate_5, -- 差異率5
    actual_rate_3_month::varchar(6) as actual_rate_3_month, -- 実績比率(3ヶ月)
    kanban_destination_no_a::varchar(3) as kanban_destination_no_a, -- かんばん行先NoA_調達拠点
    kanban_destination_no_b::varchar(3) as kanban_destination_no_b, -- かんばん行先NoB_統括拠点
    depart_name::varchar(20) as depart_name, -- 部署名
    multiple_order_msg::varchar(4) as multiple_order_msg, -- 複社発注MSG
    multiple_order_supplier_id::varchar(15) as multiple_order_supplier_id, -- 複社発注相手方仕入先ID
    multiple_order_supplier_code::varchar(4) as multiple_order_supplier_code, -- 複社発注相手方仕入先コード
    multiple_order_name::varchar(8) as multiple_order_name, -- 複社発注相手方仕入先名
    multiple_order_maker_id::varchar(15) as multiple_order_maker_id, -- 複社発注相手方メーカーID
    multiple_order_maker_code::varchar(4) as multiple_order_maker_code, -- 複社発注相手方メーカーコード
    multiple_order_maker_name::varchar(8) as multiple_order_maker_name, -- 複社発注相手方メーカー名
    multiple_odr_cls::varchar(1) as multiple_odr_cls, -- 複社区分
    importance_mmt_mtl::varchar(1) as importance_mmt_mtl, -- 重点管理資材
    standard_weight::varchar(5) as standard_weight, -- 基準重量
    modified_number::varchar(2) as modified_number, -- 修正回数
    plan_change_count::varchar(2) as plan_change_count, -- 計変
    send_instruction::varchar(1) as send_instruction, -- 送付指示
    send_date_time::varchar(14) as send_date_time, -- 送付日時
    send_method::varchar(1) as send_method, -- 送付方法
    last_send_mtl_rqi_qty_month::varchar(8) as last_send_mtl_rqi_qty_month, -- 前回送付内示量(N月)
    last_send_mtl_rqi_qty_1ma::varchar(8) as last_send_mtl_rqi_qty_1ma, -- 前回送付内示量(N月+1)
    last_send_mtl_rqi_qty_2ma::varchar(8) as last_send_mtl_rqi_qty_2ma, -- 前回送付内示量(N月+2)
    modified_cls::varchar(1) as modified_cls, -- 修正区分
    modified_value_month::varchar(8) as modified_value_month, -- 修正値(N月)
    modified_value_1month_after::varchar(8) as modified_value_1month_after, -- 修正値(N+1月)
    modified_value_2month_after::varchar(8) as modified_value_2month_after, -- 修正値(N+2月)
    modified_method::varchar(1) as modified_method, -- 修正方法
    continuation_flag::varchar(1) as continuation_flag, -- 継続フラグ
    modified_reason::varchar(30) as modified_reason, -- 修正理由
    mtl_rqi_y_m_from::varchar(6) as mtl_rqi_y_m_from, -- 内示年月カラ
    mtl_rqi_y_m_to::varchar(6) as mtl_rqi_y_m_to, -- 内示年月マデ
    processing_date::varchar(14) as processing_date, -- 処理年月日
    file_code::varchar(3) as file_code, -- ファイルコード
    to_address::varchar(4) as to_address, -- 宛先アドレス
    to_sub_address::varchar(3) as to_sub_address, -- 宛先サブアドレス
    mil_code::varchar(3) as mil_code, -- ミルコード
    share_month::varchar(3) as share_month, -- シェア(N月)
    share_1month_after::varchar(3) as share_1month_after, -- シェア(N+1月)
    share_2month_after::varchar(3) as share_2month_after, -- シェア(N+2月)
    process_cls::varchar(1) as process_cls, -- 取引区分
    organization_id::varchar(3) as organization_id, -- 在庫組織ID
    factory_cls::varchar(1) as factory_cls, -- 組織コード（工場区分）
    object_version_number::varchar(9) as object_version_number, -- Object Version Number
    sha2('created_by', 256) as created_by, -- 作成者
    created_user_name::varchar(30) as created_user_name, -- 作成者ユーザー名
    creation_date::varchar(14) as creation_date, -- 作成日時
    sha2('last_updated_by', 256) as last_updated_by, -- 最終更新者
    last_updated_user_name::varchar(30) as last_updated_user_name, -- 最終更新者ユーザー名
    last_update_date::varchar(14) as last_update_date, -- 最終更新日時
    sha2('last_update_login', 256) as last_update_login, -- 最終更新ログイン
    last_upd_login_user_name::varchar(30) as last_upd_login_user_name, -- 最終更新ログインユーザー名
    request_id::varchar(15) as request_id, -- 要求ID
    program_application_id::varchar(15) as program_application_id, -- コンカレント・プログラム・アプリケーションID
    program_id::varchar(15) as program_id, -- コンカレント・プログラムID
    program_update_date::varchar(14) as program_update_date, -- プログラム更新日時
    "ldts" -- B層取込日時
  from {{ source_table.database }}.{{ source_table.schema }}."{{ source_table.name | lower }}"
)

select * from stg_sizainaiji_maps_view