
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'enterprise_data_products'
version: '1.0.0'
config-version: 2

vars:
  use_common_masking_policy_db: true
  common_masking_policy_db: common_tbl_db
  common_masking_policy_schema: masking_policy

# This setting configures which "profile" dbt uses for this project.
profile: 'enterprise_data_products'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  enterprise_data_products:
    +copy_grants: true
    +on_schema_change: "fail"
    bb:
      valuechain:
        +snowflake_warehouse: valuechain_wh
        +group: valuechain
        +database: valuechain_db
        +schema: public
    bd:
      valuechain:
        +snowflake_warehouse: valuechain_wh
        +group: valuechain
        +database: valuechain_db
        +schema: public
        stg:
          +access: public
          +materialized: table
      supplydemand:
        +snowflake_warehouse: supplydemand_wh
        +group: supplydemand
        +database: supplydemand_db
        +schema: public
        stg:
          +access: public
          +materialized: table
      marketing:
        +snowflake_warehouse: marketing_wh
        +group: marketing
        +database: marketing_db
        +schema: public
        stg:
          +access: public
          +materialized: table
      administration:
        +snowflake_warehouse: administration_wh
        +group: administration
        +database: administration_db
        +schema: public
        stg:
          +access: public
          +materialized: table
      customerservice:
        +snowflake_warehouse: customerservice_wh
        +group: customerservice
        +database: customerservice_db
        +schema: public
        stg:
          +access: public
          +materialized: table
      engineering:
        +snowflake_warehouse: engineering_wh
        +group: engineering
        +database: engineering_db
        +schema: public
        stg:
          +access: public
          +materialized: table
    dd:
      valuechain:
        +snowflake_warehouse: valuechain_wh
        +group: valuechain
        +database: valuechain_db
        +schema: public
        stg:
          +access: public
          +materialized: table
      marketing:
        +snowflake_warehouse: marketing_wh
        +group: marketing
        +database: marketing_db
        +schema: public
        stg:
          +access: public
          +materialized: table
      supplydemand:
        +snowflake_warehouse: supplydemand_wh
        +group: supplydemand
        +database: supplydemand_db
        +schema: public
        stg:
          +access: public
          +materialized: table
      vinhis:
        +snowflake_warehouse: vinhis_wh
        vinspec:
            +group: vinhis_vinspec
            +database: vinhis_db
            +schema: vinspec
            stg:
              +access: public
              +materialized: table
      engineering:
        +snowflake_warehouse: engineering_wh
        +group: engineering
        +database: engineering_db
        +schema: public
        stg:
          +access: public
          +materialized: table
    de:
      parts:
        +snowflake_warehouse: parts_wh
        +group: parts
        +database: parts_db
        +schema: logistics
        dim:
          +access: public
          +materialized: table
      vinhis:
        +snowflake_warehouse: vinhis_wh
        +database: vinhis_db
        yohin:
          +group: vinhis_yohin
          +schema: yohin
          dim:
          +access: public
          +materialized: table
        spec:
          +group: vinhis_spec
          +schema: spec
          dim:
            +access: public
            +materialized: table
        maint:
          +group: vinhis_maint
          +schema: maint
          dim:
            +access: public
            +materialized: table
      parts_list:
        +snowflake_warehouse: parts_list_wh
        +database: parts_list_db
        sms:
          +group: parts_list_sms
          +schema: sms
          dim:
          +access: public
          +materialized: table
    ef:
      datamart:
        +snowflake_warehouse: datamart_wh
        +group: datamart
        +database: datamart_db
        +schema: public
        dim:
          +access: public
          +materialized: table

data_tests:
  enterprise_data_products:
    +severity: warn
    +store_failures: true
    +database: common_tbl_db
    # +schema: dbt_test__audit # default
    +schema: "dbt_test__audit{{ var('DBT_JOB_NAME', '') }}"
    # +schema: "dbt_test__audit_{{ modules.datetime.date.today().strftime('%Y%m%d') }}_{{ env_var('DBT_CLOUD_RUN_ID', 'local') }}"
      # https://docs.getdbt.com/docs/build/environment-variables#special-environment-variables
      # dbt Cloud: Run history / job_xxx: Run #326668
      # >> dbt_test__audit_20231113_326668
      # >> dbt_test__audit_<yyyymmdd>_<run_id>
    singular:
      de:
        parts:
          +group: parts
      ef:
        datamart:
          +group: datamart

snapshots:
  enterprise_data_products:
    bd:
      valuechain:
        +snowflake_warehouse: valuechain_wh
        +group: valuechain
        +target_database: valuechain_db
        +target_schema: dbt_snapshots
      supplydemand:
        +snowflake_warehouse: supplydemand_wh
        +group: supplydemand
        +target_database: supplydemand_db
        +target_schema: dbt_snapshots
      marketing:
        +snowflake_warehouse: marketing_wh
        +group: marketing
        +target_database: marketing_db
        +target_schema: dbt_snapshots
      customerservice:
        +snowflake_warehouse: customerservice_wh
        +group: customerservice
        +target_database: customerservice_db
        +target_schema: dbt_snapshots
      engineering:
        +snowflake_warehouse: engineering_wh
        +group: engineering
        +target_database: engineering_db
        +target_schema: dbt_snapshots