with
    tmp60 as (
        select
            dlrcd m_dlrcd,
            yusokbn m_yusokbn,
            odrno m_ordeno,
            juchuymd m_juchuymd,
            jhinban m_jhinban,
            juchusu m_juchusu,
            syubetsu m_syubetsu,
            rimak1 m_rimak1,
            rimak2 m_rimak2,
            shinban m_shinban,
            bosu m_bosu,
            boskstime m_boskstime,
            mkaitocd m_mkaitocd,
            hnkkbn m_hnkkbn,
            hnnoytime m_hnnoytime,
            hntaytime m_hntaytime,
            hnsyytime m_hnsyytime,
            hntoytime m_hntoytime,
            hokkbn m_hokkbn,
            honoytime m_honoytime,
            hotaytime m_hotaytime,
            hosyytime m_hosyytime,
            hotoytime m_hotoytime,
            hskkbn m_hskkbn,
            hsnoytime m_hsnoytime,
            hstaytime m_hstaytime,
            hssyytime m_hssyytime,
            hstoytime m_hstoytime,
            ptopflg m_ptopflg,
            ipsyytmie m_ipsyytmie,
            martflg m_martflg,
            syukkaymd m_syukkaymd,
            syukkasu m_syukkasu,
            nyukoymd,
            nyukosu,
            kaknoukbn m_kaknoukbn,
            thibusyocd m_thibusyocd,
            thitatocd m_thitatocd,
            tehaikbn m_tehaikbn,
            keikanissu m_keikanissu,
            pendid m_pendid,
            pensu m_pensu,
            pentime m_pentime,
            skzflg m_skzflg,
            canzmflg m_canzmflg,
            pentime m_nokishiteiyoyakuymd,
            hnskiboymd m_hnskiboymd,
            hoskiboymd m_hoskiboymd,
            hsskiboymd m_hsskiboymd,
            skibohenkokaisu m_skibohenkokaisu,
            hnhonyoyakuymd m_hnhonyoyakuymd,
            hshonyoyakuymd m_hshonyoyakuymd,
            hnnksyytime m_hnnksyytime,
            honksyytime m_honksyytime,
            hsnksyytime m_hsnksyytime,
            allnosicansu m_allnosicansu,
            hnnosicansu m_hnnosicansu,
            hnnosicantime m_hnnosicantime,
            honosicantime m_honosicantime,
            hsnosicantime m_hsnosicantime,
            nosicankaisu m_nosicankaisu,
            iphonyoyakuymd m_iphonyoyakuymd,
            kariyoyakuymd m_kariyoyakuymd,
            hnnosikbn m_hnnosikbn,
            hsnosikbn m_hsnosikbn,
            honosikbn m_honosikbn,
            -- オーダー指示ファイル
            jurrsymd m_jurrsymd,
            srsirskcd m_srsirskcd,
            kozyocd m_kozyocd,
            brsirskcd m_brsirskcd,
            nonukyokbn m_nonukyokbn,
            ukeirecd m_ukeirecd,
            nonyutni m_nonyutni,
            picloke m_picloke,
            sykikicd m_sykikicd,
            sksijbsy m_sksijbsy,
            -- 手配かんばん
            zaihikbn m_zaihikbn,
            cycle4 m_cycle4,
            kjnziknisu3 m_kjnziknisu3,
            kjnziksu m_kjnziksu,
            anzenzaikonisu m_anzenzaikonisu,
            anznzksu m_anznzksu,
            nonyult m_nonyult,
            nbscd m_nbscd,
            orosibacd m_orosibacd,
            brsirskkojocd m_brsirskkojocd,
            --新入出荷　出荷実績累計
            m_pikcptime,
            m_paktime
        from {{ ref("tmp60_dm_tmc_ippan_jutyunokikaito") }}
    )
select *
from tmp60
