with substr_cvn18nosiodrjyoho as (
    select
        substr(raw_data, 1, 11)::varchar(11) as ordrkey,
        substr(raw_data, 12, 7)::varchar(7) as dlrcd,
        substr(raw_data, 19, 2)::varchar(2) as syubetsu,
        substr(raw_data, 21, 8)::varchar(8) as odrno,
        substr(raw_data, 29, 8)::varchar(8) as juchuymd,
        substr(raw_data, 37, 17)::varchar(17) as juchutime,
        substr(raw_data, 54, 20)::varchar(20) as jhinban,
        substr(raw_data, 74, 1)::varchar(1) as nosikbn,
        substr(raw_data, 75, 1)::varchar(1) as skibohenkokahi,
        substr(raw_data, 76, 1)::varchar(1) as cancelkahi,
        substr(raw_data, 77, 8)::varchar(8) as hnskiboymd,
        substr(raw_data, 85, 12)::varchar(12) as hhenkoymd,
        substr(raw_data, 97, 8)::varchar(8) as hoskiboymd,
        substr(raw_data, 105, 12)::varchar(12) as hohenkoymd,
        substr(raw_data, 117, 8)::varchar(8) as hsskiboymd,
        substr(raw_data, 125, 6)::varchar(6) as skibohenkokaisu,
        substr(raw_data, 131, 6)::varchar(6) as kariyoyakubosu,
        substr(raw_data, 137, 8)::varchar(8) as nonyuhinhikiymd,
        substr(raw_data, 145, 12)::varchar(12) as nktoytime,
        substr(raw_data, 157, 8)::varchar(8) as hnhonyoyakuymd,
        substr(raw_data, 165, 8)::varchar(8) as hohonyoyakuymd,
        substr(raw_data, 173, 8)::varchar(8) as hshonyoyakuymd,
        substr(raw_data, 181, 12)::varchar(12) as hnbosyytime,
        substr(raw_data, 193, 12)::varchar(12) as hobosyytime,
        substr(raw_data, 205, 12)::varchar(12) as hsbosyytime,
        substr(raw_data, 217, 12)::varchar(12) as hnnksyytime,
        substr(raw_data, 229, 12)::varchar(12) as honksyytime,
        substr(raw_data, 241, 12)::varchar(12) as hsnksyytime,
        substr(raw_data, 253, 6)::varchar(6) as allnosicansu,
        substr(raw_data, 259, 6)::varchar(6) as hnnosicansu,
        substr(raw_data, 265, 12)::varchar(12) as hnnosicantime,
        substr(raw_data, 277, 6)::varchar(6) as honosicansu,
        substr(raw_data, 283, 12)::varchar(12) as honosicantime,
        substr(raw_data, 295, 6)::varchar(6) as hsnosicansu,
        substr(raw_data, 301, 12)::varchar(12) as hsnosicantime,
        substr(raw_data, 313, 6)::varchar(6) as nosicankaisu,
        substr(raw_data, 319, 6)::varchar(6) as htymatisu,
        substr(raw_data, 325, 8)::varchar(8) as hdyoteiymd,
        substr(raw_data, 333, 8)::varchar(8) as iphonyoyakuymd,
        substr(raw_data, 341, 16)::varchar(16) as mtuserid,
        substr(raw_data, 357, 26)::varchar(26) as mttime,
        ldts
    from {{ source('snowpipe_db_valuechain', 'raw_cvn18nosiodrjyoho') }}
)
select * from substr_cvn18nosiodrjyoho
