with substr_tbnoukifl as (
    select
        substr(raw_data, 1, 5)::varchar(5) as kyouhan,
        substr(raw_data, 6, 5)::varchar(5) as usercd,
        substr(raw_data, 11, 20)::varchar(20) as hinban,
        substr(raw_data, 31, 1)::varchar(1) as mkbn,
        substr(raw_data, 32, 8)::varchar(8) as jchuymd,
        substr(raw_data, 40, 4)::varchar(4) as jchutime,
        substr(raw_data, 44, 6)::varchar(6) as jdenno,
        substr(raw_data, 50, 2)::varchar(2) as jdennoeda,
        substr(raw_data, 52, 5)::varchar(5) as chumon,
        substr(raw_data, 57, 2)::varchar(2) as nyukktn,
        substr(raw_data, 59, 2)::varchar(2) as jchuktn,
        substr(raw_data, 61, 8)::varchar(8) as shitei,
        substr(raw_data, 69, 1)::varchar(1) as urikbn,
        substr(raw_data, 70, 1)::varchar(1) as hchuhzaikbn,
        substr(raw_data, 71, 2)::varchar(2) as gsy,
        substr(raw_data, 73, 2)::varchar(2) as kaisya,
        substr(raw_data, 75, 14)::varchar(14) as tchumon,
        substr(raw_data, 89, 1)::varchar(1) as nouhkbn,
        substr(raw_data, 90, 2)::varchar(2) as sgroup1,
        substr(raw_data, 92, 1)::varchar(1) as goguchi,
        substr(raw_data, 93, 1)::varchar(1) as rokeg,
        substr(raw_data, 94, 1)::varchar(1) as bunsan,
        substr(raw_data, 95, 4)::varchar(4) as hinmok,
        substr(raw_data, 99, 2)::varchar(2) as shincd,
        substr(raw_data, 101, 5)::varchar(5) as makercd,
        substr(raw_data, 106, 1)::varchar(1) as kyokbn,
        substr(raw_data, 107, 1)::varchar(1) as syukkflg,
        substr(raw_data, 108, 8)::varchar(8) as kanryouymd,
        substr(raw_data, 116, 2)::varchar(2) as kensu,
        substr(raw_data, 118, 2)::varchar(2) as hisouktn,
        substr(raw_data, 120, 1)::varchar(1) as syakptn,
        substr(raw_data, 121, 1)::varchar(1) as syakkbn,
        substr(raw_data, 122, 4)::varchar(4) as hbinno,
        substr(raw_data, 126, 1)::varchar(1) as syukkbn,
        substr(raw_data, 127, 2)::varchar(2) as syukktn,
        substr(raw_data, 129, 8)::varchar(8) as nokiymd,
        substr(raw_data, 137, 1)::varchar(1) as binno,
        substr(raw_data, 138, 4)::varchar(4) as hikiwatashi,
        substr(raw_data, 142, 8)::varchar(8) as kaitymd,
        substr(raw_data, 150, 4)::varchar(4) as kaittime,
        substr(raw_data, 154, 1)::varchar(1) as nokikbn,
        substr(raw_data, 155, 8)::varchar(8) as hknyukaymd,
        substr(raw_data, 163, 4)::varchar(4) as hknyukatime,
        substr(raw_data, 167, 8)::varchar(8) as hkkanymd,
        substr(raw_data, 175, 4)::varchar(4) as hkkantime,
        substr(raw_data, 179, 8)::varchar(8) as syukknoymd,
        substr(raw_data, 187, 4)::varchar(4) as syukknotime,
        substr(raw_data, 191, 1)::varchar(1) as keitai,
        substr(raw_data, 192, 1)::varchar(1) as defkaito,
        substr(raw_data, 193, 8)::varchar(8) as msyukaymd,
        substr(raw_data, 201, 4)::varchar(4) as msyukatime,
        ldts
    from {{ source('snowpipe_db_valuechain', 'raw_tbnoukifl') }}
)
select * from substr_tbnoukifl