with substr_dv2a4974 as (
    select
        substr(raw_data, 1, 1)::varchar(1) as mntkbn,
        substr(raw_data, 2, 6)::varchar(6) as ctlgcd,
        substr(raw_data, 8, 20)::varchar(20) as syakata,
        substr(raw_data, 28, 4)::varchar(4) as syasyu_cd,
        substr(raw_data, 32, 9)::varchar(9) as vinwmivds,
        substr(raw_data, 41, 6)::varchar(6) as jissijikik,
        substr(raw_data, 47, 6)::varchar(6) as jissijikim,
        substr(raw_data, 53, 7)::varchar(7) as frmnokata,
        substr(raw_data, 60, 3)::varchar(3) as katano,
        substr(raw_data, 63, 10)::varchar(10) as katatokukg1,
        substr(raw_data, 73, 10)::varchar(10) as katatokukg2,
        substr(raw_data, 83, 5)::varchar(5) as katatokukg3,
        substr(raw_data, 88, 5)::varchar(5) as katatokukg4,
        substr(raw_data, 93, 5)::varchar(5) as katatokukg5,
        substr(raw_data, 98, 5)::varchar(5) as katatokukg6,
        substr(raw_data, 103, 5)::varchar(5) as katatokukg7,
        substr(raw_data, 108, 5)::varchar(5) as katatokukg8,
        substr(raw_data, 113, 5)::varchar(5) as katatokukg9,
        substr(raw_data, 118, 5)::varchar(5) as katatokukg10,
        substr(raw_data, 123, 5)::varchar(5) as katatokukg11,
        substr(raw_data, 128, 5)::varchar(5) as katatokukg12,
        substr(raw_data, 133, 5)::varchar(5) as katatokukg13,
        substr(raw_data, 138, 5)::varchar(5) as katatokukg14,
        substr(raw_data, 143, 5)::varchar(5) as katatokukg15,
        substr(raw_data, 148, 5)::varchar(5) as katatokukg16,
        substr(raw_data, 153, 5)::varchar(5) as katatokukg17,
        substr(raw_data, 158, 5)::varchar(5) as katatokukg18,
        substr(raw_data, 163, 5)::varchar(5) as katatokukg19,
        substr(raw_data, 168, 5)::varchar(5) as katatokukg20,
        substr(raw_data, 173, 5)::varchar(5) as katatokukg21,
        substr(raw_data, 178, 5)::varchar(5) as katatokukg22,
        substr(raw_data, 183, 5)::varchar(5) as katatokukg23,
        ldts
    from {{source('snowpipe_db_valuechain', 'raw_dv2a4974')}}
)
select * from substr_dv2a4974