{{
    config(
        materialized='incremental',
        incremental_strategy = 'append'
    )
}}

with stg_kokunaijutyujisseki_daily_atop as (
    select
        iff(rtrim(jhinban, ' 　') = '', null, rtrim(jhinban, ' 　'))::varchar(20) as jhinban,
        iff(rtrim(tiikicd2, ' 　') = '', null, rtrim(tiikicd2, ' 　'))::varchar(2) as tiikicd2,
        iff(rtrim(jcym, ' 　') = '', null, rtrim(jcym, ' 　'))::varchar(6) as jcym,
        iff(rtrim(orgjcsusign_1d||orgjcsu_1d, ' 　') = '', null, to_decimal(orgjcsusign_1d||orgjcsu_1d))::number(7,0) as orgjcsu_1d,
        iff(rtrim(orgrjtjcsusign_1d||orgrjtjcsu_1d, ' 　') = '', null, to_decimal(orgrjtjcsusign_1d||orgrjtjcsu_1d))::number(7,0) as orgrjtjcsu_1d,
        iff(rtrim(orghindsign_1d||orghind_1d, ' 　') = '', null, to_decimal(orghindsign_1d||orghind_1d))::number(3,0) as orghind_1d,
        iff(rtrim(ysjcsusign_1d||ysjcsu_1d, ' 　') = '', null, to_decimal(ysjcsusign_1d||ysjcsu_1d))::number(7,0) as ysjcsu_1d,
        iff(rtrim(orgjcsusign_2d||orgjcsu_2d, ' 　') = '', null, to_decimal(orgjcsusign_2d||orgjcsu_2d))::number(7,0) as orgjcsu_2d,
        iff(rtrim(orgrjtjcsusign_2d||orgrjtjcsu_2d, ' 　') = '', null, to_decimal(orgrjtjcsusign_2d||orgrjtjcsu_2d))::number(7,0) as orgrjtjcsu_2d,
        iff(rtrim(orghindsign_2d||orghind_2d, ' 　') = '', null, to_decimal(orghindsign_2d||orghind_2d))::number(3,0) as orghind_2d,
        iff(rtrim(ysjcsusign_2d||ysjcsu_2d, ' 　') = '', null, to_decimal(ysjcsusign_2d||ysjcsu_2d))::number(7,0) as ysjcsu_2d,
        iff(rtrim(orgjcsusign_3d||orgjcsu_3d, ' 　') = '', null, to_decimal(orgjcsusign_3d||orgjcsu_3d))::number(7,0) as orgjcsu_3d,
        iff(rtrim(orgrjtjcsusign_3d||orgrjtjcsu_3d, ' 　') = '', null, to_decimal(orgrjtjcsusign_3d||orgrjtjcsu_3d))::number(7,0) as orgrjtjcsu_3d,
        iff(rtrim(orghindsign_3d||orghind_3d, ' 　') = '', null, to_decimal(orghindsign_3d||orghind_3d))::number(3,0) as orghind_3d,
        iff(rtrim(ysjcsusign_3d||ysjcsu_3d, ' 　') = '', null, to_decimal(ysjcsusign_3d||ysjcsu_3d))::number(7,0) as ysjcsu_3d,
        iff(rtrim(orgjcsusign_4d||orgjcsu_4d, ' 　') = '', null, to_decimal(orgjcsusign_4d||orgjcsu_4d))::number(7,0) as orgjcsu_4d,
        iff(rtrim(orgrjtjcsusign_4d||orgrjtjcsu_4d, ' 　') = '', null, to_decimal(orgrjtjcsusign_4d||orgrjtjcsu_4d))::number(7,0) as orgrjtjcsu_4d,
        iff(rtrim(orghindsign_4d||orghind_4d, ' 　') = '', null, to_decimal(orghindsign_4d||orghind_4d))::number(3,0) as orghind_4d,
        iff(rtrim(ysjcsusign_4d||ysjcsu_4d, ' 　') = '', null, to_decimal(ysjcsusign_4d||ysjcsu_4d))::number(7,0) as ysjcsu_4d,
        iff(rtrim(orgjcsusign_5d||orgjcsu_5d, ' 　') = '', null, to_decimal(orgjcsusign_5d||orgjcsu_5d))::number(7,0) as orgjcsu_5d,
        iff(rtrim(orgrjtjcsusign_5d||orgrjtjcsu_5d, ' 　') = '', null, to_decimal(orgrjtjcsusign_5d||orgrjtjcsu_5d))::number(7,0) as orgrjtjcsu_5d,
        iff(rtrim(orghindsign_5d||orghind_5d, ' 　') = '', null, to_decimal(orghindsign_5d||orghind_5d))::number(3,0) as orghind_5d,
        iff(rtrim(ysjcsusign_5d||ysjcsu_5d, ' 　') = '', null, to_decimal(ysjcsusign_5d||ysjcsu_5d))::number(7,0) as ysjcsu_5d,
        iff(rtrim(orgjcsusign_6d||orgjcsu_6d, ' 　') = '', null, to_decimal(orgjcsusign_6d||orgjcsu_6d))::number(7,0) as orgjcsu_6d,
        iff(rtrim(orgrjtjcsusign_6d||orgrjtjcsu_6d, ' 　') = '', null, to_decimal(orgrjtjcsusign_6d||orgrjtjcsu_6d))::number(7,0) as orgrjtjcsu_6d,
        iff(rtrim(orghindsign_6d||orghind_6d, ' 　') = '', null, to_decimal(orghindsign_6d||orghind_6d))::number(3,0) as orghind_6d,
        iff(rtrim(ysjcsusign_6d||ysjcsu_6d, ' 　') = '', null, to_decimal(ysjcsusign_6d||ysjcsu_6d))::number(7,0) as ysjcsu_6d,
        iff(rtrim(orgjcsusign_7d||orgjcsu_7d, ' 　') = '', null, to_decimal(orgjcsusign_7d||orgjcsu_7d))::number(7,0) as orgjcsu_7d,
        iff(rtrim(orgrjtjcsusign_7d||orgrjtjcsu_7d, ' 　') = '', null, to_decimal(orgrjtjcsusign_7d||orgrjtjcsu_7d))::number(7,0) as orgrjtjcsu_7d,
        iff(rtrim(orghindsign_7d||orghind_7d, ' 　') = '', null, to_decimal(orghindsign_7d||orghind_7d))::number(3,0) as orghind_7d,
        iff(rtrim(ysjcsusign_7d||ysjcsu_7d, ' 　') = '', null, to_decimal(ysjcsusign_7d||ysjcsu_7d))::number(7,0) as ysjcsu_7d,
        iff(rtrim(orgjcsusign_8d||orgjcsu_8d, ' 　') = '', null, to_decimal(orgjcsusign_8d||orgjcsu_8d))::number(7,0) as orgjcsu_8d,
        iff(rtrim(orgrjtjcsusign_8d||orgrjtjcsu_8d, ' 　') = '', null, to_decimal(orgrjtjcsusign_8d||orgrjtjcsu_8d))::number(7,0) as orgrjtjcsu_8d,
        iff(rtrim(orghindsign_8d||orghind_8d, ' 　') = '', null, to_decimal(orghindsign_8d||orghind_8d))::number(3,0) as orghind_8d,
        iff(rtrim(ysjcsusign_8d||ysjcsu_8d, ' 　') = '', null, to_decimal(ysjcsusign_8d||ysjcsu_8d))::number(7,0) as ysjcsu_8d,
        iff(rtrim(orgjcsusign_9d||orgjcsu_9d, ' 　') = '', null, to_decimal(orgjcsusign_9d||orgjcsu_9d))::number(7,0) as orgjcsu_9d,
        iff(rtrim(orgrjtjcsusign_9d||orgrjtjcsu_9d, ' 　') = '', null, to_decimal(orgrjtjcsusign_9d||orgrjtjcsu_9d))::number(7,0) as orgrjtjcsu_9d,
        iff(rtrim(orghindsign_9d||orghind_9d, ' 　') = '', null, to_decimal(orghindsign_9d||orghind_9d))::number(3,0) as orghind_9d,
        iff(rtrim(ysjcsusign_9d||ysjcsu_9d, ' 　') = '', null, to_decimal(ysjcsusign_9d||ysjcsu_9d))::number(7,0) as ysjcsu_9d,
        iff(rtrim(orgjcsusign_10d||orgjcsu_10d, ' 　') = '', null, to_decimal(orgjcsusign_10d||orgjcsu_10d))::number(7,0) as orgjcsu_10d,
        iff(rtrim(orgrjtjcsusign_10d||orgrjtjcsu_10d, ' 　') = '', null, to_decimal(orgrjtjcsusign_10d||orgrjtjcsu_10d))::number(7,0) as orgrjtjcsu_10d,
        iff(rtrim(orghindsign_10d||orghind_10d, ' 　') = '', null, to_decimal(orghindsign_10d||orghind_10d))::number(3,0) as orghind_10d,
        iff(rtrim(ysjcsusign_10d||ysjcsu_10d, ' 　') = '', null, to_decimal(ysjcsusign_10d||ysjcsu_10d))::number(7,0) as ysjcsu_10d,
        iff(rtrim(orgjcsusign_11d||orgjcsu_11d, ' 　') = '', null, to_decimal(orgjcsusign_11d||orgjcsu_11d))::number(7,0) as orgjcsu_11d,
        iff(rtrim(orgrjtjcsusign_11d||orgrjtjcsu_11d, ' 　') = '', null, to_decimal(orgrjtjcsusign_11d||orgrjtjcsu_11d))::number(7,0) as orgrjtjcsu_11d,
        iff(rtrim(orghindsign_11d||orghind_11d, ' 　') = '', null, to_decimal(orghindsign_11d||orghind_11d))::number(3,0) as orghind_11d,
        iff(rtrim(ysjcsusign_11d||ysjcsu_11d, ' 　') = '', null, to_decimal(ysjcsusign_11d||ysjcsu_11d))::number(7,0) as ysjcsu_11d,
        iff(rtrim(orgjcsusign_12d||orgjcsu_12d, ' 　') = '', null, to_decimal(orgjcsusign_12d||orgjcsu_12d))::number(7,0) as orgjcsu_12d,
        iff(rtrim(orgrjtjcsusign_12d||orgrjtjcsu_12d, ' 　') = '', null, to_decimal(orgrjtjcsusign_12d||orgrjtjcsu_12d))::number(7,0) as orgrjtjcsu_12d,
        iff(rtrim(orghindsign_12d||orghind_12d, ' 　') = '', null, to_decimal(orghindsign_12d||orghind_12d))::number(3,0) as orghind_12d,
        iff(rtrim(ysjcsusign_12d||ysjcsu_12d, ' 　') = '', null, to_decimal(ysjcsusign_12d||ysjcsu_12d))::number(7,0) as ysjcsu_12d,
        iff(rtrim(orgjcsusign_13d||orgjcsu_13d, ' 　') = '', null, to_decimal(orgjcsusign_13d||orgjcsu_13d))::number(7,0) as orgjcsu_13d,
        iff(rtrim(orgrjtjcsusign_13d||orgrjtjcsu_13d, ' 　') = '', null, to_decimal(orgrjtjcsusign_13d||orgrjtjcsu_13d))::number(7,0) as orgrjtjcsu_13d,
        iff(rtrim(orghindsign_13d||orghind_13d, ' 　') = '', null, to_decimal(orghindsign_13d||orghind_13d))::number(3,0) as orghind_13d,
        iff(rtrim(ysjcsusign_13d||ysjcsu_13d, ' 　') = '', null, to_decimal(ysjcsusign_13d||ysjcsu_13d))::number(7,0) as ysjcsu_13d,
        iff(rtrim(orgjcsusign_14d||orgjcsu_14d, ' 　') = '', null, to_decimal(orgjcsusign_14d||orgjcsu_14d))::number(7,0) as orgjcsu_14d,
        iff(rtrim(orgrjtjcsusign_14d||orgrjtjcsu_14d, ' 　') = '', null, to_decimal(orgrjtjcsusign_14d||orgrjtjcsu_14d))::number(7,0) as orgrjtjcsu_14d,
        iff(rtrim(orghindsign_14d||orghind_14d, ' 　') = '', null, to_decimal(orghindsign_14d||orghind_14d))::number(3,0) as orghind_14d,
        iff(rtrim(ysjcsusign_14d||ysjcsu_14d, ' 　') = '', null, to_decimal(ysjcsusign_14d||ysjcsu_14d))::number(7,0) as ysjcsu_14d,
        iff(rtrim(orgjcsusign_15d||orgjcsu_15d, ' 　') = '', null, to_decimal(orgjcsusign_15d||orgjcsu_15d))::number(7,0) as orgjcsu_15d,
        iff(rtrim(orgrjtjcsusign_15d||orgrjtjcsu_15d, ' 　') = '', null, to_decimal(orgrjtjcsusign_15d||orgrjtjcsu_15d))::number(7,0) as orgrjtjcsu_15d,
        iff(rtrim(orghindsign_15d||orghind_15d, ' 　') = '', null, to_decimal(orghindsign_15d||orghind_15d))::number(3,0) as orghind_15d,
        iff(rtrim(ysjcsusign_15d||ysjcsu_15d, ' 　') = '', null, to_decimal(ysjcsusign_15d||ysjcsu_15d))::number(7,0) as ysjcsu_15d,
        iff(rtrim(orgjcsusign_16d||orgjcsu_16d, ' 　') = '', null, to_decimal(orgjcsusign_16d||orgjcsu_16d))::number(7,0) as orgjcsu_16d,
        iff(rtrim(orgrjtjcsusign_16d||orgrjtjcsu_16d, ' 　') = '', null, to_decimal(orgrjtjcsusign_16d||orgrjtjcsu_16d))::number(7,0) as orgrjtjcsu_16d,
        iff(rtrim(orghindsign_16d||orghind_16d, ' 　') = '', null, to_decimal(orghindsign_16d||orghind_16d))::number(3,0) as orghind_16d,
        iff(rtrim(ysjcsusign_16d||ysjcsu_16d, ' 　') = '', null, to_decimal(ysjcsusign_16d||ysjcsu_16d))::number(7,0) as ysjcsu_16d,
        iff(rtrim(orgjcsusign_17d||orgjcsu_17d, ' 　') = '', null, to_decimal(orgjcsusign_17d||orgjcsu_17d))::number(7,0) as orgjcsu_17d,
        iff(rtrim(orgrjtjcsusign_17d||orgrjtjcsu_17d, ' 　') = '', null, to_decimal(orgrjtjcsusign_17d||orgrjtjcsu_17d))::number(7,0) as orgrjtjcsu_17d,
        iff(rtrim(orghindsign_17d||orghind_17d, ' 　') = '', null, to_decimal(orghindsign_17d||orghind_17d))::number(3,0) as orghind_17d,
        iff(rtrim(ysjcsusign_17d||ysjcsu_17d, ' 　') = '', null, to_decimal(ysjcsusign_17d||ysjcsu_17d))::number(7,0) as ysjcsu_17d,
        iff(rtrim(orgjcsusign_18d||orgjcsu_18d, ' 　') = '', null, to_decimal(orgjcsusign_18d||orgjcsu_18d))::number(7,0) as orgjcsu_18d,
        iff(rtrim(orgrjtjcsusign_18d||orgrjtjcsu_18d, ' 　') = '', null, to_decimal(orgrjtjcsusign_18d||orgrjtjcsu_18d))::number(7,0) as orgrjtjcsu_18d,
        iff(rtrim(orghindsign_18d||orghind_18d, ' 　') = '', null, to_decimal(orghindsign_18d||orghind_18d))::number(3,0) as orghind_18d,
        iff(rtrim(ysjcsusign_18d||ysjcsu_18d, ' 　') = '', null, to_decimal(ysjcsusign_18d||ysjcsu_18d))::number(7,0) as ysjcsu_18d,
        iff(rtrim(orgjcsusign_19d||orgjcsu_19d, ' 　') = '', null, to_decimal(orgjcsusign_19d||orgjcsu_19d))::number(7,0) as orgjcsu_19d,
        iff(rtrim(orgrjtjcsusign_19d||orgrjtjcsu_19d, ' 　') = '', null, to_decimal(orgrjtjcsusign_19d||orgrjtjcsu_19d))::number(7,0) as orgrjtjcsu_19d,
        iff(rtrim(orghindsign_19d||orghind_19d, ' 　') = '', null, to_decimal(orghindsign_19d||orghind_19d))::number(3,0) as orghind_19d,
        iff(rtrim(ysjcsusign_19d||ysjcsu_19d, ' 　') = '', null, to_decimal(ysjcsusign_19d||ysjcsu_19d))::number(7,0) as ysjcsu_19d,
        iff(rtrim(orgjcsusign_20d||orgjcsu_20d, ' 　') = '', null, to_decimal(orgjcsusign_20d||orgjcsu_20d))::number(7,0) as orgjcsu_20d,
        iff(rtrim(orgrjtjcsusign_20d||orgrjtjcsu_20d, ' 　') = '', null, to_decimal(orgrjtjcsusign_20d||orgrjtjcsu_20d))::number(7,0) as orgrjtjcsu_20d,
        iff(rtrim(orghindsign_20d||orghind_20d, ' 　') = '', null, to_decimal(orghindsign_20d||orghind_20d))::number(3,0) as orghind_20d,
        iff(rtrim(ysjcsusign_20d||ysjcsu_20d, ' 　') = '', null, to_decimal(ysjcsusign_20d||ysjcsu_20d))::number(7,0) as ysjcsu_20d,
        iff(rtrim(orgjcsusign_21d||orgjcsu_21d, ' 　') = '', null, to_decimal(orgjcsusign_21d||orgjcsu_21d))::number(7,0) as orgjcsu_21d,
        iff(rtrim(orgrjtjcsusign_21d||orgrjtjcsu_21d, ' 　') = '', null, to_decimal(orgrjtjcsusign_21d||orgrjtjcsu_21d))::number(7,0) as orgrjtjcsu_21d,
        iff(rtrim(orghindsign_21d||orghind_21d, ' 　') = '', null, to_decimal(orghindsign_21d||orghind_21d))::number(3,0) as orghind_21d,
        iff(rtrim(ysjcsusign_21d||ysjcsu_21d, ' 　') = '', null, to_decimal(ysjcsusign_21d||ysjcsu_21d))::number(7,0) as ysjcsu_21d,
        iff(rtrim(orgjcsusign_22d||orgjcsu_22d, ' 　') = '', null, to_decimal(orgjcsusign_22d||orgjcsu_22d))::number(7,0) as orgjcsu_22d,
        iff(rtrim(orgrjtjcsusign_22d||orgrjtjcsu_22d, ' 　') = '', null, to_decimal(orgrjtjcsusign_22d||orgrjtjcsu_22d))::number(7,0) as orgrjtjcsu_22d,
        iff(rtrim(orghindsign_22d||orghind_22d, ' 　') = '', null, to_decimal(orghindsign_22d||orghind_22d))::number(3,0) as orghind_22d,
        iff(rtrim(ysjcsusign_22d||ysjcsu_22d, ' 　') = '', null, to_decimal(ysjcsusign_22d||ysjcsu_22d))::number(7,0) as ysjcsu_22d,
        iff(rtrim(orgjcsusign_23d||orgjcsu_23d, ' 　') = '', null, to_decimal(orgjcsusign_23d||orgjcsu_23d))::number(7,0) as orgjcsu_23d,
        iff(rtrim(orgrjtjcsusign_23d||orgrjtjcsu_23d, ' 　') = '', null, to_decimal(orgrjtjcsusign_23d||orgrjtjcsu_23d))::number(7,0) as orgrjtjcsu_23d,
        iff(rtrim(orghindsign_23d||orghind_23d, ' 　') = '', null, to_decimal(orghindsign_23d||orghind_23d))::number(3,0) as orghind_23d,
        iff(rtrim(ysjcsusign_23d||ysjcsu_23d, ' 　') = '', null, to_decimal(ysjcsusign_23d||ysjcsu_23d))::number(7,0) as ysjcsu_23d,
        iff(rtrim(orgjcsusign_24d||orgjcsu_24d, ' 　') = '', null, to_decimal(orgjcsusign_24d||orgjcsu_24d))::number(7,0) as orgjcsu_24d,
        iff(rtrim(orgrjtjcsusign_24d||orgrjtjcsu_24d, ' 　') = '', null, to_decimal(orgrjtjcsusign_24d||orgrjtjcsu_24d))::number(7,0) as orgrjtjcsu_24d,
        iff(rtrim(orghindsign_24d||orghind_24d, ' 　') = '', null, to_decimal(orghindsign_24d||orghind_24d))::number(3,0) as orghind_24d,
        iff(rtrim(ysjcsusign_24d||ysjcsu_24d, ' 　') = '', null, to_decimal(ysjcsusign_24d||ysjcsu_24d))::number(7,0) as ysjcsu_24d,
        iff(rtrim(orgjcsusign_25d||orgjcsu_25d, ' 　') = '', null, to_decimal(orgjcsusign_25d||orgjcsu_25d))::number(7,0) as orgjcsu_25d,
        iff(rtrim(orgrjtjcsusign_25d||orgrjtjcsu_25d, ' 　') = '', null, to_decimal(orgrjtjcsusign_25d||orgrjtjcsu_25d))::number(7,0) as orgrjtjcsu_25d,
        iff(rtrim(orghindsign_25d||orghind_25d, ' 　') = '', null, to_decimal(orghindsign_25d||orghind_25d))::number(3,0) as orghind_25d,
        iff(rtrim(ysjcsusign_25d||ysjcsu_25d, ' 　') = '', null, to_decimal(ysjcsusign_25d||ysjcsu_25d))::number(7,0) as ysjcsu_25d,
        iff(rtrim(orgjcsusign_26d||orgjcsu_26d, ' 　') = '', null, to_decimal(orgjcsusign_26d||orgjcsu_26d))::number(7,0) as orgjcsu_26d,
        iff(rtrim(orgrjtjcsusign_26d||orgrjtjcsu_26d, ' 　') = '', null, to_decimal(orgrjtjcsusign_26d||orgrjtjcsu_26d))::number(7,0) as orgrjtjcsu_26d,
        iff(rtrim(orghindsign_26d||orghind_26d, ' 　') = '', null, to_decimal(orghindsign_26d||orghind_26d))::number(3,0) as orghind_26d,
        iff(rtrim(ysjcsusign_26d||ysjcsu_26d, ' 　') = '', null, to_decimal(ysjcsusign_26d||ysjcsu_26d))::number(7,0) as ysjcsu_26d,
        iff(rtrim(orgjcsusign_27d||orgjcsu_27d, ' 　') = '', null, to_decimal(orgjcsusign_27d||orgjcsu_27d))::number(7,0) as orgjcsu_27d,
        iff(rtrim(orgrjtjcsusign_27d||orgrjtjcsu_27d, ' 　') = '', null, to_decimal(orgrjtjcsusign_27d||orgrjtjcsu_27d))::number(7,0) as orgrjtjcsu_27d,
        iff(rtrim(orghindsign_27d||orghind_27d, ' 　') = '', null, to_decimal(orghindsign_27d||orghind_27d))::number(3,0) as orghind_27d,
        iff(rtrim(ysjcsusign_27d||ysjcsu_27d, ' 　') = '', null, to_decimal(ysjcsusign_27d||ysjcsu_27d))::number(7,0) as ysjcsu_27d,
        iff(rtrim(orgjcsusign_28d||orgjcsu_28d, ' 　') = '', null, to_decimal(orgjcsusign_28d||orgjcsu_28d))::number(7,0) as orgjcsu_28d,
        iff(rtrim(orgrjtjcsusign_28d||orgrjtjcsu_28d, ' 　') = '', null, to_decimal(orgrjtjcsusign_28d||orgrjtjcsu_28d))::number(7,0) as orgrjtjcsu_28d,
        iff(rtrim(orghindsign_28d||orghind_28d, ' 　') = '', null, to_decimal(orghindsign_28d||orghind_28d))::number(3,0) as orghind_28d,
        iff(rtrim(ysjcsusign_28d||ysjcsu_28d, ' 　') = '', null, to_decimal(ysjcsusign_28d||ysjcsu_28d))::number(7,0) as ysjcsu_28d,
        iff(rtrim(orgjcsusign_29d||orgjcsu_29d, ' 　') = '', null, to_decimal(orgjcsusign_29d||orgjcsu_29d))::number(7,0) as orgjcsu_29d,
        iff(rtrim(orgrjtjcsusign_29d||orgrjtjcsu_29d, ' 　') = '', null, to_decimal(orgrjtjcsusign_29d||orgrjtjcsu_29d))::number(7,0) as orgrjtjcsu_29d,
        iff(rtrim(orghindsign_29d||orghind_29d, ' 　') = '', null, to_decimal(orghindsign_29d||orghind_29d))::number(3,0) as orghind_29d,
        iff(rtrim(ysjcsusign_29d||ysjcsu_29d, ' 　') = '', null, to_decimal(ysjcsusign_29d||ysjcsu_29d))::number(7,0) as ysjcsu_29d,
        iff(rtrim(orgjcsusign_30d||orgjcsu_30d, ' 　') = '', null, to_decimal(orgjcsusign_30d||orgjcsu_30d))::number(7,0) as orgjcsu_30d,
        iff(rtrim(orgrjtjcsusign_30d||orgrjtjcsu_30d, ' 　') = '', null, to_decimal(orgrjtjcsusign_30d||orgrjtjcsu_30d))::number(7,0) as orgrjtjcsu_30d,
        iff(rtrim(orghindsign_30d||orghind_30d, ' 　') = '', null, to_decimal(orghindsign_30d||orghind_30d))::number(3,0) as orghind_30d,
        iff(rtrim(ysjcsusign_30d||ysjcsu_30d, ' 　') = '', null, to_decimal(ysjcsusign_30d||ysjcsu_30d))::number(7,0) as ysjcsu_30d,
        iff(rtrim(orgjcsusign_31d||orgjcsu_31d, ' 　') = '', null, to_decimal(orgjcsusign_31d||orgjcsu_31d))::number(7,0) as orgjcsu_31d,
        iff(rtrim(orgrjtjcsusign_31d||orgrjtjcsu_31d, ' 　') = '', null, to_decimal(orgrjtjcsusign_31d||orgrjtjcsu_31d))::number(7,0) as orgrjtjcsu_31d,
        iff(rtrim(orghindsign_31d||orghind_31d, ' 　') = '', null, to_decimal(orghindsign_31d||orghind_31d))::number(3,0) as orghind_31d,
        iff(rtrim(ysjcsusign_31d||ysjcsu_31d, ' 　') = '', null, to_decimal(ysjcsusign_31d||ysjcsu_31d))::number(7,0) as ysjcsu_31d,
        iff(rtrim(mtuserid, ' 　') = '', null, rtrim(mtuserid, ' 　'))::varchar(16) as mtuserid,
        iff(rtrim(mttime, ' 　') = '', null, to_timestamp_ntz(mttime, 'yyyy-mm-dd-hh24.mi.ss.ff6'))::timestamp_ntz(9) as mttime,
        ldts::timestamp_ntz(9) as ldts,
    from {{ref('substr_ktrla01vzz0kvr00q4')}}
    {% if is_incremental() %}
        where ldts > (select max(ldts) from {{this}})
    {% endif %}
)
select * from stg_kokunaijutyujisseki_daily_atop