id: dbt_docs_generate
namespace: kestra_dbt_project
description: dbtドキュメントを生成してS3に格納するFlow

labels:
  type: common_root
  error: default_failed

retry:
  maxAttempts: 3
  behavior: CREATE_NEW_EXECUTION # or RETRY_FAILED_TASK 
  type: constant
  interval: PT1S
  
inputs:
  - id: branch
    type: STRING
    defaults: proj-job-

concurrency:
  behavior: QUEUE
  limit: 1

tasks:

  - id: if_branch_isnot_common_root
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.branch != 'common_root' }}"
    # 共通部品以外のプロジェクトのsyncの場合はdbt docs generateする
    then:

    - id: dbt

      type: io.kestra.plugin.core.flow.WorkingDirectory
      tasks:

        - id: clone_dbt_docs_generate
          type: io.kestra.plugin.dbt.cli.DbtCLI
          commands:
            - dbt docs generate --static
          outputFiles:
            - kestra_dbt_project/enterprise_data_products/target/static_index.html

        - id: S3_upload
          type: io.kestra.plugin.aws.s3.Upload
          from: "{{ outputs.clone_dbt_docs_generate['outputFiles']['kestra_dbt_project/enterprise_data_products/target/static_index.html'] }}"
          bucket: "{{ namespace.DBT_DOCS.S3_BUCKET }}"
          key: "{{ namespace.DBT_DOCS.BASE_PATH }}{{ inputs.branch }}/static_index.html"
          contentType: text/html
          region: ap-northeast-1
          
# git syncの完了をトリガーにdbt docs generateする（対象ブランチを取得する）
triggers:
  - id: flow_trigger
    type: io.kestra.plugin.core.trigger.Flow
    inputs:
      branch: "{{ trigger.outputs.target_branch }}"
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionLabels
        labels:
          dbt_docs: generate
      - type: io.kestra.plugin.core.condition.ExecutionNamespace
        namespace: "kestra_dbt_project"
        prefix: true
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - SUCCESS

# エラーログを出力
errors:
  - id: error_log
    type: io.kestra.plugin.core.debug.Return
    format: "{{ errorLogs()[0]['message'] }}"

outputs: 
  - id: output_error_log
    type: STRING
    value: "{{ outputs.error_log.value ?? 'No message found.' }}"
  - id: output_state
    type: STRING
    value: "{{ tasks.dbt.state ?? 'No state' }}"

# ログ出力
finally:
  - id: finally_log 
    type: io.kestra.plugin.core.log.Log
    message: 
      - "Git branch -> {{ namespace.GIT.BRANCH ?? inputs.branch }}"
      - "Path -> {{ namespace.DBT_DOCS.S3_BUCKET }}/{{ namespace.DBT_DOCS.BASE_PATH }}{{ inputs.branch }}/static_index.html"

disabled: false