id: dbt_elementary
namespace: kestra_dbt_project
description: elementaryドキュメントを生成してS3に格納するFlow

labels:
  type: common_root
  error: default_failed

retry:
  behavior: CREATE_NEW_EXECUTION # or RETRY_FAILED_TASK 
  type: exponential
  interval: PT5S
  maxAttempts: 7
  maxInterval: PT720S
  delayFactor: 30
  
concurrency:
  behavior: QUEUE
  limit: 1

inputs:
  - id: build
    type: BOOLEAN
    defaults: false
  - id: branch
    type: STRING
    required: false
    dependsOn:
      condition: "{{ namespace.ENV  == 'dev' }}"

tasks:
  
  - id: if_build_is_true
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.build == true }}"
    # 初回実行の場合
    then:

    - id: clone_dbt_run
      type: io.kestra.plugin.dbt.cli.DbtCLI
      commands:
        - dbt run
          --select elementary

  - id: elementary

    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_edr_report
        type: io.kestra.plugin.dbt.cli.DbtCLI
        commands:
          - pip install 'elementary-data[snowflake]'
          - edr report
            --profiles-dir .
        env:
          DBT_SNOWFLAKE_ACCOUNT: "{{ namespace.DBT.SNOWFLAKE_ACCOUNT }}"
          DBT_SNOWFLAKE_USER: "{{ namespace.DBT.SNOWFLAKE_USER }}"
          SNOWFLAKE_PRIVATE_KEY_DBT: "{{ secret('SNOWFLAKE_PRIVATE_KEY_DBT') }}"
          SNOWFLAKE_PRIVATE_KEY_PASSPHRASE_DBT: "{{ secret('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE_DBT') }}"
          DBT_SNOWFLAKE_ROLE: "{{ namespace.DBT.SNOWFLAKE_ROLE }}"
        outputFiles:
          - kestra_dbt_project/enterprise_data_products/edr_target/elementary_report.html

      - id: S3_upload
        type: io.kestra.plugin.aws.s3.Upload
        from: "{{ outputs.clone_edr_report['outputFiles']['kestra_dbt_project/enterprise_data_products/edr_target/elementary_report.html'] }}"
        bucket: "{{ namespace.DBT_DOCS.S3_BUCKET }}"
        key: "{{ namespace.DBT_DOCS.BASE_PATH }}edr_report/elementary_report.html"
        contentType: text/html
        region: ap-northeast-1


triggers:
  - id: flow_trigger_stg
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.Expression
        expression: "{{ namespace.ENV  == 'stg' }}"
      - type: io.kestra.plugin.core.condition.ExecutionLabels
        labels:
          dbt: build
      - type: io.kestra.plugin.core.condition.ExecutionNamespace
        namespace: "kestra_dbt_project"
        prefix: true
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - FAILED
          - WARNING
          - SUCCESS
  - id: schedule_prod
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 * * * *"
    timezone: Asia/Tokyo
    conditions:
      - type: io.kestra.plugin.core.condition.Expression
        expression: "{{ namespace.ENV  == 'prod' }}"

# エラーログを出力
errors:
  - id: error_log
    type: io.kestra.plugin.core.debug.Return
    format: "{{ errorLogs()[0]['message'] }}"

outputs: 
  - id: output_error_log
    type: STRING
    value: "{{ outputs.error_log.value ?? 'No message found.' }}"
  - id: output_state
    type: STRING
    value: "{{ tasks.elementary.state ?? 'No state' }}"
    
disabled: false