id: dbt-snowflake-build-triger-after
namespace: kestra_dbt_project.proj-job-kuboi

labels:
  error: default

tasks:
  - id: dbt

    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        branch: kestra-trial-kuboi

      - id: dbt_build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        commands:
          - dbt build --select +stg_tbdaikl --vars '{"DBT_JOB_NAME":"_chekk"}' --project-dir "{{ namespace.DBT.PROJ_DIR }}"

triggers:
  - id: flow_trigger
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionFlow
        namespace: trial-kuboi2
        flowId: python_commands
    states:
     - SUCCESS