id: dbt-snowflake-snapshot
namespace: kestra_dbt_project.proj-job-kuboi
tasks:
  - id: git
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: http://ip-100-80-0-103.ap-northeast-1.compute.internal/enterprise_orchestration_products/kestra_dbt_project.git
        branch: proj-job-kuboi
        username: e.kuboi
        password: 11Nmoka30
      - id: dbt
        type: io.kestra.plugin.dbt.cli.DbtCLI
        taskRunner:
          type: io.kestra.plugin.ee.kubernetes.runner.Kubernetes
          namespace: kestra
          config:
            caCertData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTXlpZGpMWHFnN2d3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBM01EY3dNakl6TVRaYUZ3MHpOVEEzTURVd01qSTRNVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURBMmtTMWplKzM4UktLdUkvVU9rVlpNM2JRWTdnN2VFc2d3YWxXdjk3djk0VThDVnlLa00zeFdDcFIKT0JqcDBmNGRnak1aWE5Qek5YK0NhZ2dWanRnOWFzSnp0eXRxaGRuTmFTdCtYaVgxcGVobkJCWjVaamRlcGJJKwphSnVDemZUZEdEb21YMzJ4MmtPbzFyWG1VYVNOQW00Q09aRXRvNTQ2SEFpejZRMEJWdUJldmkvVldIbEwwa2tlClAzU2FVMGw1b1NzMnhVdXRNWlA4dGFWa2RSNjR2UVZrWCtvbW9IYThRb3JESEJuWm54SFUzNlhEVGJRazZtWWsKelFtUzJwRnBqZzJzMGtZWmRKMlNPNXJSelo4d2E1WHBsMG02UEpZQkRqVUtEV1NxWUJvTXMvZEFGbW50bTROYQp5dXJGV3J5emd3UmdKdDUxZklUbGxpVXB5QWh0QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSWVk3YVhlQ0ZsWElOcUZ5UER5Z3FUczFDaS9EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlhvd3l1R3ZEdApyUjNtQXQ1b0RGNEc0MmVmUDBqVFBuVGJKUHZqQkd3UjhQYVZMWTQ5UitrRjFrcEM1M3lzUjg0cFFXMFMwLzcrCnRVd0dtRE5XK2ZkemtMNTRYNGdSSFVraEdaQWpMZURCUGtsR2w1WExISXlaZWxneDNzRndKeitNaGdzZ09pSWIKWUpDZThPSlBpWWlrdjlKc2pxYWJZQkwzQStPbVRZL084c01HWmxYcVpPSy9QQVJLWmhpVjhuWGE3N0p2K25GZwpDaDltajN0MDAxb2UyYmFMaW1WaVNYYi9TZmIyOERKMmtLeU00dlVrSUp2eHZ4dEM4WUtIc1BocTlyY0FNOEVnCktYZ1ZKY2tqQVo1a01uZ1JXMm5UVTJQdS9IUU9GcG9iRE5oN2ttWDdVb2ZRdFVLVUg3QW5PaHlKWXRwb3JnTGkKaXZOWDZGODMrQmpECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            masterUrl: https://792D6FD8199A980FC7CC517D69717F34.gr7.ap-northeast-1.eks.amazonaws.com
            username: arn:aws:eks:ap-northeast-1:248810166614:cluster/dajp1-dxpf-edp-eks-kestra01
            oauthToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJlODE0ZWNmNWIyZTEyY2JjYTNmYmI1M2MwZDBhMzZjNTkyMjU3ODIifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTc4MzY1NjUzMSwiaWF0IjoxNzUyMTIwNTMxLCJpc3MiOiJodHRwczovL29pZGMuZWtzLmFwLW5vcnRoZWFzdC0xLmFtYXpvbmF3cy5jb20vaWQvNzkyRDZGRDgxOTlBOTgwRkM3Q0M1MTdENjk3MTdGMzQiLCJqdGkiOiI1ZWM1MTQ0Mi03Mjk3LTQ0ZTYtOTc4Ni0wNjFjZGM2OWZlODgiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Imtlc3RyYSIsIm5vZGUiOnsibmFtZSI6ImlwLTEwMC04MC0xLTE4MS5hcC1ub3J0aGVhc3QtMS5jb21wdXRlLmludGVybmFsIiwidWlkIjoiZTc5ZTBlZDAtOWFkNi00ZGUzLWFiZmQtOTM0Yjc4MmVhZDc5In0sInBvZCI6eyJuYW1lIjoia2VzdHJhLXdvcmtlci03NGY4ZDU5NzRmLWpodzRnIiwidWlkIjoiNzQyZWEzNDctMGE4YS00M2RlLTkwNjgtODJhNGQyNDNlNzFkIn0sInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJrZXN0cmEtc2EiLCJ1aWQiOiJjMzFlMTQ4MC1hOGI3LTQ3NmYtYWZmNC05YTk5NWU4NWNiZWIifSwid2FybmFmdGVyIjoxNzUyMTI0MTM4fSwibmJmIjoxNzUyMTIwNTMxLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a2VzdHJhOmtlc3RyYS1zYSJ9.BPXyr9sHRtl-gjAuMzdj9-2sUM698xut1iH0HRGG_t4ml2z9JBf9o8dE-_bdlonJ6KUR9-rcVNkjFb6h2Fk8AfLgGmLsuhunfPQQdeMLxmkKteMJuC9ToGh9gTky5W8nYErvF028nWPdJ7RnSh4VtyhJawwvCPb0Molnz71ERqbxZJFxnguSzdSyR5kHqH9x18AGyTl-uRX-xvtHOlIakgKTQgnzOf2INfDGuDLItstDjtCcB_6JevVEfAbxX7pA3YFgsi4k1rONUzsRM92LrP_suMYPg5zPTfc6jT-qF6jiULASiQxdema1l4SAWoGJOSPu_hWTfJ7jux3pWH9WfQ
        projectDir: enterprise_data_products
        profiles: |
          enterprise_data_products:
            target: dev
            outputs:
              dev:
                account: "nw21470.ap-northeast-1.privatelink"
                database: "datamart_db"
                password: "Password123"
                role: "dbt_role"
                schema: "public"
                threads: 16
                type: snowflake
                user: "dbt"
                warehouse: "dbt_default_wh"
        commands:
          - dbt deps --project-dir enterprise_data_products
          - dbt snapshot --select scd_cvn18nosiodrjyoho_initial scd_cvn18nosiodrjyoho_latest scd_cvn18nosiodrjyoho_previous --project-dir enterprise_data_products
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "00 15 * * *"