id: dbt-snowflake-build-s3-trigger
namespace: kestra_dbt_project.proj-job-kuboi

labels:
  error: default

tasks:
  - id: dbt

    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        branch: kestra-trial-kuboi

      - id: dbt_build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        commands:
          - dbt build --select +stg_tbchznl --vars '{"DBT_JOB_NAME":"_chekk"}' --project-dir "{{ namespace.DBT.PROJ_DIR }}"

  - id: set_kv_count
    type: io.kestra.plugin.core.kv.Set
    key: timestamp_dxbofl99
    value: "{{ now() | date('yyyyMMdd', timeZone='UTC') }}"

triggers:
  - id: s3_trigger
    type: io.kestra.plugin.aws.s3.Trigger
    interval: "PT5M"
    bucket: "dajp1-dxpf-edp-dev-s3-valuechain01"
    prefix: "BufferFolder/TAS/CHUZANF/DXCHZN99_{{ now() | date('yyyyMMdd', timeZone='UTC') }}"
    conditions:
      - type: io.kestra.plugin.core.condition.Expression
        expression: "{{ kv('timestamp_dxbofl99') != now() | date('yyyyMMdd', timeZone='UTC') }}"