id: dbt-snowflake-snapshot
namespace: kestra_dbt_project.proj-job-kuboi
tasks:
  - id: git
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: http://ip-100-80-0-103.ap-northeast-1.compute.internal/enterprise_orchestration_products/kestra_dbt_project.git
        branch: proj-job-kuboi
        username: e.kuboi
        password: 11Nmoka30
      - id: dbt
        type: io.kestra.plugin.dbt.cli.DbtCLI
        taskRunner:
          type: io.kestra.plugin.ee.kubernetes.runner.Kubernetes
          config:
            caCertData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTXlpZGpMWHFnN2d3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBM01EY3dNakl6TVRaYUZ3MHpOVEEzTURVd01qSTRNVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURBMmtTMWplKzM4UktLdUkvVU9rVlpNM2JRWTdnN2VFc2d3YWxXdjk3djk0VThDVnlLa00zeFdDcFIKT0JqcDBmNGRnak1aWE5Qek5YK0NhZ2dWanRnOWFzSnp0eXRxaGRuTmFTdCtYaVgxcGVobkJCWjVaamRlcGJJKwphSnVDemZUZEdEb21YMzJ4MmtPbzFyWG1VYVNOQW00Q09aRXRvNTQ2SEFpejZRMEJWdUJldmkvVldIbEwwa2tlClAzU2FVMGw1b1NzMnhVdXRNWlA4dGFWa2RSNjR2UVZrWCtvbW9IYThRb3JESEJuWm54SFUzNlhEVGJRazZtWWsKelFtUzJwRnBqZzJzMGtZWmRKMlNPNXJSelo4d2E1WHBsMG02UEpZQkRqVUtEV1NxWUJvTXMvZEFGbW50bTROYQp5dXJGV3J5emd3UmdKdDUxZklUbGxpVXB5QWh0QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSWVk3YVhlQ0ZsWElOcUZ5UER5Z3FUczFDaS9EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlhvd3l1R3ZEdApyUjNtQXQ1b0RGNEc0MmVmUDBqVFBuVGJKUHZqQkd3UjhQYVZMWTQ5UitrRjFrcEM1M3lzUjg0cFFXMFMwLzcrCnRVd0dtRE5XK2ZkemtMNTRYNGdSSFVraEdaQWpMZURCUGtsR2w1WExISXlaZWxneDNzRndKeitNaGdzZ09pSWIKWUpDZThPSlBpWWlrdjlKc2pxYWJZQkwzQStPbVRZL084c01HWmxYcVpPSy9QQVJLWmhpVjhuWGE3N0p2K25GZwpDaDltajN0MDAxb2UyYmFMaW1WaVNYYi9TZmIyOERKMmtLeU00dlVrSUp2eHZ4dEM4WUtIc1BocTlyY0FNOEVnCktYZ1ZKY2tqQVo1a01uZ1JXMm5UVTJQdS9IUU9GcG9iRE5oN2ttWDdVb2ZRdFVLVUg3QW5PaHlKWXRwb3JnTGkKaXZOWDZGODMrQmpECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            masterUrl: https://792D6FD8199A980FC7CC517D69717F34.gr7.ap-northeast-1.eks.amazonaws.com
            username: arn:aws:eks:ap-northeast-1:248810166614:cluster/dajp1-dxpf-edp-eks-kestra01
            oauthToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJlODE0ZWNmNWIyZTEyY2JjYTNmYmI1M2MwZDBhMzZjNTkyMjU3ODIifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTc4MzQxMjYwNSwiaWF0IjoxNzUxODc2NjA1LCJpc3MiOiJodHRwczovL29pZGMuZWtzLmFwLW5vcnRoZWFzdC0xLmFtYXpvbmF3cy5jb20vaWQvNzkyRDZGRDgxOTlBOTgwRkM3Q0M1MTdENjk3MTdGMzQiLCJqdGkiOiIxNjMzZjQ0NS0yY2FkLTQ5ZWUtOTdmZi1jM2I3N2JiYTM0MjQiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Imtlc3RyYSIsIm5vZGUiOnsibmFtZSI6ImlwLTEwMC04MC0xLTkxLmFwLW5vcnRoZWFzdC0xLmNvbXB1dGUuaW50ZXJuYWwiLCJ1aWQiOiJlMmU4NDNiNy1lMWQzLTQwNzUtYWYzNi01MWUwOGFiMzkwOWMifSwicG9kIjp7Im5hbWUiOiJrZXN0cmEtd29ya2VyLTY5NmY4NmI1N2MtY2YyajciLCJ1aWQiOiJlMmVlYmMzZi0xM2RmLTQyMTMtOGM5MS04MjNlZWZmN2I1ZGYifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6Imtlc3RyYS1zYSIsInVpZCI6ImMzMWUxNDgwLWE4YjctNDc2Zi1hZmY0LTlhOTk1ZTg1Y2JlYiJ9LCJ3YXJuYWZ0ZXIiOjE3NTE4ODAyMTJ9LCJuYmYiOjE3NTE4NzY2MDUsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprZXN0cmE6a2VzdHJhLXNhIn0.FNR92f0AMIF6gw6Jau_qerdweTACjFFKaZ2jPAHMfFl8Ue27eeRM5nK45D0VKJJOIGX_YeKsw5_EEP9IP5-f-As02tSBI9OJbTc1dDiRerVQUPt5evps3dMU5M8sR9OV0v12n3DrOyTvaGlWT1imZ40nBS_UD-pSx5BzKLtNyKF2hWdh8LlxoiZH3JazAA9bE07JGKY8I3qR-bQJ5fvccLqF4GFPkmVtIjQfoJauTD60330b6WYEJIQIoFWzEyZJym8k5UllL3Cqx-peagpsJ04npFfbmSKRlj9r-MlVuRSlO0EQmUMVc99RebSKpverLy1Md5ZZeYUGPHWfDmO5TA
        projectDir: enterprise_data_products
        profiles: |
          enterprise_data_products:
            target: dev
            outputs:
              dev:
                account: "nw21470.ap-northeast-1.aws"
                database: "datamart_db"
                password: "Password123"
                role: "dbt_role"
                schema: "public"
                threads: 16
                type: snowflake
                user: "dbt"
                warehouse: "dbt_default_wh"
        commands:
          - dbt deps --project-dir enterprise_data_products
          - dbt snapshot --select scd_cvn18nosiodrjyoho_initial scd_cvn18nosiodrjyoho_latest scd_cvn18nosiodrjyoho_previous --project-dir enterprise_data_products
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "00 15 * * *"