id: dbt-snowflake-build-table-trigger
namespace: kestra_dbt_project.proj-job-kuboi

labels:
  error: default

tasks:
  - id: dbt

    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        branch: kestra-trial-kuboi

      - id: dbt_build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        commands:
          - dbt build --select +stg_tbbofll --vars '{"DBT_JOB_NAME":"_chekk"}' --project-dir "{{ namespace.DBT.PROJ_DIR }}"

  - id: select
    type: io.kestra.plugin.jdbc.snowflake.Query
    sql: select count(*) as cnt from snowpipe_db.valuechain.dxbofl99

  - id: set_kv_count
    type: io.kestra.plugin.core.kv.Set
    key: count_dxbofl99
    value: "{{ outputs.select.rows[0].CNT }}"

triggers:
  - id: snowflake_trigger
    type: io.kestra.plugin.jdbc.snowflake.Trigger
    interval: "PT5M"
    sql: "select count(*) from snowpipe_db.valuechain.dxbofl99 having count(*) > {{ kv('count_dxbofl99') }};"