{% snapshot scd_noukikanri_atop %}
{{
    config(
        unique_key="concat_ws('-',
                    iff( syoritype is null , '',  syoritype), --nullの場合はブランクに置き換える処理
                    iff( tyotathb is null , '',  tyotathb), --nullの場合はブランクに置き換える処理
                    iff( kaknoukbn is null , '',  kaknoukbn), --nullの場合はブランクに置き換える処理
                    iff( srsirskcd is null , '',  srsirskcd), --nullの場合はブランクに置き換える処理
                    iff( brsirskcd is null , '',  brsirskcd), --nullの場合はブランクに置き換える処理
                    iff( kanbnkbn is null , '',  kanbnkbn), --nullの場合はブランクに置き換える処理
                    iff( nonyuym is null , '',  nonyuym), --nullの場合はブランクに置き換える処理
                    iff( hniraisugokn is null , 0,  hniraisugokn), --nullの場合は0に置き換える処理
                    iff( kriraisugokn7 is null , 0,  kriraisugokn7), --nullの場合は0に置き換える処理
                    iff( hdsugokn is null , 0,  hdsugokn), --nullの場合は0に置き換える処理
                    iff( nnjsksugokn is null , 0,  nnjsksugokn), --nullの場合は0に置き換える処理
                    iff( minyusenkosunm3 is null , 0,  minyusenkosunm3), --nullの場合は0に置き換える処理
                    iff( minyusenkosunm4 is null , 0,  minyusenkosunm4), --nullの場合は0に置き換える処理
                    iff( minyusenkosunm5 is null , 0,  minyusenkosunm5), --nullの場合は0に置き換える処理
                    iff( henkmaemd1 is null , '',  henkmaemd1), --nullの場合はブランクに置き換える処理
                    iff( henkmaemd2 is null , '',  henkmaemd2), --nullの場合はブランクに置き換える処理
                    iff( henkmaemd3 is null , '',  henkmaemd3), --nullの場合はブランクに置き換える処理
                    iff( henkmaemd4 is null , '',  henkmaemd4), --nullの場合はブランクに置き換える処理
                    iff( henkmaemd5 is null , '',  henkmaemd5), --nullの場合はブランクに置き換える処理
                    iff( henkmaemd6 is null , '',  henkmaemd6), --nullの場合はブランクに置き換える処理
                    iff( ntkadoflg_1d is null , '',  ntkadoflg_1d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_1d is null , 0,  ntnniraisun_1d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_1d is null , '',  ntnukidasflg_1d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_1d is null , 0,  nthenkhdsun6_1d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_1d is null , 0,  ntnnjisseksu_1d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_2d is null , '',  ntkadoflg_2d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_2d is null , 0,  ntnniraisun_2d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_2d is null , '',  ntnukidasflg_2d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_2d is null , 0,  nthenkhdsun6_2d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_2d is null , 0,  ntnnjisseksu_2d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_3d is null , '',  ntkadoflg_3d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_3d is null , 0,  ntnniraisun_3d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_3d is null , '',  ntnukidasflg_3d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_3d is null , 0,  nthenkhdsun6_3d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_3d is null , 0,  ntnnjisseksu_3d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_4d is null , '',  ntkadoflg_4d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_4d is null , 0,  ntnniraisun_4d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_4d is null , '',  ntnukidasflg_4d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_4d is null , 0,  nthenkhdsun6_4d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_4d is null , 0,  ntnnjisseksu_4d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_5d is null , '',  ntkadoflg_5d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_5d is null , 0,  ntnniraisun_5d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_5d is null , '',  ntnukidasflg_5d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_5d is null , 0,  nthenkhdsun6_5d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_5d is null , 0,  ntnnjisseksu_5d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_6d is null , '',  ntkadoflg_6d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_6d is null , 0,  ntnniraisun_6d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_6d is null , '',  ntnukidasflg_6d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_6d is null , 0,  nthenkhdsun6_6d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_6d is null , 0,  ntnnjisseksu_6d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_7d is null , '',  ntkadoflg_7d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_7d is null , 0,  ntnniraisun_7d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_7d is null , '',  ntnukidasflg_7d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_7d is null , 0,  nthenkhdsun6_7d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_7d is null , 0,  ntnnjisseksu_7d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_8d is null , '',  ntkadoflg_8d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_8d is null , 0,  ntnniraisun_8d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_8d is null , '',  ntnukidasflg_8d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_8d is null , 0,  nthenkhdsun6_8d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_8d is null , 0,  ntnnjisseksu_8d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_9d is null , '',  ntkadoflg_9d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_9d is null , 0,  ntnniraisun_9d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_9d is null , '',  ntnukidasflg_9d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_9d is null , 0,  nthenkhdsun6_9d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_9d is null , 0,  ntnnjisseksu_9d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_10d is null , '',  ntkadoflg_10d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_10d is null , 0,  ntnniraisun_10d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_10d is null , '',  ntnukidasflg_10d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_10d is null , 0,  nthenkhdsun6_10d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_10d is null , 0,  ntnnjisseksu_10d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_11d is null , '',  ntkadoflg_11d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_11d is null , 0,  ntnniraisun_11d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_11d is null , '',  ntnukidasflg_11d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_11d is null , 0,  nthenkhdsun6_11d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_11d is null , 0,  ntnnjisseksu_11d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_12d is null , '',  ntkadoflg_12d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_12d is null , 0,  ntnniraisun_12d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_12d is null , '',  ntnukidasflg_12d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_12d is null , 0,  nthenkhdsun6_12d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_12d is null , 0,  ntnnjisseksu_12d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_13d is null , '',  ntkadoflg_13d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_13d is null , 0,  ntnniraisun_13d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_13d is null , '',  ntnukidasflg_13d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_13d is null , 0,  nthenkhdsun6_13d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_13d is null , 0,  ntnnjisseksu_13d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_14d is null , '',  ntkadoflg_14d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_14d is null , 0,  ntnniraisun_14d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_14d is null , '',  ntnukidasflg_14d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_14d is null , 0,  nthenkhdsun6_14d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_14d is null , 0,  ntnnjisseksu_14d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_15d is null , '',  ntkadoflg_15d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_15d is null , 0,  ntnniraisun_15d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_15d is null , '',  ntnukidasflg_15d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_15d is null , 0,  nthenkhdsun6_15d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_15d is null , 0,  ntnnjisseksu_15d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_16d is null , '',  ntkadoflg_16d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_16d is null , 0,  ntnniraisun_16d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_16d is null , '',  ntnukidasflg_16d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_16d is null , 0,  nthenkhdsun6_16d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_16d is null , 0,  ntnnjisseksu_16d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_17d is null , '',  ntkadoflg_17d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_17d is null , 0,  ntnniraisun_17d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_17d is null , '',  ntnukidasflg_17d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_17d is null , 0,  nthenkhdsun6_17d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_17d is null , 0,  ntnnjisseksu_17d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_18d is null , '',  ntkadoflg_18d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_18d is null , 0,  ntnniraisun_18d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_18d is null , '',  ntnukidasflg_18d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_18d is null , 0,  nthenkhdsun6_18d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_18d is null , 0,  ntnnjisseksu_18d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_19d is null , '',  ntkadoflg_19d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_19d is null , 0,  ntnniraisun_19d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_19d is null , '',  ntnukidasflg_19d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_19d is null , 0,  nthenkhdsun6_19d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_19d is null , 0,  ntnnjisseksu_19d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_20d is null , '',  ntkadoflg_20d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_20d is null , 0,  ntnniraisun_20d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_20d is null , '',  ntnukidasflg_20d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_20d is null , 0,  nthenkhdsun6_20d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_20d is null , 0,  ntnnjisseksu_20d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_21d is null , '',  ntkadoflg_21d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_21d is null , 0,  ntnniraisun_21d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_21d is null , '',  ntnukidasflg_21d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_21d is null , 0,  nthenkhdsun6_21d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_21d is null , 0,  ntnnjisseksu_21d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_22d is null , '',  ntkadoflg_22d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_22d is null , 0,  ntnniraisun_22d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_22d is null , '',  ntnukidasflg_22d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_22d is null , 0,  nthenkhdsun6_22d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_22d is null , 0,  ntnnjisseksu_22d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_23d is null , '',  ntkadoflg_23d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_23d is null , 0,  ntnniraisun_23d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_23d is null , '',  ntnukidasflg_23d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_23d is null , 0,  nthenkhdsun6_23d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_23d is null , 0,  ntnnjisseksu_23d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_24d is null , '',  ntkadoflg_24d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_24d is null , 0,  ntnniraisun_24d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_24d is null , '',  ntnukidasflg_24d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_24d is null , 0,  nthenkhdsun6_24d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_24d is null , 0,  ntnnjisseksu_24d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_25d is null , '',  ntkadoflg_25d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_25d is null , 0,  ntnniraisun_25d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_25d is null , '',  ntnukidasflg_25d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_25d is null , 0,  nthenkhdsun6_25d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_25d is null , 0,  ntnnjisseksu_25d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_26d is null , '',  ntkadoflg_26d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_26d is null , 0,  ntnniraisun_26d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_26d is null , '',  ntnukidasflg_26d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_26d is null , 0,  nthenkhdsun6_26d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_26d is null , 0,  ntnnjisseksu_26d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_27d is null , '',  ntkadoflg_27d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_27d is null , 0,  ntnniraisun_27d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_27d is null , '',  ntnukidasflg_27d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_27d is null , 0,  nthenkhdsun6_27d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_27d is null , 0,  ntnnjisseksu_27d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_28d is null , '',  ntkadoflg_28d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_28d is null , 0,  ntnniraisun_28d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_28d is null , '',  ntnukidasflg_28d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_28d is null , 0,  nthenkhdsun6_28d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_28d is null , 0,  ntnnjisseksu_28d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_29d is null , '',  ntkadoflg_29d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_29d is null , 0,  ntnniraisun_29d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_29d is null , '',  ntnukidasflg_29d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_29d is null , 0,  nthenkhdsun6_29d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_29d is null , 0,  ntnnjisseksu_29d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_30d is null , '',  ntkadoflg_30d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_30d is null , 0,  ntnniraisun_30d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_30d is null , '',  ntnukidasflg_30d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_30d is null , 0,  nthenkhdsun6_30d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_30d is null , 0,  ntnnjisseksu_30d), --nullの場合は0に置き換える処理
                    iff( ntkadoflg_31d is null , '',  ntkadoflg_31d), --nullの場合はブランクに置き換える処理
                    iff( ntnniraisun_31d is null , 0,  ntnniraisun_31d), --nullの場合は0に置き換える処理
                    iff( ntnukidasflg_31d is null , '',  ntnukidasflg_31d), --nullの場合はブランクに置き換える処理
                    iff( nthenkhdsun6_31d is null , 0,  nthenkhdsun6_31d), --nullの場合は0に置き換える処理
                    iff( ntnnjisseksu_31d is null , 0,  ntnnjisseksu_31d), --nullの場合は0に置き換える処理
                    ldts)",

        strategy='timestamp',
        updated_at='ldts',
        invalidate_hard_deletes=true,
    )
}}
select * from {{ ref('stg_noukikanri_atop') }}
{% endsnapshot %}