{{
    config (
        materialized = 'incremental',
        unique_key = [
            'syasyu_cd',
            'sno',
            'syameicd',
            'ordertype',
            'nisgt',
            'kd_hbtgrcd',
            'hi_ktcd',
            'ctl_kt',
            'gaihncd',
            'utibrcd',
            'sn_spec01',
            'sn_spec02',
            'sn_spec03',
            'sn_spec04',
            'sn_spec05',
            'sn_spec06',
            'sn_spec07',
            'sn_spec08',
            'sn_spec09',
            'sn_spec10',
            'sn_spec11',
            'sn_spec12',
            'sn_spec13',
            'sn_spec14',
            'sn_spec15',
            'sn_spec16',
            'sn_spec17',
            'sn_spec18',
            'sn_spec19',
            'sn_spec20',
            'smkcd',
            'smkmeisai',
            'frmkbn',
            'kd_lotfg',
            'hi_kt',
            'lo_ktcd',
            'eg_kt',
            'mt_kt',
            'grade',
            'bodytype',
            'vin_wmi',
            'vin_vds',
            'mdlyr',
            'idline',
            'maker',
            'k_nen',
            ],
        incremental_strategy = 'merge'
    )
}}

with stg_seisankeikaku as (
    select
        mtkbn::varchar(1) as mtkbn,
        sms_syasyucd::varchar(4) as syasyu_cd,
        siyono::varchar(2) as sno,
        syameicd::varchar(2) as syameicd,
        odt::varchar(1) as ordertype,
        nisgt::varchar(1) as nisgt,
        kd_hbtgrcd::varchar(1) as kd_hbtgrcd,
        hi_ktcd::varchar(5) as hi_ktcd,
        ctl_kt::varchar(16) as ctl_kt,
        gaihncd::varchar(4) as gaihncd,
        utibrcd::varchar(4) as utibrcd,
        sn_spec01::varchar(10) as sn_spec01,
        sn_spec02::varchar(10) as sn_spec02,
        sn_spec03::varchar(10) as sn_spec03,
        sn_spec04::varchar(10) as sn_spec04,
        sn_spec05::varchar(10) as sn_spec05,
        sn_spec06::varchar(10) as sn_spec06,
        sn_spec07::varchar(10) as sn_spec07,
        sn_spec08::varchar(10) as sn_spec08,
        sn_spec09::varchar(10) as sn_spec09,
        sn_spec10::varchar(10) as sn_spec10,
        sn_spec11::varchar(10) as sn_spec11,
        sn_spec12::varchar(10) as sn_spec12,
        sn_spec13::varchar(10) as sn_spec13,
        sn_spec14::varchar(10) as sn_spec14,
        sn_spec15::varchar(10) as sn_spec15,
        sn_spec16::varchar(10) as sn_spec16,
        sn_spec17::varchar(10) as sn_spec17,
        sn_spec18::varchar(10) as sn_spec18,
        sn_spec19::varchar(10) as sn_spec19,
        sn_spec20::varchar(10) as sn_spec20,
        smkcd::varchar(3) as smkcd,
        smkmeisai::varchar(1) as smkmeisai,
        frmkbn::varchar(3) as frmkbn,
        kd_lotfg::varchar(2) as kd_lotfg,
        hi_kt::varchar(15) as hi_kt,
        lo_ktcd::varchar(5) as lo_ktcd,
        eg_kt::varchar(7) as eg_kt,
        mt_kt::varchar(6) as mt_kt,
        grade::varchar(3) as grade,
        bodytype::varchar(6) as bodytype,
        vin_wmi::varchar(3) as vin_wmi,
        vin_vds::varchar(6) as vin_vds,
        mdlyr::varchar(1) as mdlyr,
        idline::varchar(2) as idline,
        maker::varchar(4) as maker,
        k_nen::varchar(4) as k_nen,
        k_tdai_01::number(7) as k_tdai01,
        k_tdai_02::number(7) as k_tdai02,
        k_tdai_03::number(7) as k_tdai03,
        k_tdai_04::number(7) as k_tdai04,
        k_tdai_05::number(7) as k_tdai05,
        k_tdai_06::number(7) as k_tdai06,
        k_tdai_07::number(7) as k_tdai07,
        k_tdai_08::number(7) as k_tdai08,
        k_tdai_09::number(7) as k_tdai09,
        k_tdai_10::number(7) as k_tdai10,
        k_tdai_11::number(7) as k_tdai11,
        k_tdai_12::number(7) as k_tdai12,
        k_tuki::varchar(2) as k_tuki,
        k_n_1_dai::number(7) as k_n1dai,
        k_n_2_dai::number(7) as k_n2dai,
        k_ndai_01::number(5) as k_ndai01,
        k_ndai_02::number(5) as k_ndai02,
        k_ndai_03::number(5) as k_ndai03,
        k_ndai_04::number(5) as k_ndai04,
        k_ndai_05::number(5) as k_ndai05,
        k_ndai_06::number(5) as k_ndai06,
        k_ndai_07::number(5) as k_ndai07,
        k_ndai_08::number(5) as k_ndai08,
        k_ndai_09::number(5) as k_ndai09,
        k_ndai_10::number(5) as k_ndai10,
        k_ndai_11::number(5) as k_ndai11,
        k_ndai_12::number(5) as k_ndai12,
        k_ndai_13::number(5) as k_ndai13,
        k_ndai_14::number(5) as k_ndai14,
        k_ndai_15::number(5) as k_ndai15,
        k_ndai_16::number(5) as k_ndai16,
        k_ndai_17::number(5) as k_ndai17,
        k_ndai_18::number(5) as k_ndai18,
        k_ndai_19::number(5) as k_ndai19,
        k_ndai_20::number(5) as k_ndai20,
        k_ndai_21::number(5) as k_ndai21,
        k_ndai_22::number(5) as k_ndai22,
        k_ndai_23::number(5) as k_ndai23,
        k_ndai_24::number(5) as k_ndai24,
        k_ndai_25::number(5) as k_ndai25,
        k_ndai_26::number(5) as k_ndai26,
        k_ndai_27::number(5) as k_ndai27,
        k_ndai_28::number(5) as k_ndai28,
        k_ndai_29::number(5) as k_ndai29,
        k_ndai_30::number(5) as k_ndai30,
        k_ndai_31::number(5) as k_ndai31,
        createuser::varchar(13) as createuser,
        try_to_timestamp_ntz(createtime, 'yyyy/mm/dd hh24:mi:ss.ff9')	as createtime, -- timestamp型
        updateuser::varchar(13) as updateuser,
        try_to_timestamp_ntz(updatetime, 'yyyy/mm/dd hh24:mi:ss.ff9') as updatetime, -- timestamp型
        ldts,
        line_number,
        rank() over(
                partition by
                    syasyu_cd,
                    sno,
                    syameicd,
                    ordertype,
                    nisgt,
                    kd_hbtgrcd,
                    hi_ktcd,
                    ctl_kt,
                    gaihncd,
                    utibrcd,
                    sn_spec01,
                    sn_spec02,
                    sn_spec03,
                    sn_spec04,
                    sn_spec05,
                    sn_spec06,
                    sn_spec07,
                    sn_spec08,
                    sn_spec09,
                    sn_spec10,
                    sn_spec11,
                    sn_spec12,
                    sn_spec13,
                    sn_spec14,
                    sn_spec15,
                    sn_spec16,
                    sn_spec17,
                    sn_spec18,
                    sn_spec19,
                    sn_spec20,
                    smkcd,
                    smkmeisai,
                    frmkbn,
                    kd_lotfg,
                    hi_kt,
                    lo_ktcd,
                    eg_kt,
                    mt_kt,
                    grade,
                    bodytype,
                    vin_wmi,
                    vin_vds,
                    mdlyr,
                    idline,
                    maker,
                    k_nen
                order by ldts desc, line_number desc
            ) aggkey
        from {{ref('substr_da5a220a')}}

        {% if is_incremental() %}
            where ldts > (select max(ldts) from {{ this }})
        {% endif %}

)
select * exclude(mtkbn, aggkey, line_number) from stg_seisankeikaku where aggkey = 1 and mtkbn = 'C'