{{ config(
materialized='incremental',
incremental_strategy = 'append',
pre_hook = "
{% if is_incremental() %}
delete from {{this}}
{% endif %}
"
) }}

with stg_jikkokeikaku as (
select 
send_date::varchar(20) as send_date,
ym::varchar(7) as ym,
year::varchar(4) as year,
month::varchar(2) as month,
to_number(jpn_local_div)::number(38,0) as jpn_local_div,
jpn_local::varchar(255) as jpn_local,
areacd::varchar(1) as areacd,
area::varchar(10) as area,
area_display_name::varchar(255) as area_display_name,
country_cd::varchar(3) as country_cd,
country::varchar(255) as country,
psc::varchar(2) as psc,
affiliate_cd::varchar(2) as affiliate_cd,
affiliate::varchar(255) as affiliate,
affiliate_e::varchar(255) as affiliate_e,
plant_cd::varchar(2) as plant_cd,
plant::varchar(255) as plant,
plant_e::varchar(255) as plant_e,
line_cd::varchar(1) as line_cd,
line::varchar(255) as line,
line_e::varchar(255) as line_e,
geoss_line::varchar(5) as geoss_line,
shimukechi_cd::varchar(4) as shimukechi_cd,
id::varchar(2) as id,
syasyu_cd::varchar(4) as syasyu_cd,
daily_report_car_grcd::varchar(10) as daily_report_car_grcd,
daily_report_car_gr::varchar(255) as daily_report_car_gr,
sno::varchar(2) as sno,
syamei::varchar(2) as syamei,
to_number(model_name_cd)::number(38,0) as model_name_cd,
to_number(unit_cd)::number(38,0) as unit_cd,
unit::varchar(255) as unit,
to_number(dom_exp_cd)::number(38,0) as dom_exp_cd,
dom_exp::varchar(255) as dom_exp,
to_number(monthly_total)::number(38,0) as monthly_total,
to_number(daily_total)::number(38,0) as daily_total,
to_number(monthly_minus_daily)::number(38,0) as monthly_minus_daily,
to_number(monthly_nqc)::number(38,0) as monthly_nqc,
to_number(increase_decrease)::number(38,0) as increase_decrease,
to_number(erase_sf)::number(38,0) as erase_sf,
to_number(ringi)::number(38,0) as ringi,
to_number(goushi)::number(38,0) as goushi,
to_number(diff_adjustment)::number(38,0) as diff_adjustment,
to_number(between_process_last_m)::number(38,0) as between_process_last_m,
to_number(between_process)::number(38,0) as between_process,
to_number(advance_last_m)::number(38,0) as advance_last_m,
to_number(co_last_m)::number(38,0) as co_last_m,
to_number(advance_next_m)::number(38,0) as advance_next_m,
to_number(co_next_m)::number(38,0) as co_next_m,
to_number(vol_1st)::number(38,0) as vol_1st,
to_number(vol_2nd)::number(38,0) as vol_2nd,
to_number(vol_3rd)::number(38,0) as vol_3rd,
to_number(vol_4th)::number(38,0) as vol_4th,
to_number(vol_5th)::number(38,0) as vol_5th,
to_number(vol_6th)::number(38,0) as vol_6th,
to_number(vol_7th)::number(38,0) as vol_7th,
to_number(vol_8th)::number(38,0) as vol_8th,
to_number(vol_9th)::number(38,0) as vol_9th,
to_number(vol_10th)::number(38,0) as vol_10th,
to_number(vol_11th)::number(38,0) as vol_11th,
to_number(vol_12th)::number(38,0) as vol_12th,
to_number(vol_13th)::number(38,0) as vol_13th,
to_number(vol_14th)::number(38,0) as vol_14th,
to_number(vol_15th)::number(38,0) as vol_15th,
to_number(vol_16th)::number(38,0) as vol_16th,
to_number(vol_17th)::number(38,0) as vol_17th,
to_number(vol_18th)::number(38,0) as vol_18th,
to_number(vol_19th)::number(38,0) as vol_19th,
to_number(vol_20th)::number(38,0) as vol_20th,
to_number(vol_21st)::number(38,0) as vol_21st,
to_number(vol_22nd)::number(38,0) as vol_22nd,
to_number(vol_23rd)::number(38,0) as vol_23rd,
to_number(vol_24th)::number(38,0) as vol_24th,
to_number(vol_25th)::number(38,0) as vol_25th,
to_number(vol_26th)::number(38,0) as vol_26th,
to_number(vol_27th)::number(38,0) as vol_27th,
to_number(vol_28th)::number(38,0) as vol_28th,
to_number(vol_29th)::number(38,0) as vol_29th,
to_number(vol_30th)::number(38,0) as vol_30th,
to_number(vol_31st)::number(38,0) as vol_31st,
update_reason::varchar(500) as update_reason,
to_number(pcd_confirmed)::number(38,0) as pcd_confirmed,
pcd_decision_name::varchar(255) as pcd_decision_name,
employee_cd::varchar(10) as employee_cd,
employee::varchar(255) as employee,
confirmed_t::varchar(20) as confirmed_t,
to_number(last_m_total)::number(38,0) as last_m_total,
to_number(last_m_result)::number(38,0) as last_m_result,
to_number(area_sort)::number(38,0) as area_sort,
to_number(line_sort)::number(38,0) as line_sort,
to_number(d_rep_car_sort)::number(38,0) as d_rep_car_sort,
to_number(result_model_sort)::number(38,0) as result_model_sort,
to_number(unit_sort)::number(38,0) as unit_sort,
ldts::timestamp_ntz(9) as ldts,
row_number() over (
partition by
send_date,ym,jpn_local_div,areacd,country_cd,psc,affiliate_cd,plant_cd,line_cd,geoss_line,shimukechi_cd,id,syasyu_cd,daily_report_car_grcd,sno,syamei,model_name_cd,unit_cd,dom_exp_cd,update_reason,pcd_confirmed,employee_cd
order by line_number desc
) aggkey
from {{ source('snowpipe_db_supplydemand','raw_t_imp_plan') }}
where ldts = (select max(ldts) from {{ source('snowpipe_db_supplydemand','raw_t_imp_plan') }})
)
select * exclude(aggkey)
from stg_jikkokeikaku
where aggkey = 1
