DBT_SNOWFLAKE_PASS
GIT_PASS
X_TMC_CLIENT_ID_SMS
X_TMC_CLIENT_SECRET_SMS
X_TMC_ZDFW_COMPCODE_SMS
X_TMC_ZDFW_USERID_SMS
KUBERNETES_CA_CERT_DATA
KUBERNETES_OAUTH_TOKEN
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY