GIT_PASS
KUBERNETES_CA_CERT_DATA
SNOWFLAKE_PRIVATE_KEY_DBT
SNOWFLAKE_PRIVATE_KEY_KESTRA
SNOWFLAKE_PRIVATE_KEY_PASSPHRASE_DBT
SNOWFLAKE_PRIVATE_KEY_PASSPHRASE_KESTRA
X_TMC_CLIENT_ID_SMS
X_TMC_CLIENT_SECRET_SMS
X_TMC_ZDFW_COMPCODE_SMS
X_TMC_ZDFW_USERID_SMS