dagster_dbt:
  target: LOCAL
  outputs:
    LOCAL:
      type: snowflake
      account: nw21470.ap-northeast-1.aws

      # User/password auth
      user: dapj1.dagster_poc_sys_usr
      password: k5$Wj2(*pyeT
      role: EDP_INFRA_SANDBOX_JDBC
      database: EDP_INFRA_SANDBOX_DB
      warehouse: EDP_INFRA_SANDBOX_WH
      schema: PUBLIC

    DEV:
      type: snowflake
      account: nw21470.ap-northeast-1.privatelink

      # User/password auth
      user: dapj1.dagster_poc_sys_usr
      password: k5$Wj2(*pyeT
      role: EDP_INFRA_SANDBOX_JDBC
      database: EDP_INFRA_SANDBOX_DB
      warehouse: EDP_INFRA_SANDBOX_WH
      schema: PUBLIC

    STG:
      type: snowflake
      account: rf70500.ap-northeast-1.privatelink

      # User/password auth
      user: sajp1.dagster_poc_sys_usr
      password: TKzD|g7aP#uA
      role: FIVETRAN_ROLE
      database: FIVETRAN_DATABASE
      warehouse: FIVETRAN_WAREHOUSE
      schema: ORACLERDS_LZDATA01_DAGSTER_DXPFY2D

    PROD:
      type: 
      account: 

      # User/password auth
      user:
      password:
      role:
      database:
      warehouse:
      schema: