ALERTS:
  REGION: ap-northeast-1
  TOPIC: arn:aws:sns:ap-northeast-1:248810166614:dajp1-dxpf-edp-dev-sns-kestra01
DBT:
  PROJ_DIR: enterprise_data_products
  SNOWFLAKE_ACCOUNT: rf70500.ap-northeast-1.privatelink
  SNOWFLAKE_DATABASE: DATAMART_DB
  SNOWFLAKE_ROLE: DBT_ROLE
  SNOWFLAKE_SCHEMA: public
  SNOWFLAKE_USER: DBT_USER
DBT_DOCS:
  BASE_PATH: dbt_documents/kestra/
  S3_BUCKET: sajp1-dxpf-edp-s3-kestra01
DOCKER:
  IMAGE_VERSION:
    DBT: ghcr.io/dbt-labs/dbt-snowflake:1.9.0
    PYTHON: ghcr.io/jumpserver/python:3.11-slim
ENV: stg
GIT:
  BRANCH: stg_test
  URL: http://ip-100-80-0-121.ap-northeast-1.compute.internal/enterprise_orchestration_products/kestra_dbt_project.git
  USER: kestra.dbt
KUBERNETES:
  MASTER_URL: https://9FDB6138DE76E626E001182949DA8F15.gr7.ap-northeast-1.eks.amazonaws.com
  USER_NAME: arn:aws:eks:ap-northeast-1:085931761001:cluster/sajp1-dxpf-edp-eks-kestra01
NAME: kestra_dbt_project
PYTHON:
  SNOWFLAKE_CONNECTOR_VERSION: snowflake-connector-python[pandas]==3.15.0
SNOWFLAKE:
  ACCOUNT: rf70500.ap-northeast-1.privatelink
  DATABASE: DATAMART_DB
  ROLE: TRF_ACT_ROLE
  SCHEMA: public
  USER: KESTRA_USER
  WAREHOUSE: DATAMART_WH
