DBT:
  PROJ_DIR: enterprise_data_products
  SNOWFLAKE_ROLE: DBT_ROLE
  SNOWFLAKE_USER: DBT_USER
  SNOWFLAKE_SCHEMA: public
  SNOWFLAKE_ACCOUNT: zb43294.ap-northeast-1.privatelink
  SNOWFLAKE_DATABASE: DATAMART_DB
ENV: prod
GIT:
  URL: http://ip-100-80-1-189.ap-northeast-1.compute.internal/enterprise_orchestration_products/kestra_dbt_project.git
  USER: kestra.dbt
  BRANCH: prod
  URL_PATH: ip-100-80-1-189.ap-northeast-1.compute.internal/enterprise_orchestration_products/kestra_dbt_project.git
NAME: kestra_dbt_project
ALERTS:
  TOPIC: arn:aws:sns:ap-northeast-1:433723560297:pajp1-dxpf-edp-sns-kestra01
  REGION: ap-northeast-1
DOCKER:
  IMAGE_VERSION:
    DBT: ghcr.io/dbt-labs/dbt-snowflake:1.9.0
    PYTHON: ghcr.io/jumpserver/python:3.11-slim
PYTHON:
  SNOWFLAKE_CONNECTOR_VERSION: snowflake-connector-python[pandas]==3.15.0
DBT_DOCS:
  BASE_PATH: dbt_documents/kestra/
  S3_BUCKET: pajp1-dxpf-edp-s3-kestra01
SNOWFLAKE:
  ROLE: TRF_ACT_ROLE
  USER: KESTRA_USER
  SCHEMA: public
  ACCOUNT: zb43294.ap-northeast-1.privatelink
  DATABASE: DATAMART_DB
  WAREHOUSE: DATAMART_WH
KUBERNETES:
  REGION: ap-northeast-1
  NAMESPACE: default
  USER_NAME: arn:aws:eks:ap-northeast-1:433723560297:cluster/pajp1-dxpf-edp-eks-kestra01
  MASTER_URL: https://3D1F82E7D700743A0AA7C4066B2F3FA4.gr7.ap-northeast-1.eks.amazonaws.com
  CLUSTER_NAME: sajp1-dxpf-edp-eks-kestra10
EXPORT_AUDIT_LOGS:
  MONTHLY:
    BASE_PATH: Kestra
    S3_BUCKET: pajp1-dxpf-edp-s3-logs01
  MANUALLY:
    BASE_PATH: Kestra/manually
    S3_BUCKET: pajp1-dxpf-edp-s3-ope01
