with substr_n8jfim01 as (
    select
        substr(raw_data, 2, 11)::varchar(11) as hanbaino,
        substr(raw_data, 13, 4)::varchar(4) as syasyu,
        substr(raw_data, 17, 1)::varchar(1) as kategoricd,
        substr(raw_data, 18, 1)::varchar(1) as kscd,
        substr(raw_data, 19, 11)::varchar(11) as mhanbaino,
        substr(raw_data, 30, 11)::varchar(11) as mbhanbaino,
        substr(raw_data, 41, 11)::varchar(11) as mhanbainoed,
        substr(raw_data, 52, 6)::varchar(6) as kirikaeym,
        substr(raw_data, 58, 3)::varchar(3) as kirikaeno,
        substr(raw_data, 61, 3)::varchar(3) as setsuhenno,
        substr(raw_data, 64, 1)::varchar(1) as shijikbn,
        substr(raw_data, 65, 9)::varchar(9) as shijino,
        substr(raw_data, 74, 1)::varchar(1) as clrshkbn,
        substr(raw_data, 75, 10)::varchar(10) as seppenno,
        substr(raw_data, 85, 9)::varchar(9) as clrshijino,
        substr(raw_data, 94, 14)::varchar(14) as hhakkouymd,
        substr(raw_data, 108, 3)::varchar(3) as edptnno,
        substr(raw_data, 111, 1)::varchar(1) as setsikisflg,
        substr(raw_data, 112, 14)::varchar(14) as hikilcymd,
        substr(raw_data, 126, 1)::varchar(1) as hikilc,
        substr(raw_data, 127, 14)::varchar(14) as siyolcymd,
        substr(raw_data, 141, 1)::varchar(1) as siyolc,
        substr(raw_data, 142, 1)::varchar(1) as uchibariflg,
        substr(raw_data, 143, 1)::varchar(1) as release_flg,
        substr(raw_data, 144, 14)::varchar(14) as hkakuteiymd,
        substr(raw_data, 158, 1)::varchar(1) as rmailflg,
        substr(raw_data, 159, 1)::varchar(1) as kataaddflg,
        substr(raw_data, 160, 1)::varchar(1) as katadelflg,
        --備考カラム桁ずれ対応　以降のカラムは末尾からのsubstrで取り込む
        substr(raw_data, -102, 9)::varchar(9) as cd_sksifunc,
        substr(raw_data, -93, 9)::varchar(9) as cd_ksnfunc,
        substr(raw_data, -84, 16)::varchar(16) as cd_sksisya,
        substr(raw_data, -68, 16)::varchar(16) as cd_ksnsya,
        substr(raw_data, -52, 26)::varchar(26) as dt_sakusei,
        substr(raw_data, -26, 26)::varchar(26) as dt_kosin,
        ldts
    from {{source('snowpipe_db_marketing', 'raw_n8jfim01')}}
)
select * from substr_n8jfim01