with substr_ktrla038zz0kaddb01 as (
  select
    substr(raw_data, 1, 6)::varchar(6) as ym,
    substr(raw_data, 7, 2)::varchar(2) as caltimingkbn,
    substr(raw_data, 9, 2)::varchar(2) as shamei,
    substr(raw_data, 11, 2)::varchar(2) as sno,
    substr(raw_data, 13, 3)::varchar(3) as shinq,
    substr(raw_data, 16, 7)::varchar(7) as datarbn_7keta,
    substr(raw_data, 23, 5)::varchar(5) as dlrcd,
    substr(raw_data, 28, 5)::varchar(5) as dlrcd_smksk,
    substr(raw_data, 33, 12)::varchar(12) as odno,
    substr(raw_data, 45, 6)::varchar(6) as nijsym_all,
    substr(raw_data, 51, 6)::varchar(6) as nijsym_seiyakuari,
    substr(raw_data, 57, 6)::varchar(6) as jkeijyotuki,
    substr(raw_data, 63, 6)::varchar(6) as nosyakibotuki,
    substr(raw_data, 69, 5)::varchar(5) as daisu,
    substr(raw_data, 74, 20)::varchar(20) as hckata,
    substr(raw_data, 94, 20)::varchar(20) as hkata,
    substr(raw_data, 114, 4)::varchar(4) as gaicd,
    substr(raw_data, 118, 4)::varchar(4) as ucd,
    substr(raw_data, 122, 3)::varchar(3) as tire,
    substr(raw_data, 125, 80)::varchar(80) as hoption,
    substr(raw_data, 205, 1)::varchar(1) as knkkbnzenkokudumari,
    substr(raw_data, 206, 8)::varchar(8) as jkeijyobi,
    substr(raw_data, 214, 8)::varchar(8) as jrdate,
    substr(raw_data, 222, 8)::varchar(8) as motokndate,
    substr(raw_data, 230, 8)::varchar(8) as sstbi,
    substr(raw_data, 238, 1)::varchar(1) as sstbihan,
    substr(raw_data, 239, 8)::varchar(8) as skkibonk,
    substr(raw_data, 247, 8)::varchar(8) as kibonk,
    substr(raw_data, 255, 1)::varchar(1) as odkbn,
    substr(raw_data, 256, 5)::varchar(5) as odtjun,
    substr(raw_data, 261, 8)::varchar(8) as kibostukistipintome,
    substr(raw_data, 269, 8)::varchar(8) as sydate,
    substr(raw_data, 277, 1)::varchar(1) as haiyouflg,
    substr(raw_data, 278, 1)::varchar(1) as serrmflg,
    substr(raw_data, 279, 22)::varchar(22) as dummy,
    ldts,
    line_number
  from {{ source('snowpipe_db_supplydemand', 'raw_ktrla038zz0kaddb01')}}
)
select * from substr_ktrla038zz0kaddb01
