with substr_tsjfae2b as (
    select
        substr(raw_data, 1, 1)::varchar(1) as maker_kbn,
        substr(raw_data, 2, 7)::varchar(7) as ktsk,
        substr(raw_data, 9, 2)::varchar(2) as sp,
        substr(raw_data, 11, 2)::varchar(2) as op,
        substr(raw_data, 13, 1)::varchar(1) as onkn_kbn,
        substr(raw_data, 14, 2)::varchar(2) as gsclr,
        substr(raw_data, 16, 2)::varchar(2) as nsclr,
        substr(raw_data, 18, 2)::varchar(2) as siyo_no,
        substr(raw_data, 20, 16)::varchar(16) as ksh_ktsk,
        substr(raw_data, 36, 16)::varchar(16) as cntl_ktsk,
        substr(raw_data, 52, 4)::varchar(4) as ghnclr_cd,
        substr(raw_data, 56, 4)::varchar(4) as uchibr_cd,
        substr(raw_data, 60, 200)::varchar(200) as ssn_sp,
        substr(raw_data, 260, 5)::varchar(5) as dfsc,
        substr(raw_data, 265, 6)::varchar(6) as tsho_ym,
        substr(raw_data, 271, 6)::varchar(6) as ssn_ym_tougt,
        substr(raw_data, 277, 5)::varchar(5) as dsu_tougt,
        substr(raw_data, 282, 5)::varchar(5) as db_dsu_d01,
        substr(raw_data, 287, 5)::varchar(5) as db_dsu_d02,
        substr(raw_data, 292, 5)::varchar(5) as db_dsu_d03,
        substr(raw_data, 297, 5)::varchar(5) as db_dsu_d04,
        substr(raw_data, 302, 5)::varchar(5) as db_dsu_d05,
        substr(raw_data, 307, 5)::varchar(5) as db_dsu_d06,
        substr(raw_data, 312, 5)::varchar(5) as db_dsu_d07,
        substr(raw_data, 317, 5)::varchar(5) as db_dsu_d08,
        substr(raw_data, 322, 5)::varchar(5) as db_dsu_d09,
        substr(raw_data, 327, 5)::varchar(5) as db_dsu_d10,
        substr(raw_data, 332, 5)::varchar(5) as db_dsu_d11,
        substr(raw_data, 337, 5)::varchar(5) as db_dsu_d12,
        substr(raw_data, 342, 5)::varchar(5) as db_dsu_d13,
        substr(raw_data, 347, 5)::varchar(5) as db_dsu_d14,
        substr(raw_data, 352, 5)::varchar(5) as db_dsu_d15,
        substr(raw_data, 357, 5)::varchar(5) as db_dsu_d16,
        substr(raw_data, 362, 5)::varchar(5) as db_dsu_d17,
        substr(raw_data, 367, 5)::varchar(5) as db_dsu_d18,
        substr(raw_data, 372, 5)::varchar(5) as db_dsu_d19,
        substr(raw_data, 377, 5)::varchar(5) as db_dsu_d20,
        substr(raw_data, 382, 5)::varchar(5) as db_dsu_d21,
        substr(raw_data, 387, 5)::varchar(5) as db_dsu_d22,
        substr(raw_data, 392, 5)::varchar(5) as db_dsu_d23,
        substr(raw_data, 397, 5)::varchar(5) as db_dsu_d24,
        substr(raw_data, 402, 5)::varchar(5) as db_dsu_d25,
        substr(raw_data, 407, 5)::varchar(5) as db_dsu_d26,
        substr(raw_data, 412, 5)::varchar(5) as db_dsu_d27,
        substr(raw_data, 417, 5)::varchar(5) as db_dsu_d28,
        substr(raw_data, 422, 5)::varchar(5) as db_dsu_d29,
        substr(raw_data, 427, 5)::varchar(5) as db_dsu_d30,
        substr(raw_data, 432, 5)::varchar(5) as db_dsu_d31,
        substr(raw_data, 437, 6)::varchar(6) as ssn_ym_zg1gt,
        substr(raw_data, 443, 5)::varchar(5) as dsu_zg1gt,
        substr(raw_data, 448, 6)::varchar(6) as ssn_ym_zg2gt,
        substr(raw_data, 454, 5)::varchar(5) as dsu_zg2gt,
        substr(raw_data, 459, 11)::varchar(11) as knfugo,
        substr(raw_data, 470, 2)::varchar(2) as idline,
        substr(raw_data, 472, 2)::varchar(2) as syamei,
        substr(raw_data, 474, 1)::varchar(1) as simuke,
        substr(raw_data, 475, 26)::varchar(26) as dummy,
        ldts,
        line_number
   from {{ source('snowpipe_db_supplydemand', 'raw_tsjfae2b') }}
)
select * from substr_tsjfae2b