with
    substr_ktrla038zz0kadda01 as (
        select
            to_varchar(substr(raw_data, 1, 6), 'utf-8')::varchar(6) as ym,
            to_varchar(substr(raw_data, 7, 2), 'utf-8')::varchar(2) as caltimingkbn,
            to_varchar(substr(raw_data, 9, 1), 'utf-8')::varchar(1) as bukbn,
            to_varchar(substr(raw_data, 10, 2), 'utf-8')::varchar(2) as shamei,
            to_varchar(substr(raw_data, 12, 2), 'utf-8')::varchar(2) as sno,
            to_varchar(substr(raw_data, 14, 1), 'utf-8')::varchar(1) as yosokbn,
            to_varchar(substr(raw_data, 15, 5), 'utf-8')::varchar(5) as yosoren,
            to_varchar(substr(raw_data, 20, 20), 'utf-8')::varchar(20) as hckata,
            to_varchar(substr(raw_data, 40, 4), 'utf-8')::varchar(4) as gaicd,
            to_varchar(substr(raw_data, 44, 4), 'utf-8')::varchar(4) as ucd,
            to_varchar(substr(raw_data, 48, 3), 'utf-8')::varchar(3) as tire,
            to_varchar(substr(raw_data, 51, 80), 'utf-8')::varchar(80) as hoption,
            to_varchar(substr(raw_data, 131, 5), 'utf-8')::varchar(5) as haisyaybdain,
            to_varchar(substr(raw_data, 136, 5), 'utf-8')::varchar(5) as haisyaybdain1,
            to_varchar(substr(raw_data, 141, 5), 'utf-8')::varchar(5) as haisyaybdain2,
            to_varchar(substr(raw_data, 146, 5), 'utf-8')::varchar(5) as haisyaybdain3,
            to_varchar(substr(raw_data, 151, 5), 'utf-8')::varchar(5) as haisyaybdain4,
            to_varchar(substr(raw_data, 156, 5), 'utf-8')::varchar(5) as haisyaybdain5,
            to_varchar(substr(raw_data, 161, 5), 'utf-8')::varchar(5) as haisyaybdain6,
            to_varchar(substr(raw_data, 166, 5), 'utf-8')::varchar(5) as haisyaybdain7,
            to_varchar(substr(raw_data, 171, 5), 'utf-8')::varchar(5) as haisyaybdain8,
            to_varchar(substr(raw_data, 176, 5), 'utf-8')::varchar(5) as haisyaybdain9,
            to_varchar(substr(raw_data, 181, 5), 'utf-8')::varchar(5) as haisyaybdain10,
            to_varchar(substr(raw_data, 186, 5), 'utf-8')::varchar(5) as haisyaybdain11,
            to_varchar(substr(raw_data, 191, 5), 'utf-8')::varchar(5) as haisyaybdain12,
            to_varchar(substr(raw_data, 196, 5), 'utf-8')::varchar(5) as haisyaybdain13,
            to_varchar(substr(raw_data, 201, 5), 'utf-8')::varchar(5) as haisyaybdain14,
            to_varchar(substr(raw_data, 206, 5), 'utf-8')::varchar(5) as haisyaybdain15,
            to_varchar(substr(raw_data, 211, 5), 'utf-8')::varchar(5) as haisyaybdain16,
            to_varchar(substr(raw_data, 216, 5), 'utf-8')::varchar(5) as haisyaybdain17,
            to_varchar(substr(raw_data, 221, 5), 'utf-8')::varchar(5) as haisyaybdain18,
            to_varchar(substr(raw_data, 226, 5), 'utf-8')::varchar(5) as haisyaybdain19,
            to_varchar(substr(raw_data, 231, 5), 'utf-8')::varchar(5) as haisyaybdain20,
            to_varchar(substr(raw_data, 236, 5), 'utf-8')::varchar(5) as haisyaybdain21,
            to_varchar(substr(raw_data, 241, 5), 'utf-8')::varchar(5) as haisyaybdain22,
            to_varchar(substr(raw_data, 246, 5), 'utf-8')::varchar(5) as haisyaybdain23,
            to_varchar(substr(raw_data, 251, 1), 'utf-8')::varchar(1) as jdumflg,
            to_varchar(substr(raw_data, 252, 1), 'utf-8')::varchar(1) as haiyouflg,
            to_varchar(substr(raw_data, 253, 1), 'utf-8')::varchar(1) as serrmflg,
            to_varchar(substr(raw_data, 254, 1), 'utf-8')::varchar(1) as haiybknssrj,
            to_varchar(substr(raw_data, 255, 14), 'utf-8')::varchar(14) as haiybknsjji,
            to_varchar(substr(raw_data, 269, 85), 'utf-8')::varchar(85) as haiybknserrjyoho,
            to_varchar(substr(raw_data, 354, 18), 'utf-8')::varchar(18) as mtuser,
            to_varchar(substr(raw_data, 372, 26), 'utf-8')::varchar(26) as mttime,
            ldts,
            line_number
        from {{ ref('byte_ktrla038zz0kadda01') }}
    )
select * from substr_ktrla038zz0kadda01
