id: job_call_sms_api_parts_info
namespace: kestra_dbt_project.proj-job-api-call

labels:
  error: default_failed

retry:
  behavior: CREATE_NEW_EXECUTION # or RETRY_FAILED_TASK 
  type: exponential
  interval: PT5S
  maxAttempts: 7
  maxInterval: PT720S
  delayFactor: 30

tasks:
  - id: python
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
      include:
        - python/api_call_kitora/api_util.py
        - python/api_call_kitora/assets_sms.py
    commands:
      - python python/api_call_kitora/assets_sms.py
    env:
      ENV: "{{ namespace.ENV }}"
      SNOWFLAKE_ACCOUNT: "{{ namespace.SNOWFLAKE.ACCOUNT }}"
      SNOWFLAKE_USER: "{{ namespace.SNOWFLAKE.USER }}"
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE_KESTRA: "{{ secret('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE_KESTRA') }}"
      SNOWFLAKE_PRIVATE_KEY_KESTRA: "{{ secret('SNOWFLAKE_PRIVATE_KEY_KESTRA') }}"
      SNOWFLAKE_ROLE: "{{ namespace.SNOWFLAKE.ROLE }}"
      X_TMC_CLIENT_ID_SMS: "{{ secret('X_TMC_CLIENT_ID_SMS') }}"
      X_TMC_CLIENT_SECRET_SMS: "{{ secret('X_TMC_CLIENT_SECRET_SMS') }}"
      X_TMC_ZDFW_USERID_SMS: "{{ secret('X_TMC_ZDFW_USERID_SMS') }}"
      X_TMC_ZDFW_COMPCODE_SMS: "{{ secret('X_TMC_ZDFW_COMPCODE_SMS') }}"
  
triggers:
  - id: flow_trigger
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: flows
      flows:
        - namespace: kestra_dbt_project.proj-job-sms-kousei
          flowId: job_build_tmp_sms_api_parts_info_req_json
          states: [SUCCESS]

# エラーログを出力
errors:
  - id: error_log
    type: io.kestra.plugin.core.debug.Return
    format: "{{ errorLogs()[0]['message'] }}"

outputs: 
  - id: output_error_log
    type: STRING
    value: "{{ outputs.error_log.value ?? 'No message found.' }}"
  - id: output_state
    type: STRING
    value: "{{ tasks.python.state ?? 'No state' }}"
      
disabled: false